<?php

/**
 * Shared high-frequency EN → locale phrases for admin chrome.
 * Long/unique sentences live in tools/overlays/{locale}.php after merge.
 */
return [
    'Add' => ['de' => 'Hinzufügen', 'es' => 'Añadir', 'fr' => 'Ajouter', 'ko' => '추가', 'pt' => 'Adicionar'],
    'Edit' => ['de' => 'Bearbeiten', 'es' => 'Editar', 'fr' => 'Modifier', 'ko' => '수정', 'pt' => 'Editar'],
    'Save' => ['de' => 'Speichern', 'es' => 'Guardar', 'fr' => 'Enregistrer', 'ko' => '저장', 'pt' => 'Guardar'],
    'Cancel' => ['de' => 'Abbrechen', 'es' => 'Cancelar', 'fr' => 'Annuler', 'ko' => '취소', 'pt' => 'Cancelar'],
    'Close' => ['de' => 'Schließen', 'es' => 'Cerrar', 'fr' => 'Fermer', 'ko' => '닫기', 'pt' => 'Fechar'],
    'Delete' => ['de' => 'Löschen', 'es' => 'Eliminar', 'fr' => 'Supprimer', 'ko' => '삭제', 'pt' => 'Eliminar'],
    'Search' => ['de' => 'Suchen', 'es' => 'Buscar', 'fr' => 'Rechercher', 'ko' => '검색', 'pt' => 'Pesquisar'],
    'Reset' => ['de' => 'Zurücksetzen', 'es' => 'Restablecer', 'fr' => 'Réinitialiser', 'ko' => '초기화', 'pt' => 'Repor'],
    'Are you sure?' => ['de' => 'Sind Sie sicher?', 'es' => '¿Confirmar?', 'fr' => 'Confirmer ?', 'ko' => '진행할까요?', 'pt' => 'Tem a certeza?'],
    'OK' => ['de' => 'OK', 'es' => 'OK', 'fr' => 'OK', 'ko' => 'OK', 'pt' => 'OK'],
    'Failed' => ['de' => 'Fehlgeschlagen', 'es' => 'Error', 'fr' => 'Échec', 'ko' => '실패', 'pt' => 'Falhou'],
    'Saved' => ['de' => 'Gespeichert', 'es' => 'Guardado', 'fr' => 'Enregistré', 'ko' => '저장됨', 'pt' => 'Guardado'],
    'Created' => ['de' => 'Erstellt', 'es' => 'Creado', 'fr' => 'Créé', 'ko' => '생성됨', 'pt' => 'Criado'],
    'Deleted' => ['de' => 'Gelöscht', 'es' => 'Eliminado', 'fr' => 'Supprimé', 'ko' => '삭제됨', 'pt' => 'Eliminado'],
    'Added' => ['de' => 'Hinzugefügt', 'es' => 'Añadido', 'fr' => 'Ajouté', 'ko' => '추가됨', 'pt' => 'Adicionado'],
    'Done' => ['de' => 'Fertig', 'es' => 'Listo', 'fr' => 'Terminé', 'ko' => '완료', 'pt' => 'Concluído'],
    'Upload' => ['de' => 'Hochladen', 'es' => 'Subir', 'fr' => 'Téléverser', 'ko' => '업로드', 'pt' => 'Carregar'],
    'Front' => ['de' => 'Website', 'es' => 'Sitio', 'fr' => 'Site', 'ko' => '사이트', 'pt' => 'Site'],
    'View site' => ['de' => 'Website öffnen', 'es' => 'Ver el sitio', 'fr' => 'Voir le site', 'ko' => '사이트 보기', 'pt' => 'Ver o site'],
    'Full form' => ['de' => 'Vollformular', 'es' => 'Formulario completo', 'fr' => 'Formulaire complet', 'ko' => '전체 양식', 'pt' => 'Formulário completo'],
    'Quick' => ['de' => 'Schnell', 'es' => 'Rápido', 'fr' => 'Rapide', 'ko' => '빠른 추가', 'pt' => 'Rápido'],
    'More fields' => ['de' => 'Weitere Felder', 'es' => 'Más campos', 'fr' => 'Plus de champs', 'ko' => '자세히 입력', 'pt' => 'Mais campos'],
    'Actions' => ['de' => 'Aktionen', 'es' => 'Acciones', 'fr' => 'Actions', 'ko' => '작업', 'pt' => 'Ações'],
    'Status' => ['de' => 'Status', 'es' => 'Estado', 'fr' => 'Statut', 'ko' => '상태', 'pt' => 'Estado'],
    'Sort' => ['de' => 'Sortierung', 'es' => 'Orden', 'fr' => 'Ordre', 'ko' => '정렬', 'pt' => 'Ordem'],
    'On' => ['de' => 'An', 'es' => 'Activo', 'fr' => 'Activé', 'ko' => '공개', 'pt' => 'Ativo'],
    'Off' => ['de' => 'Aus', 'es' => 'Inactivo', 'fr' => 'Désactivé', 'ko' => '비공개', 'pt' => 'Inativo'],
    'Enabled' => ['de' => 'Aktiv', 'es' => 'Activado', 'fr' => 'Activé', 'ko' => '사용', 'pt' => 'Ativado'],
    'Disabled' => ['de' => 'Deaktiviert', 'es' => 'Desactivado', 'fr' => 'Désactivé', 'ko' => '중지', 'pt' => 'Desativado'],
    'Pending' => ['de' => 'Prüfung', 'es' => 'Pendiente', 'fr' => 'En attente', 'ko' => '심사 대기', 'pt' => 'Pendente'],
    'Uncategorized' => ['de' => 'Ohne Kategorie', 'es' => 'Sin categoría', 'fr' => 'Sans catégorie', 'ko' => '미분류', 'pt' => 'Sem categoria'],
    'All categories' => ['de' => 'Alle Kategorien', 'es' => 'Todas las categorías', 'fr' => 'Toutes les catégories', 'ko' => '모든 분류', 'pt' => 'Todas as categorias'],
    ':n selected' => ['de' => ':n ausgewählt', 'es' => ':n seleccionados', 'fr' => ':n sélectionné(s)', 'ko' => ':n개 선택', 'pt' => ':n selecionados'],
    'Clear selection' => ['de' => 'Auswahl aufheben', 'es' => 'Quitar selección', 'fr' => 'Effacer la sélection', 'ko' => '선택 해제', 'pt' => 'Limpar seleção'],
    'Clear filters' => ['de' => 'Filter leeren', 'es' => 'Quitar filtros', 'fr' => 'Effacer les filtres', 'ko' => '필터 지우기', 'pt' => 'Limpar filtros'],
    'No matching records' => ['de' => 'Keine Treffer', 'es' => 'Sin coincidencias', 'fr' => 'Aucun résultat', 'ko' => '일치하는 항목 없음', 'pt' => 'Sem resultados'],
    'Select items first' => ['de' => 'Bitte zuerst Einträge wählen', 'es' => 'Seleccione elementos primero', 'fr' => 'Sélectionnez d’abord des éléments', 'ko' => '먼저 항목을 선택하세요', 'pt' => 'Selecione itens primeiro'],
    'None yet' => ['de' => 'Noch keine', 'es' => 'Todavía ninguno', 'fr' => 'Aucun pour l’instant', 'ko' => '아직 없음', 'pt' => 'Ainda nenhum'],
    'Works' => ['de' => 'Werke', 'es' => 'Obras', 'fr' => 'Œuvres', 'ko' => '작품', 'pt' => 'Obras'],
    'Chapters' => ['de' => 'Kapitel', 'es' => 'Capítulos', 'fr' => 'Chapitres', 'ko' => '회차', 'pt' => 'Capítulos'],
    'Images' => ['de' => 'Bilder', 'es' => 'Imágenes', 'fr' => 'Images', 'ko' => '이미지', 'pt' => 'Imagens'],
    'Categories' => ['de' => 'Kategorien', 'es' => 'Categorías', 'fr' => 'Catégories', 'ko' => '분류', 'pt' => 'Categorias'],
    'Comments' => ['de' => 'Kommentare', 'es' => 'Comentarios', 'fr' => 'Commentaires', 'ko' => '댓글', 'pt' => 'Comentários'],
    'Favorites' => ['de' => 'Favoriten', 'es' => 'Favoritos', 'fr' => 'Favoris', 'ko' => '즐겨찾기', 'pt' => 'Favoritos'],
    'Bookshelf' => ['de' => 'Bücherregal', 'es' => 'Estantería', 'fr' => 'Étagère', 'ko' => '책장', 'pt' => 'Estante'],
    'Stats' => ['de' => 'Statistik', 'es' => 'Estadísticas', 'fr' => 'Statistiques', 'ko' => '통계', 'pt' => 'Estatísticas'],
    'Tags' => ['de' => 'Tags', 'es' => 'Etiquetas', 'fr' => 'Tags', 'ko' => '태그', 'pt' => 'Etiquetas'],
    'Authors' => ['de' => 'Autoren', 'es' => 'Autores', 'fr' => 'Auteurs', 'ko' => '작가', 'pt' => 'Autores'],
    'All' => ['de' => 'Alle', 'es' => 'Todo', 'fr' => 'Tout', 'ko' => '전체', 'pt' => 'Tudo'],
    'Videos' => ['de' => 'Videos', 'es' => 'Vídeos', 'fr' => 'Vidéos', 'ko' => '영상', 'pt' => 'Vídeos'],
    'Add video' => ['de' => 'Video hinzufügen', 'es' => 'Añadir vídeo', 'fr' => 'Ajouter une vidéo', 'ko' => '영상 추가', 'pt' => 'Adicionar vídeo'],
    'Recycle bin' => ['de' => 'Papierkorb', 'es' => 'Papelera', 'fr' => 'Corbeille', 'ko' => '휴지통', 'pt' => 'Reciclagem'],
    'Search title' => ['de' => 'Titel suchen', 'es' => 'Buscar título', 'fr' => 'Rechercher un titre', 'ko' => '제목 검색', 'pt' => 'Pesquisar título'],
    'More filters' => ['de' => 'Mehr Filter', 'es' => 'Más filtros', 'fr' => 'Plus de filtres', 'ko' => '필터 더보기', 'pt' => 'Mais filtros'],
    'No URL' => ['de' => 'Keine URL', 'es' => 'Sin URL', 'fr' => 'Sans URL', 'ko' => 'URL 없음', 'pt' => 'Sem URL'],
    'No cover' => ['de' => 'Kein Cover', 'es' => 'Sin portada', 'fr' => 'Sans jaquette', 'ko' => '표지 없음', 'pt' => 'Sem capa'],
    'Duplicates' => ['de' => 'Duplikate', 'es' => 'Duplicados', 'fr' => 'Doublons', 'ko' => '중복', 'pt' => 'Duplicados'],
    'Fill-in & tools' => ['de' => 'Nachpflege & Werkzeuge', 'es' => 'Completar y herramientas', 'fr' => 'Compléter et outils', 'ko' => '보완 · 도구', 'pt' => 'Preencher e ferramentas'],
    'Points' => ['de' => 'Punkte', 'es' => 'Puntos', 'fr' => 'Points', 'ko' => '포인트', 'pt' => 'Pontos'],
    'Updated' => ['de' => 'Aktualisiert', 'es' => 'Actualizado', 'fr' => 'Mis à jour', 'ko' => '수정됨', 'pt' => 'Atualizado'],
    'Library is empty' => ['de' => 'Die Mediathek ist leer', 'es' => 'La mediateca está vacía', 'fr' => 'La médiathèque est vide', 'ko' => '영상 라이브러리가 비어 있습니다', 'pt' => 'A biblioteca está vazia'],
    'Connect a collect source, or add a video manually.' => [
        'de' => 'Sammeln Sie eine Quelle an, oder fügen Sie ein Video manuell hinzu.',
        'es' => 'Conecte una fuente de recolección o añada un vídeo a mano.',
        'fr' => 'Connectez une source de collecte, ou ajoutez une vidéo à la main.',
        'ko' => '수집원을 연결하거나 영상을 직접 추가하세요.',
        'pt' => 'Ligue uma fonte de recolha, ou adicione um vídeo manualmente.',
    ],
    'Collect' => ['de' => 'Sammeln', 'es' => 'Recolectar', 'fr' => 'Collecter', 'ko' => '수집', 'pt' => 'Recolher'],
    'Draft' => ['de' => 'Entwurf', 'es' => 'Borrador', 'fr' => 'Brouillon', 'ko' => '초안', 'pt' => 'Rascunho'],
    'Rejected' => ['de' => 'Abgelehnt', 'es' => 'Rechazado', 'fr' => 'Rejeté', 'ko' => '반려', 'pt' => 'Rejeitado'],
    'Scheduled' => ['de' => 'Geplant', 'es' => 'Programado', 'fr' => 'Planifié', 'ko' => '예약', 'pt' => 'Agendado'],
    'Title' => ['de' => 'Titel', 'es' => 'Título', 'fr' => 'Titre', 'ko' => '제목', 'pt' => 'Título'],
    'Name' => ['de' => 'Name', 'es' => 'Nombre', 'fr' => 'Nom', 'ko' => '이름', 'pt' => 'Nome'],
    'Cover' => ['de' => 'Cover', 'es' => 'Portada', 'fr' => 'Jaquette', 'ko' => '표지', 'pt' => 'Capa'],
    'Optional' => ['de' => 'Optional', 'es' => 'Opcional', 'fr' => 'Facultatif', 'ko' => '선택', 'pt' => 'Opcional'],
    'Today' => ['de' => 'Heute', 'es' => 'Hoy', 'fr' => 'Aujourd’hui', 'ko' => '오늘', 'pt' => 'Hoje'],
    'Hits' => ['de' => 'Aufrufe', 'es' => 'Visitas', 'fr' => 'Vues', 'ko' => '조회', 'pt' => 'Visualizações'],
    'Recommend' => ['de' => 'Empfehlen', 'es' => 'Recomendar', 'fr' => 'Recommander', 'ko' => '추천', 'pt' => 'Recomendar'],
    'Visible' => ['de' => 'Sichtbar', 'es' => 'Visible', 'fr' => 'Visible', 'ko' => '표시', 'pt' => 'Visível'],
    'Back' => ['de' => 'Zurück', 'es' => 'Volver', 'fr' => 'Retour', 'ko' => '뒤로', 'pt' => 'Voltar'],
    'Member' => ['de' => 'Mitglied', 'es' => 'Miembro', 'fr' => 'Membre', 'ko' => '회원', 'pt' => 'Membro'],
    'Free' => ['de' => 'Kostenlos', 'es' => 'Gratis', 'fr' => 'Gratuit', 'ko' => '무료', 'pt' => 'Gratuito'],
    'Time' => ['de' => 'Zeit', 'es' => 'Hora', 'fr' => 'Heure', 'ko' => '시간', 'pt' => 'Hora'],
    'Content' => ['de' => 'Inhalt', 'es' => 'Contenido', 'fr' => 'Contenu', 'ko' => '내용', 'pt' => 'Conteúdo'],
    'Nickname' => ['de' => 'Spitzname', 'es' => 'Apodo', 'fr' => 'Pseudo', 'ko' => '닉네임', 'pt' => 'Alcunha'],
    'Articles' => ['de' => 'Artikel', 'es' => 'Artículos', 'fr' => 'Articles', 'ko' => '기사', 'pt' => 'Artigos'],
    'Sites' => ['de' => 'Websites', 'es' => 'Sitios', 'fr' => 'Sites', 'ko' => '사이트', 'pt' => 'Sites'],
    'Topics' => ['de' => 'Themen', 'es' => 'Temas', 'fr' => 'Thèmes', 'ko' => '특집', 'pt' => 'Temas'],
    'Actors' => ['de' => 'Schauspieler', 'es' => 'Actores', 'fr' => 'Acteurs', 'ko' => '배우', 'pt' => 'Atores'],
    'Settings' => ['de' => 'Einstellungen', 'es' => 'Ajustes', 'fr' => 'Réglages', 'ko' => '설정', 'pt' => 'Definições'],
    'Refresh' => ['de' => 'Aktualisieren', 'es' => 'Actualizar', 'fr' => 'Actualiser', 'ko' => '새로고침', 'pt' => 'Atualizar'],
    'Refreshed' => ['de' => 'Aktualisiert', 'es' => 'Actualizado', 'fr' => 'Actualisé', 'ko' => '새로고침됨', 'pt' => 'Atualizado'],
    'Remove' => ['de' => 'Entfernen', 'es' => 'Quitar', 'fr' => 'Retirer', 'ko' => '제거', 'pt' => 'Remover'],
    'Yes' => ['de' => 'Ja', 'es' => 'Sí', 'fr' => 'Oui', 'ko' => '예', 'pt' => 'Sim'],
    'No' => ['de' => 'Nein', 'es' => 'No', 'fr' => 'Non', 'ko' => '아니요', 'pt' => 'Não'],
    'Lock' => ['de' => 'Sperren', 'es' => 'Bloquear', 'fr' => 'Verrouiller', 'ko' => '잠금', 'pt' => 'Bloquear'],
    'Locked' => ['de' => 'Gesperrt', 'es' => 'Bloqueado', 'fr' => 'Verrouillé', 'ko' => '잠김', 'pt' => 'Bloqueado'],
    'Unlocked' => ['de' => 'Entsperrt', 'es' => 'Desbloqueado', 'fr' => 'Déverrouillé', 'ko' => '잠금 해제', 'pt' => 'Desbloqueado'],
    'Hot' => ['de' => 'Beliebt', 'es' => 'Popular', 'fr' => 'Populaire', 'ko' => '인기', 'pt' => 'Popular'],
    'Move' => ['de' => 'Verschieben', 'es' => 'Mover', 'fr' => 'Déplacer', 'ko' => '이동', 'pt' => 'Mover'],
    'Show' => ['de' => 'Anzeigen', 'es' => 'Mostrar', 'fr' => 'Afficher', 'ko' => '표시', 'pt' => 'Mostrar'],
    'Hide' => ['de' => 'Ausblenden', 'es' => 'Ocultar', 'fr' => 'Masquer', 'ko' => '숨기기', 'pt' => 'Ocultar'],
    'Hidden' => ['de' => 'Versteckt', 'es' => 'Oculto', 'fr' => 'Masqué', 'ko' => '숨김', 'pt' => 'Oculto'],
    'Open' => ['de' => 'Öffnen', 'es' => 'Abrir', 'fr' => 'Ouvrir', 'ko' => '열기', 'pt' => 'Abrir'],
    'Members' => ['de' => 'Mitglieder', 'es' => 'Miembros', 'fr' => 'Membres', 'ko' => '회원', 'pt' => 'Membros'],
    'Add work' => ['de' => 'Werk hinzufügen', 'es' => 'Añadir obra', 'fr' => 'Ajouter une œuvre', 'ko' => '작품 추가', 'pt' => 'Adicionar obra'],
    'Add category' => ['de' => 'Kategorie hinzufügen', 'es' => 'Añadir categoría', 'fr' => 'Ajouter une catégorie', 'ko' => '분류 추가', 'pt' => 'Adicionar categoria'],
    'Add chapter' => ['de' => 'Kapitel hinzufügen', 'es' => 'Añadir capítulo', 'fr' => 'Ajouter un chapitre', 'ko' => '회차 추가', 'pt' => 'Adicionar capítulo'],
    'Add tag' => ['de' => 'Tag hinzufügen', 'es' => 'Añadir etiqueta', 'fr' => 'Ajouter un tag', 'ko' => '태그 추가', 'pt' => 'Adicionar etiqueta'],
    'Add actor' => ['de' => 'Schauspieler hinzufügen', 'es' => 'Añadir actor', 'fr' => 'Ajouter un acteur', 'ko' => '배우 추가', 'pt' => 'Adicionar ator'],
    'Add author' => ['de' => 'Autor hinzufügen', 'es' => 'Añadir autor', 'fr' => 'Ajouter un auteur', 'ko' => '작가 추가', 'pt' => 'Adicionar autor'],
    'Batch add' => ['de' => 'Stapel hinzufügen', 'es' => 'Añadir por lote', 'fr' => 'Ajout groupé', 'ko' => '일괄 추가', 'pt' => 'Adicionar em lote'],
    'Unused' => ['de' => 'Ungenutzt', 'es' => 'Sin uso', 'fr' => 'Inutilisé', 'ko' => '미사용', 'pt' => 'Não usado'],
    'No comments yet' => ['de' => 'Noch keine Kommentare', 'es' => 'Aún no hay comentarios', 'fr' => 'Pas encore de commentaires', 'ko' => '댓글이 없습니다', 'pt' => 'Ainda sem comentários'],
    'No categories yet' => ['de' => 'Noch keine Kategorien', 'es' => 'Aún no hay categorías', 'fr' => 'Pas encore de catégories', 'ko' => '분류가 없습니다', 'pt' => 'Ainda sem categorias'],
    'Untitled' => ['de' => 'Ohne Titel', 'es' => 'Sin título', 'fr' => 'Sans titre', 'ko' => '제목 없음', 'pt' => 'Sem título'],
    'Message' => ['de' => 'Nachricht', 'es' => 'Mensaje', 'fr' => 'Message', 'ko' => '메시지', 'pt' => 'Mensagem'],
    'Code' => ['de' => 'Code', 'es' => 'Código', 'fr' => 'Code', 'ko' => '코드', 'pt' => 'Código'],
    'Roles' => ['de' => 'Rollen', 'es' => 'Roles', 'fr' => 'Rôles', 'ko' => '역할', 'pt' => 'Funções'],
    'Basics' => ['de' => 'Basis', 'es' => 'Básico', 'fr' => 'Base', 'ko' => '기본', 'pt' => 'Básico'],
    'Display' => ['de' => 'Anzeige', 'es' => 'Visualización', 'fr' => 'Affichage', 'ko' => '표시', 'pt' => 'Apresentação'],
    'Playback' => ['de' => 'Wiedergabe', 'es' => 'Reproducción', 'fr' => 'Lecture', 'ko' => '재생', 'pt' => 'Reprodução'],
    'Subtitle' => ['de' => 'Untertitel', 'es' => 'Subtítulo', 'fr' => 'Sous-titre', 'ko' => '부제', 'pt' => 'Subtítulo'],
    'Remarks' => ['de' => 'Hinweis', 'es' => 'Notas', 'fr' => 'Remarques', 'ko' => '비고', 'pt' => 'Notas'],
    'Intro' => ['de' => 'Einleitung', 'es' => 'Introducción', 'fr' => 'Présentation', 'ko' => '소개', 'pt' => 'Introdução'],
    'Image' => ['de' => 'Bild', 'es' => 'Imagen', 'fr' => 'Image', 'ko' => '이미지', 'pt' => 'Imagem'],
    'Keyword' => ['de' => 'Stichwort', 'es' => 'Palabra clave', 'fr' => 'Mot-clé', 'ko' => '키워드', 'pt' => 'Palavra-chave'],
    'Last 7 days' => ['de' => 'Letzte 7 Tage', 'es' => 'Últimos 7 días', 'fr' => '7 derniers jours', 'ko' => '최근 7일', 'pt' => 'Últimos 7 dias'],
    'Last 30 days' => ['de' => 'Letzte 30 Tage', 'es' => 'Últimos 30 días', 'fr' => '30 derniers jours', 'ko' => '최근 30일', 'pt' => 'Últimos 30 dias'],
    'Clear search' => ['de' => 'Suche leeren', 'es' => 'Quitar búsqueda', 'fr' => 'Effacer la recherche', 'ko' => '검색 지우기', 'pt' => 'Limpar pesquisa'],
    'Open front end' => ['de' => 'Website öffnen', 'es' => 'Abrir el sitio', 'fr' => 'Ouvrir le site', 'ko' => '사이트 열기', 'pt' => 'Abrir o site'],
    'Select' => ['de' => 'Wählen', 'es' => 'Seleccionar', 'fr' => 'Sélectionner', 'ko' => '선택', 'pt' => 'Selecionar'],
    'None' => ['de' => 'Keine', 'es' => 'Ninguno', 'fr' => 'Aucun', 'ko' => '없음', 'pt' => 'Nenhum'],
];
