<?php

/**
 * Admin user toasts/labels, safety known-map, schedule toasts, rewrite labels, gender.
 * Applied by tools/patch-display-i18n.php.
 */
$t = static fn (
    string $en,
    string $zh,
    string $de,
    string $es,
    string $fr,
    string $ko,
    string $pt,
    string $ja,
): array => [
    'en' => $en,
    'zh_cn' => $zh,
    'de' => $de,
    'es' => $es,
    'fr' => $fr,
    'ko' => $ko,
    'pt' => $pt,
    'ja' => $ja,
];

return [
    'ui.username_min2' => $t('Username needs at least 2 characters', '登录名至少 2 个字', 'Anmeldename mindestens 2 Zeichen', 'El usuario necesita al menos 2 caracteres', 'L’identifiant doit faire au moins 2 caractères', '로그인 이름은 2자 이상', 'O utilizador precisa de pelo menos 2 caracteres', 'ログイン名は2文字以上'),
    'ui.username_taken' => $t('That username is already used', '这个登录名已经有人用了', 'Dieser Anmeldename ist schon vergeben', 'Ese usuario ya está usado', 'Cet identifiant est déjà pris', '그 로그인 이름은 이미 있습니다', 'Esse utilizador já está a ser usado', 'そのログイン名は既に使われています'),
    'ui.add_fail' => $t('Could not add', '没能添加', 'Hinzufügen fehlgeschlagen', 'No se pudo añadir', 'Ajout impossible', '추가하지 못했습니다', 'Não deu para adicionar', '追加できませんでした'),
    'ui.added_can_login' => $t('Added. They can sign in to the admin.', '已添加，可以登录后台', 'Hinzugefügt. Sie können sich an der Verwaltung anmelden.', 'Añadido. Pueden entrar al panel.', 'Ajouté. Ils peuvent se connecter à l’admin.', '추가됨. 관리 화면에 로그인할 수 있습니다.', 'Adicionado. Podem entrar na administração.', '追加しました。管理画面にログインできます。'),
    'ui.admin_missing' => $t('Admin not found', '管理员不存在', 'Admin nicht gefunden', 'Admin no encontrado', 'Admin introuvable', '관리자가 없습니다', 'Admin não encontrado', '管理者がいません'),
    'ui.cant_save' => $t('Could not save', '没能保存', 'Speichern fehlgeschlagen', 'No se pudo guardar', 'Enregistrement impossible', '저장하지 못했습니다', 'Não deu para guardar', '保存できませんでした'),
    'ui.founder_no_delete' => $t('The founder cannot be deleted', '创始人不能删', 'Der Gründer kann nicht gelöscht werden', 'El fundador no se puede borrar', 'Le fondateur ne peut pas être supprimé', '창립자는 삭제할 수 없습니다', 'O fundador não pode ser apagado', '創設者は削除できません'),
    'ui.cannot_delete_self' => $t('You cannot delete the account you are using', '不能删自己正在用的账号', 'Sie können das Konto, das Sie nutzen, nicht löschen', 'No puede borrar la cuenta que está usando', 'Vous ne pouvez pas supprimer le compte que vous utilisez', '지금 쓰는 계정은 삭제할 수 없습니다', 'Não pode apagar a conta que está a usar', '使っているアカウントは削除できません'),
    'ui.keep_one_admin' => $t('Keep at least one admin', '至少留一位管理员', 'Mindestens einen Admin behalten', 'Deje al menos un admin', 'Gardez au moins un admin', '관리자를 한 명은 남겨 두세요', 'Fique pelo menos um admin', '管理者を少なくとも一人残してください'),
    'ui.cant_delete' => $t('Could not delete', '没能删除', 'Löschen fehlgeschlagen', 'No se pudo borrar', 'Suppression impossible', '삭제하지 못했습니다', 'Não deu para apagar', '削除できませんでした'),
    'ui.no_role_assigned' => $t('No role assigned', '未分角色', 'Keine Rolle', 'Sin rol asignado', 'Aucun rôle', '역할 없음', 'Sem função', '役割なし'),
    'ui.logout_ok' => $t('Signed out', '退出成功', 'Abgemeldet', 'Sesión cerrada', 'Déconnecté', '로그아웃됨', 'Sessão terminada', 'ログアウトしました'),
    'ui.not_signed_in' => $t('Not signed in', '未登录', 'Nicht angemeldet', 'No ha iniciado sesión', 'Non connecté', '로그인되지 않음', 'Não tem sessão', '未ログイン'),
    'ui.need_current_password' => $t('Enter the current password', '请输入当前密码', 'Aktuelles Passwort eingeben', 'Escriba la contraseña actual', 'Saisissez le mot de passe actuel', '현재 비밀번호를 입력하세요', 'Introduza a palavra-passe atual', '現在のパスワードを入力してください'),
    'ui.need_new_password' => $t('Enter a new password', '请输入新密码', 'Neues Passwort eingeben', 'Escriba una contraseña nueva', 'Saisissez un nouveau mot de passe', '새 비밀번호를 입력하세요', 'Introduza uma palavra-passe nova', '新しいパスワードを入力してください'),
    'ui.new_password_min6' => $t('New password needs at least 6 characters', '新密码至少6位', 'Neues Passwort mindestens 6 Zeichen', 'La nueva contraseña necesita al menos 6 caracteres', 'Le nouveau mot de passe doit faire au moins 6 caractères', '새 비밀번호는 6자 이상', 'A palavra-passe nova precisa de pelo menos 6 caracteres', '新しいパスワードは6文字以上'),
    'ui.passwords_mismatch' => $t('The two new passwords do not match', '两次新密码不一致', 'Die neuen Passwörter stimmen nicht überein', 'Las dos contraseñas nuevas no coinciden', 'Les deux nouveaux mots de passe ne correspondent pas', '새 비밀번호가 서로 다릅니다', 'As duas palavras-passe novas não coincidem', '新しいパスワードが一致しません'),
    'ui.new_password_same' => $t('New password cannot be the same as the current one', '新密码不能与当前密码相同', 'Neues Passwort darf nicht dem aktuellen gleichen', 'La nueva no puede ser igual a la actual', 'Le nouveau ne peut pas être identique à l’actuel', '새 비밀번호는 현재와 같을 수 없습니다', 'A nova não pode ser igual à atual', '新しいパスワードは現在と同じにできません'),
    'ui.user_missing' => $t('User not found', '用户不存在', 'Benutzer nicht gefunden', 'Usuario no encontrado', 'Utilisateur introuvable', '사용자가 없습니다', 'Utilizador não encontrado', 'ユーザーがいません'),
    'ui.current_password_wrong' => $t('Current password is wrong', '当前密码错误', 'Aktuelles Passwort falsch', 'La contraseña actual es incorrecta', 'Mot de passe actuel incorrect', '현재 비밀번호가 틀렸습니다', 'A palavra-passe atual está errada', '現在のパスワードが違います'),
    'ui.change_fail' => $t('Could not change', '修改失败', 'Änderung fehlgeschlagen', 'No se pudo cambiar', 'Modification impossible', '바꾸지 못했습니다', 'Não deu para alterar', '変更できませんでした'),
    'ui.change_ok' => $t('Changed', '修改成功', 'Geändert', 'Cambiado', 'Modifié', '바꿨습니다', 'Alterado', '変更しました'),
    'ui.safety_k_password' => $t('Site password decode', '本站密码解密', 'Site-Passwort-Decode', 'Decodificar contraseña del sitio', 'Décodage mot de passe du site', '이 사이트 비밀번호 복호', 'Descodificar palavra-passe do sítio', '本サイトのパスワード復号'),
    'ui.safety_k_encrypt' => $t('Site encrypt/decrypt', '本站加解密', 'Site-Ver-/Entschlüsselung', 'Cifrado/descifrado del sitio', 'Chiffrement/déchiffrement du site', '이 사이트 암복호', 'Cifrar/decifrar do sítio', '本サイトの暗号化/復号'),
    'ui.safety_k_rate' => $t('Site rate limit uses a Redis script, not PHP eval', '本站限流用 Redis 脚本，不是 PHP eval', 'Site-Rate-Limit nutzt ein Redis-Skript, nicht PHP-eval', 'El límite de este sitio usa un script Redis, no eval de PHP', 'La limite du site utilise un script Redis, pas eval PHP', '이 사이트 제한은 Redis 스크립트이며 PHP eval이 아닙니다', 'O limite deste sítio usa um script Redis, não eval PHP', '本サイトの制限は Redis スクリプトであり PHP eval ではありません'),
    'ui.safety_k_dump' => $t('Site backup calls mysqldump', '本站备份调 mysqldump', 'Site-Backup ruft mysqldump auf', 'La copia del sitio llama a mysqldump', 'La sauvegarde du site appelle mysqldump', '이 사이트 백업이 mysqldump를 호출', 'A cópia deste sítio chama mysqldump', '本サイトのバックアップは mysqldump を呼びます'),
    'ui.safety_k_alipay' => $t('Alipay signature decode', '支付宝验签解码', 'Alipay-Signatur-Decode', 'Decodificar firma Alipay', 'Décodage signature Alipay', '알리페이 서명 복호', 'Descodificar assinatura Alipay', 'Alipay 署名の復号'),
    'ui.sched_need_name' => $t('Enter a task name', '请输入任务名称', 'Aufgabenname eingeben', 'Escriba un nombre de tarea', 'Saisissez un nom de tâche', '작업 이름을 입력하세요', 'Introduza um nome de tarefa', 'タスク名を入力してください'),
    'ui.sched_bad_type' => $t('Task type is invalid', '任务类型不正确', 'Aufgabentyp ungültig', 'El tipo de tarea no es válido', 'Type de tâche invalide', '작업 유형이 올바르지 않습니다', 'O tipo de tarefa é inválido', 'タスクの種類が正しくありません'),
    'ui.sched_need_cmd' => $t('Enter what to run', '请输入执行内容', 'Ausführung eingeben', 'Escriba qué ejecutar', 'Saisissez quoi exécuter', '실행 내용을 입력하세요', 'Introduza o que executar', '実行内容を入力してください'),
    'ui.sched_cmd_long' => $t('What to run is too long', '执行内容过长', 'Ausführung zu lang', 'Lo que ejecutar es demasiado largo', 'Ce qu’il faut exécuter est trop long', '실행 내용이 너무 깁니다', 'O que executar é demasiado longo', '実行内容が長すぎます'),
    'ui.sched_name_taken' => $t('That task name already exists', '任务名称已存在', 'Dieser Aufgabenname existiert schon', 'Ese nombre de tarea ya existe', 'Ce nom de tâche existe déjà', '그 작업 이름은 이미 있습니다', 'Esse nome de tarefa já existe', 'そのタスク名は既にあります'),
    'ui.sched_bad_cron' => $t('Cron expression is invalid', 'cron表达式格式错误', 'Cron-Ausdruck ungültig', 'La expresión cron no es válida', 'Expression cron invalide', 'cron 식이 올바르지 않습니다', 'A expressão cron é inválida', 'cron 式の形式が違います'),
    'ui.sched_bad_param' => $t('Invalid parameter', '参数错误', 'Ungültiger Parameter', 'Parámetro no válido', 'Paramètre invalide', '인자가 올바르지 않습니다', 'Parâmetro inválido', 'パラメータが違います'),
    'ui.sched_missing' => $t('Task not found', '任务不存在', 'Aufgabe nicht gefunden', 'Tarea no encontrada', 'Tâche introuvable', '작업이 없습니다', 'Tarefa não encontrada', 'タスクがありません'),
    'ui.sched_running' => $t('The task is already running', '任务正在执行中', 'Die Aufgabe läuft bereits', 'La tarea ya se está ejecutando', 'La tâche est déjà en cours', '작업이 이미 실행 중입니다', 'A tarefa já está a correr', 'タスクは実行中です'),
    'ui.sched_need_http' => $t('URL must start with http:// or https://', '网址要以 http:// 或 https:// 开头', 'URL muss mit http:// oder https:// beginnen', 'La URL debe empezar por http:// o https://', 'L’URL doit commencer par http:// ou https://', '주소는 http:// 또는 https:// 로 시작해야 합니다', 'O URL tem de começar por http:// ou https://', 'URL は http:// または https:// で始めてください'),
    'ui.sched_need_shell' => $t('Enter the command to run on the server', '请填写要在服务器上跑的命令', 'Befehl für den Server eingeben', 'Escriba el comando a ejecutar en el servidor', 'Saisissez la commande à lancer sur le serveur', '서버에서 실행할 명령을 입력하세요', 'Introduza o comando a correr no servidor', 'サーバーで実行するコマンドを入力してください'),
    'ui.sched_on_msg' => $t('On. It will run when due.', '已开着，到点会跑', 'An. Läuft zum Termin.', 'Encendida. Correrá a su hora.', 'Activée. Elle tournera à l’heure.', '켜짐. 시간이 되면 실행됩니다.', 'Ligada. Corre quando for a hora.', 'オンです。時刻が来ると実行します。'),
    'ui.sched_off_msg' => $t('Off. It will not run when due.', '已停，到点不跑', 'Aus. Läuft nicht zum Termin.', 'Apagada. No correrá a su hora.', 'Arrêtée. Elle ne tournera pas à l’heure.', '꺼짐. 시간이 되어도 실행하지 않습니다.', 'Desligada. Não corre quando for a hora.', 'オフです。時刻が来ても実行しません。'),
    'ui.sched_status_fail' => $t('Could not change status', '没能改状态', 'Statusänderung fehlgeschlagen', 'No se pudo cambiar el estado', 'Impossible de changer l’état', '상태를 바꾸지 못했습니다', 'Não deu para alterar o estado', '状態を変えられませんでした'),
    'ui.sched_pick_cmd' => $t('Pick a site command to run', '请选择要跑的本站命令', 'Eine Site-Befehl wählen', 'Elija un comando del sitio', 'Choisissez une commande du site', '실행할 이 사이트 명령을 고르세요', 'Escolha um comando deste sítio', '実行する本サイトコマンドを選んでください'),
    'ui.sched_cmd_denied' => $t('That command cannot run as a scheduled task', '这条命令不能当定时任务跑', 'Dieser Befehl darf nicht als Zeitaufgabe laufen', 'Ese comando no puede correr como tarea programada', 'Cette commande ne peut pas tourner en tâche planifiée', '그 명령은 예약 작업으로 실행할 수 없습니다', 'Esse comando não pode correr como tarefa agendada', 'そのコマンドは定時タスクで実行できません'),
    'ui.sched_cmd_site_only' => $t('Only site commands, or jobs declared in an enabled plugin.json', '只接受本站命令，或已启用插件在 plugin.json 里声明的任务', 'Nur Site-Befehle oder Jobs aus einer aktivierten plugin.json', 'Solo comandos del sitio, o tareas declaradas en un plugin.json activo', 'Seulement commandes du site, ou jobs déclarés dans un plugin.json actif', '이 사이트 명령 또는 사용 중인 plugin.json 에 선언된 작업만', 'Só comandos deste sítio, ou tarefas declaradas num plugin.json ativo', '本サイトコマンド、または有効な plugin.json のタスクのみ'),
    'ui.sched_plugin_args' => $t('Plugin jobs must be written as plugin:run plugin-id job-id', '插件任务要写成 plugin:run 插件id 任务id', 'Plugin-Jobs als plugin:run Plugin-ID Job-ID schreiben', 'Las tareas de plugin se escriben plugin:run id-plugin id-tarea', 'Les jobs plugin s’écrivent plugin:run id-plugin id-tâche', '플러그인 작업은 plugin:run 플러그인id 작업id 로 쓰세요', 'Tarefas de plugin escrevem-se plugin:run id-plugin id-tarefa', 'プラグインタスクは plugin:run プラグインid タスクid と書いてください'),
    'ui.sched_plugin_missing' => $t('No such plugin job, or the plugin is off', '没有这条插件任务，或插件没启用', 'Kein solcher Plugin-Job, oder Plugin aus', 'No hay esa tarea de plugin, o el plugin está apagado', 'Pas ce job plugin, ou plugin désactivé', '그런 플러그인 작업이 없거나 플러그인이 꺼져 있습니다', 'Não há essa tarefa de plugin, ou o plugin está desligado', 'そのプラグインタスクがないか、プラグインがオフです'),
    'ui.gender' => $t('Gender', '性别', 'Geschlecht', 'Sexo', 'Genre', '성별', 'Género', '性別'),
    'ui.gender_unknown' => $t('Unknown', '未知', 'Unbekannt', 'Desconocido', 'Inconnu', '미상', 'Desconhecido', '不明'),
    'ui.gender_m' => $t('Male', '男', 'Männlich', 'Hombre', 'Homme', '남', 'Masculino', '男性'),
    'ui.gender_f' => $t('Female', '女', 'Weiblich', 'Mujer', 'Femme', '여', 'Feminino', '女性'),
    'ui.rewrite_local_mode' => $t('Site routes', '本站路由', 'Eigene Routen', 'Rutas del sitio', 'Routes du site', '이 사이트 라우트', 'Rotas do sítio', '本サイト経路'),
    'ui.rewrite_mac_mode' => $t('Apple style', '苹果风格', 'Apple-Stil', 'Estilo Apple', 'Style Apple', '애플 스타일', 'Estilo Apple', 'アップル風'),
    'ui.rewrite_g_vod' => $t('Videos', '片子', 'Videos', 'Vídeos', 'Vidéos', '영상', 'Vídeos', '映像'),
    'ui.rewrite_g_other' => $t('Other sections', '其它栏目', 'Andere Rubriken', 'Otras secciones', 'Autres rubriques', '기타 섹션', 'Outras secções', 'その他の欄'),
    'ui.rewrite_g_member' => $t('Members', '会员', 'Mitglieder', 'Miembros', 'Membres', '회원', 'Membros', '会員'),
    'ui.rewrite_g_seo' => $t('For search engines', '给搜索引擎', 'Für Suchmaschinen', 'Para buscadores', 'Pour les moteurs', '검색엔진용', 'Para motores de busca', '検索エンジン向け'),
    'ui.rewrite_home' => $t('Home', '首页', 'Startseite', 'Inicio', 'Accueil', '홈', 'Início', 'ホーム'),
    'ui.rewrite_type' => $t('Category', '分类', 'Kategorie', 'Categoría', 'Catégorie', '분류', 'Categoria', 'カテゴリ'),
    'ui.rewrite_detail' => $t('Detail', '详情', 'Detail', 'Detalle', 'Détail', '상세', 'Detalhe', '詳細'),
    'ui.rewrite_play' => $t('Play', '播放', 'Abspielen', 'Reproducir', 'Lecture', '재생', 'Reproduzir', '再生'),
    'ui.rewrite_down' => $t('Download', '下载', 'Download', 'Descarga', 'Téléchargement', '다운로드', 'Transferência', 'ダウンロード'),
    'ui.rewrite_player' => $t('Embedded player', '播放器内嵌', 'Eingebetteter Player', 'Reproductor incrustado', 'Lecteur intégré', '플레이어 삽입', 'Leitor embutido', 'プレイヤー埋め込み'),
    'ui.rewrite_show' => $t('Filter', '筛选', 'Filter', 'Filtro', 'Filtre', '필터', 'Filtro', '絞り込み'),
    'ui.rewrite_search' => $t('Search', '搜索', 'Suche', 'Búsqueda', 'Recherche', '검색', 'Pesquisa', '検索'),
    'ui.rewrite_latest' => $t('Latest', '最近更新', 'Zuletzt aktualisiert', 'Recientes', 'Dernières mises à jour', '최근 업데이트', 'Recentes', '最近の更新'),
    'ui.rewrite_local_path' => $t('Site path', '本站路径', 'Site-Pfad', 'Ruta del sitio', 'Chemin du site', '이 사이트 경로', 'Caminho do sítio', '本サイト経路'),
    'ui.rewrite_tag' => $t('Tag', '标签', 'Tag', 'Etiqueta', 'Tag', '태그', 'Etiqueta', 'タグ'),
    'ui.rewrite_actors' => $t('Actor list', '演员列表', 'Darstellerliste', 'Lista de actores', 'Liste d’acteurs', '배우 목록', 'Lista de atores', '俳優一覧'),
    'ui.rewrite_actor' => $t('Actor', '演员', 'Darsteller', 'Actor', 'Acteur', '배우', 'Ator', '俳優'),
    'ui.rewrite_topics' => $t('Topic list', '专题列表', 'Themenliste', 'Lista de temas', 'Liste de sujets', '특집 목록', 'Lista de tópicos', '特集一覧'),
    'ui.rewrite_topic' => $t('Topic', '专题', 'Thema', 'Tema', 'Sujet', '특집', 'Tópico', '特集'),
    'ui.rewrite_arts' => $t('Article list', '文章列表', 'Artikelliste', 'Lista de artículos', 'Liste d’articles', '기사 목록', 'Lista de artigos', '記事一覧'),
    'ui.rewrite_art' => $t('Article', '文章', 'Artikel', 'Artículo', 'Article', '기사', 'Artigo', '記事'),
    'ui.rewrite_roles' => $t('Role list', '角色列表', 'Rollenliste', 'Lista de roles', 'Liste de rôles', '역할 목록', 'Lista de papéis', '役割一覧'),
    'ui.rewrite_role' => $t('Role', '角色', 'Rolle', 'Rol', 'Rôle', '역할', 'Papel', '役割'),
    'ui.rewrite_plots' => $t('Plot list', '剧情列表', 'Handlungsliste', 'Lista de tramas', 'Liste d’intrigues', '줄거리 목록', 'Lista de enredos', 'あらすじ一覧'),
    'ui.rewrite_plot' => $t('Plot', '剧情', 'Handlung', 'Trama', 'Intrigue', '줄거리', 'Enredo', 'あらすじ'),
    'ui.rewrite_sites' => $t('Link directory list', '网址导航列表', 'Linkverzeichnis-Liste', 'Lista de directorio', 'Liste d’annuaire', '사이트 디렉터리 목록', 'Lista do diretório', 'リンク集一覧'),
    'ui.rewrite_site' => $t('Link directory', '网址导航', 'Linkverzeichnis', 'Directorio', 'Annuaire', '사이트 디렉터리', 'Diretório', 'リンク集'),
    'ui.rewrite_gbook' => $t('Guestbook', '留言', 'Gästebuch', 'Libro de visitas', 'Livre d’or', '방명록', 'Livro de visitas', '伝言板'),
    'ui.rewrite_login' => $t('Sign in', '登录', 'Anmelden', 'Entrar', 'Connexion', '로그인', 'Iniciar sessão', 'ログイン'),
    'ui.rewrite_register' => $t('Register', '注册', 'Registrieren', 'Registro', 'Inscription', '가입', 'Registar', '登録'),
    'ui.rewrite_center' => $t('Member center', '会员中心', 'Mitgliederbereich', 'Centro de miembros', 'Espace membre', '회원 센터', 'Centro de membros', '会員センター'),
    'ui.rewrite_need_login' => $t('Sign-in required', '要登录', 'Anmeldung nötig', 'Hay que entrar', 'Connexion requise', '로그인 필요', 'É preciso iniciar sessão', 'ログインが必要'),
    'ui.rewrite_sitemap' => $t('Sitemap', '站点地图', 'Sitemap', 'Mapa del sitio', 'Plan du site', '사이트맵', 'Mapa do sítio', 'サイトマップ'),
    'ui.sched_ran_ok' => $t('Finished, :d', '跑完了，:d', 'Fertig, :d', 'Terminado, :d', 'Terminé, :d', '끝났습니다, :d', 'Terminou, :d', '終わりました、:d'),
    'ui.cmd_exit' => $t('Command returned :code', '命令返回 :code', 'Befehl gab :code zurück', 'El comando devolvió :code', 'La commande a renvoyé :code', '명령이 :code 를 반환', 'O comando devolveu :code', 'コマンドは :code を返しました'),
    'ui.http_only' => $t('Only http or https URLs are accepted', '只接受 http 或 https 地址', 'Nur http- oder https-URLs', 'Solo se aceptan URL http o https', 'Seules les URL http ou https', 'http 또는 https 주소만', 'Só URLs http ou https', 'http または https の URL のみ'),
];
