<?php

/**
 * Login API toasts, cache board details, list badges.
 * Applied by tools/patch-display-i18n.php.
 */
$t = static fn (
    string $en,
    string $zh,
    string $de,
    string $es,
    string $fr,
    string $ko,
    string $pt,
    string $ja,
): array => [
    'en' => $en,
    'zh_cn' => $zh,
    'de' => $de,
    'es' => $es,
    'fr' => $fr,
    'ko' => $ko,
    'pt' => $pt,
    'ja' => $ja,
];

return [
    'auth.need_account' => $t('Enter username and password', '请填写账号和密码', 'Benutzername und Passwort eingeben', 'Escriba usuario y contraseña', 'Saisissez identifiant et mot de passe', '계정과 비밀번호를 입력하세요', 'Introduza conta e palavra-passe', 'アカウントとパスワードを入力してください'),
    'auth.locked' => $t('Too many failed sign-ins. Try again in 15 minutes.', '登录失败次数过多，请 15 分钟后再试', 'Zu viele Fehlversuche. In 15 Minuten erneut versuchen.', 'Demasiados fallos. Inténtelo en 15 minutos.', 'Trop d’échecs. Réessayez dans 15 minutes.', '로그인 실패가 너무 많습니다. 15분 후 다시 시도하세요.', 'Demasiadas falhas. Tente daqui a 15 minutos.', 'ログイン失敗が多すぎます。15分後に再試行してください。'),
    'auth.need_captcha' => $t('Enter the captcha', '请输入验证码', 'Captcha eingeben', 'Escriba el captcha', 'Saisissez le captcha', '인증코드를 입력하세요', 'Introduza o captcha', '認証コードを入力してください'),
    'auth.captcha_wrong' => $t('Captcha is wrong', '验证码错误', 'Captcha falsch', 'Captcha incorrecto', 'Captcha incorrect', '인증코드가 틀렸습니다', 'Captcha errado', '認証コードが違います'),
    'auth.no_admin' => $t('No admin yet. Reinstall.', '还没有管理员，请重新安装', 'Noch kein Admin. Neu installieren.', 'Aún no hay admin. Reinstale.', 'Pas encore d’admin. Réinstallez.', '관리자가 없습니다. 다시 설치하세요.', 'Ainda não há admin. Reinstale.', '管理者がいません。再インストールしてください。'),
    'auth.bad_pass' => $t('Wrong username or password', '账号或者密码错误', 'Benutzername oder Passwort falsch', 'Usuario o contraseña incorrectos', 'Identifiant ou mot de passe incorrect', '계정 또는 비밀번호가 틀렸습니다', 'Conta ou palavra-passe errada', 'アカウントまたはパスワードが違います'),
    'auth.disabled' => $t('This account is disabled', '账号已停用', 'Dieses Konto ist deaktiviert', 'Esta cuenta está desactivada', 'Ce compte est désactivé', '이 계정은 정지되었습니다', 'Esta conta está desativada', 'このアカウントは停止されています'),
    'auth.ok' => $t('Signed in', '登录成功', 'Angemeldet', 'Sesión iniciada', 'Connecté', '로그인됨', 'Sessão iniciada', 'ログインしました'),
    'ui.ep_n' => $t('Episode :n', '第:n集', 'Folge :n', 'Episodio :n', 'Épisode :n', ':n화', 'Episódio :n', '第:n話'),
    'ui.ep_missing' => $t('No episode number', '未写集数', 'Keine Folgennummer', 'Sin número de episodio', 'Pas de numéro d’épisode', '회차 없음', 'Sem número de episódio', '話数が未記入'),
    'ui.title_missing' => $t('No title', '未写标题', 'Kein Titel', 'Sin título', 'Pas de titre', '제목 없음', 'Sem título', 'タイトル未記入'),
    'ui.parse_prefix' => $t('Prefix', '前缀', 'Präfix', 'Prefijo', 'Préfixe', '접두사', 'Prefixo', '接頭辞'),
    'ui.parse_raw' => $t('As-is', '原样', 'Unverändert', 'Tal cual', 'Tel quel', '그대로', 'Tal como está', 'そのまま'),
    'ui.bak_kind_sqlite' => $t('SQLite file', 'SQLite 文件', 'SQLite-Datei', 'Archivo SQLite', 'Fichier SQLite', 'SQLite 파일', 'Ficheiro SQLite', 'SQLite ファイル'),
    'ui.bak_kind_sql' => $t('SQL text', 'SQL 文本', 'SQL-Text', 'Texto SQL', 'Texte SQL', 'SQL 텍스트', 'Texto SQL', 'SQL テキスト'),
    'ui.cache_unknown_kind' => $t('Unknown cache item', '不知道要清哪一项', 'Unbekannter Cache-Punkt', 'Elemento de caché desconocido', 'Élément de cache inconnu', '어떤 항목인지 모릅니다', 'Item de cache desconhecido', 'どの項目か不明です'),
    'ui.cache_run_fail' => $t('Could not run', '没能执行', 'Ausführung fehlgeschlagen', 'No se pudo ejecutar', 'Impossible d’exécuter', '실행하지 못했습니다', 'Não deu para executar', '実行できませんでした'),
    'ui.cache_cmd_denied' => $t('That command is not allowed', '不允许执行该命令', 'Dieser Befehl ist nicht erlaubt', 'Ese comando no está permitido', 'Cette commande n’est pas autorisée', '그 명령은 허용되지 않습니다', 'Esse comando não é permitido', 'そのコマンドは許可されていません'),
    'ui.cache_msg_data' => $t('Data cache cleared. Settings and queries will recompute.', '已清掉数据缓存。设置和查询会重新算。', 'Daten-Cache geleert. Einstellungen und Abfragen werden neu berechnet.', 'Caché de datos vaciada. Ajustes y consultas se recálculan.', 'Cache données vidée. Réglages et requêtes seront recalculés.', '데이터 캐시를 지웠습니다. 설정과 조회는 다시 계산됩니다.', 'Cache de dados limpa. Definições e consultas voltam a calcular.', 'データキャッシュを消しました。設定と照会は再計算されます。'),
    'ui.cache_msg_views' => $t('Compiled templates cleared. Pages will recompile on next open.', '已清掉编译模板。下次打开页面会重新编译。', 'Kompilierte Vorlagen geleert. Nächste Seite kompiliert neu.', 'Plantillas compiladas vaciadas. La próxima página recompila.', 'Modèles compilés vidés. La prochaine page recompile.', '컴파일된 템플릿을 지웠습니다. 다음 페이지에서 다시 컴파일합니다.', 'Modelos compilados limpos. A próxima página recompila.', 'コンパイル済みテンプレートを消しました。次のページで再コンパイルします。'),
    'ui.cache_msg_config' => $t('Unpacked config and routes. Edited files will be read again.', '已解开配置和路由打包。改过的配置会重新读。', 'Config und Routen entpackt. Geänderte Dateien werden neu gelesen.', 'Config y rutas desempaquetadas. Los archivos editados se leen otra vez.', 'Config et routes dépaquetées. Les fichiers édités seront relus.', '설정과 라우트 묶음을 풀었습니다. 고친 파일은 다시 읽습니다.', 'Config e rotas desempacotadas. Ficheiros editados voltam a ser lidos.', '設定とルートのパックを解きました。変更ファイルは再読込されます。'),
    'ui.cache_msg_all' => $t('Everything cleared. The front may be slower for a bit.', '已全部清掉。前台会稍慢一会儿。', 'Alles geleert. Das Frontend kann kurz langsamer sein.', 'Todo vaciado. El frente puede ir más lento un rato.', 'Tout vidé. Le front peut être un peu plus lent.', '전부 지웠습니다. 프론트가 잠시 느려질 수 있습니다.', 'Tudo limpo. A frente pode ficar mais lenta um pouco.', 'すべて消しました。フロントがしばらく遅くなることがあります。'),
    'ui.cache_msg_pack_config' => $t('Config packed. File edits will not apply until you unpack.', '已打包配置。之后改配置文件不会马上生效，要先解开。', 'Config gepackt. Dateiänderungen greifen erst nach dem Entpacken.', 'Config empaquetada. Los cambios de archivo no aplican hasta desempaquetar.', 'Config empaquetée. Les edits fichier n’appliquent qu’après dépaquetage.', '설정을 묶었습니다. 파일 수정은 풀기 전까지 적용되지 않습니다.', 'Config empacotada. Edições de ficheiro só após desempacotar.', '設定をパックしました。ファイル変更は解くまで効きません。'),
    'ui.cache_msg_pack_routes' => $t('Routes packed. After editing route files, unpack then pack again.', '已打包路由。改路由文件后要先解开再打包。', 'Routen gepackt. Nach Dateiänderungen zuerst entpacken, dann neu packen.', 'Rutas empaquetadas. Tras editar, desempaquete y vuelva a empaquetar.', 'Routes empaquetées. Après édition, dépaquetez puis rempaquetez.', '라우트를 묶었습니다. 파일 수정 후 풀었다가 다시 묶으세요.', 'Rotas empacotadas. Depois de editar, desempacote e volte a empacotar.', 'ルートをパックしました。ファイル変更後は解いてから再パック。'),
    'ui.cache_msg_pack_views' => $t('Templates precompiled. Clear them before compiling again after edits.', '已预编译模板。改模板后要先清掉再预编译。', 'Vorlagen vorkompiliert. Nach Änderungen zuerst leeren, dann neu kompilieren.', 'Plantillas precompiladas. Tras editar, vacíe y vuelva a precompilar.', 'Modèles précompilés. Après édition, videz puis recompilez.', '템플릿을 미리 컴파일했습니다. 수정 후 지우고 다시 컴파일하세요.', 'Modelos pré-compilados. Depois de editar, limpe e volte a compilar.', 'テンプレートを事前コンパイルしました。変更後は消してから再コンパイル。'),
    'ui.cache_driver_file' => $t('File', '文件', 'Datei', 'Archivo', 'Fichier', '파일', 'Ficheiro', 'ファイル'),
    'ui.cache_driver_file_h' => $t('Cache on disk. Fine for one machine.', '缓存在服务器磁盘，单机够用', 'Cache auf der Platte. Reicht für eine Maschine.', 'Caché en disco. Vale para una máquina.', 'Cache sur disque. Suffit pour une machine.', '디스크 캐시. 한 대면 충분합니다.', 'Cache em disco. Chega para uma máquina.', 'ディスク上のキャッシュ。1台なら足りる。'),
    'ui.cache_driver_redis_h' => $t('Cache in Redis. Can be shared across machines.', '缓存在 Redis，多机可共用', 'Cache in Redis. Über Maschinen teilbar.', 'Caché en Redis. Se puede compartir entre máquinas.', 'Cache dans Redis. Partageable entre machines.', 'Redis 캐시. 여러 대가 공유할 수 있습니다.', 'Cache no Redis. Partilhável entre máquinas.', 'Redis 上のキャッシュ。複数台で共有可。'),
    'ui.cache_driver_db' => $t('Database', '数据库', 'Datenbank', 'Base de datos', 'Base de données', '데이터베이스', 'Base de dados', 'データベース'),
    'ui.cache_driver_db_h' => $t('Cache in a table.', '缓存在数据表里', 'Cache in einer Tabelle.', 'Caché en una tabla.', 'Cache dans une table.', '테이블에 캐시합니다.', 'Cache numa tabela.', 'テーブルにキャッシュします。'),
    'ui.cache_driver_mem' => $t('Memory', '内存', 'Speicher', 'Memoria', 'Mémoire', '메모리', 'Memória', 'メモリ'),
    'ui.cache_driver_mem_h' => $t('This request only. Gone when it ends.', '只在这次请求里，关掉就没了', 'Nur diese Anfrage. Weg, wenn sie endet.', 'Solo esta petición. Se pierde al terminar.', 'Cette requête seulement. Disparu à la fin.', '이번 요청만. 끝나면 사라집니다.', 'Só este pedido. Desaparece ao terminar.', 'このリクエストのみ。終わると消えます。'),
    'ui.cache_driver_mc_h' => $t('Cache in Memcached.', '缓存在 Memcached', 'Cache in Memcached.', 'Caché en Memcached.', 'Cache dans Memcached.', 'Memcached에 캐시합니다.', 'Cache no Memcached.', 'Memcached にキャッシュします。'),
    'ui.cache_detail_db' => $t('Database', '数据库', 'Datenbank', 'Base de datos', 'Base de données', '데이터베이스', 'Base de dados', 'データベース'),
    'ui.cache_detail_db_n' => $t('Database · :n rows', '数据库 · :n 条', 'Datenbank · :n Zeilen', 'Base · :n filas', 'Base · :n lignes', '데이터베이스 · :n건', 'Base · :n linhas', 'データベース · :n 件'),
    'ui.cache_detail_file_empty' => $t('File · empty', '文件 · 空', 'Datei · leer', 'Archivo · vacío', 'Fichier · vide', '파일 · 비움', 'Ficheiro · vazio', 'ファイル · 空'),
    'ui.cache_detail_file_n' => $t('File · :size · :n files', '文件 · :size · :n 个文件', 'Datei · :size · :n Dateien', 'Archivo · :size · :n archivos', 'Fichier · :size · :n fichiers', '파일 · :size · :n개', 'Ficheiro · :size · :n ficheiros', 'ファイル · :size · :n 個'),
    'ui.cache_detail_array' => $t('Memory, not persistent', '内存，不持久', 'Speicher, nicht persistent', 'Memoria, no persistente', 'Mémoire, non persistante', '메모리, 유지되지 않음', 'Memória, não persistente', 'メモリ、非永続'),
    'ui.cache_detail_redis' => $t('In Redis; row count is not shown here', '在 Redis 里，条数不在这里数', 'In Redis; Zeilenzahl nicht hier', 'En Redis; el recuento no se muestra aquí', 'Dans Redis ; le nombre n’est pas ici', 'Redis에 있음. 건수는 여기서 안 셉니다', 'No Redis; a contagem não aparece aqui', 'Redis 内。件数はここでは数えません'),
    'ui.cache_views_empty' => $t('No compiled files yet', '还没有编译文件', 'Noch keine kompilierten Dateien', 'Aún no hay archivos compilados', 'Pas encore de fichiers compilés', '컴파일된 파일이 없습니다', 'Ainda não há ficheiros compilados', 'コンパイル済みファイルはまだありません'),
    'ui.cache_views_n' => $t(':n compiled', '已编译 :n 个', ':n kompiliert', ':n compilados', ':n compilés', ':n개 컴파일됨', ':n compilados', ':n 個コンパイル済み'),
    'ui.cache_views_n_size' => $t(':n compiled · :size', '已编译 :n 个 · :size', ':n kompiliert · :size', ':n compilados · :size', ':n compilés · :size', ':n개 컴파일 · :size', ':n compilados · :size', ':n 個コンパイル · :size'),
    'ui.cache_cfg_packed' => $t('Config packed', '配置已打包', 'Config gepackt', 'Config empaquetada', 'Config empaquetée', '설정 묶음', 'Config empacotada', '設定パック済み'),
    'ui.cache_cfg_fresh' => $t('Config read fresh each time', '配置每次读最新', 'Config jedes Mal neu gelesen', 'Config se lee cada vez', 'Config relue à chaque fois', '설정은 매번 최신을 읽음', 'Config lida de novo cada vez', '設定は毎回最新を読む'),
    'ui.cache_rt_packed' => $t('Routes packed', '路由已打包', 'Routen gepackt', 'Rutas empaquetadas', 'Routes empaquetées', '라우트 묶음', 'Rotas empacotadas', 'ルートパック済み'),
    'ui.cache_rt_fresh' => $t('Routes read fresh each time', '路由每次读最新', 'Routen jedes Mal neu gelesen', 'Rutas se leen cada vez', 'Routes relues à chaque fois', '라우트는 매번 최신을 읽음', 'Rotas lidas de novo cada vez', 'ルートは毎回最新を読む'),
    'ui.cache_ev_packed' => $t('Events packed', '事件已打包', 'Events gepackt', 'Eventos empaquetados', 'Events empaquetés', '이벤트 묶음', 'Eventos empacotados', 'イベントパック済み'),
    'ui.cache_empty_size' => $t('empty', '空', 'leer', 'vacío', 'vide', '비움', 'vazio', '空'),
    'ui.cache_about' => $t('~ :size', '约 :size', 'ca. :size', 'aprox. :size', 'env. :size', '약 :size', 'cerca de :size', '約 :size'),
];
