<?php

/**
 * Template picker labels, search-push toasts, module save fails.
 * Applied by tools/patch-display-i18n.php.
 */
$t = static fn (
    string $en,
    string $zh,
    string $de,
    string $es,
    string $fr,
    string $ko,
    string $pt,
    string $ja,
): array => [
    'en' => $en,
    'zh_cn' => $zh,
    'de' => $de,
    'es' => $es,
    'fr' => $fr,
    'ko' => $ko,
    'pt' => $pt,
    'ja' => $ja,
];

return [
    'ui.tpl_g_layout' => $t('Home & layout', '首页与布局', 'Start & Layout', 'Inicio y diseño', 'Accueil et mise en page', '홈과 레이아웃', 'Início e esquema', 'ホームとレイアウト'),
    'ui.tpl_g_vod' => $t('Videos', '影片', 'Videos', 'Vídeos', 'Vidéos', '영상', 'Vídeos', '映像'),
    'ui.tpl_g_partials' => $t('Shared blocks', '公共块', 'Gemeinsame Blöcke', 'Bloques comunes', 'Blocs communs', '공용 블록', 'Blocos comuns', '共通ブロック'),
    'ui.tpl_g_other' => $t('Other', '其他', 'Sonstiges', 'Otros', 'Autres', '기타', 'Outros', 'その他'),
    'ui.tpl_f_chrome' => $t('Site chrome', '整站头尾', 'Kopf und Fuß', 'Cabecera y pie', 'En-tête et pied', '전체 머리·바닥', 'Cabeçalho e rodapé', 'サイトの頭と末'),
    'ui.tpl_f_card' => $t('Video card', '影片卡片', 'Videokarte', 'Tarjeta de vídeo', 'Carte vidéo', '영상 카드', 'Cartão de vídeo', '映像カード'),
    'ui.tpl_f_filters' => $t('Filter bar', '筛选条', 'Filterleiste', 'Barra de filtros', 'Barre de filtres', '필터 바', 'Barra de filtros', '絞り込みバー'),
    'ui.tpl_f_pager' => $t('Pager', '分页', 'Pager', 'Paginación', 'Pagination', '페이지', 'Paginação', 'ページ送り'),
    'ui.tpl_f_type_list' => $t('Category list', '分类列表', 'Kategorieliste', 'Lista de categorías', 'Liste de catégories', '분류 목록', 'Lista de categorias', 'カテゴリ一覧'),
    'ui.tpl_f_show' => $t('Filter results', '筛选结果', 'Filterergebnis', 'Resultados del filtro', 'Résultats du filtre', '필터 결과', 'Resultados do filtro', '絞り込み結果'),
    'ui.tpl_f_vod_detail' => $t('Video detail', '影片详情', 'Videodetail', 'Detalle de vídeo', 'Détail vidéo', '영상 상세', 'Detalhe do vídeo', '映像詳細'),
    'ui.tpl_f_play' => $t('Play page', '播放页', 'Wiedergabeseite', 'Página de reproducción', 'Page de lecture', '재생 페이지', 'Página de reprodução', '再生ページ'),
    'ui.tpl_f_down' => $t('Download page', '下载页', 'Downloadseite', 'Página de descarga', 'Page de téléchargement', '다운로드 페이지', 'Página de transferência', 'ダウンロードページ'),
    'ui.tpl_f_player' => $t('Player', '播放器', 'Player', 'Reproductor', 'Lecteur', '플레이어', 'Leitor', 'プレイヤー'),
    'ui.tpl_f_tag' => $t('Tag page', '标签页', 'Tag-Seite', 'Página de etiqueta', 'Page de tag', '태그 페이지', 'Página de etiqueta', 'タグページ'),
    'ui.tpl_f_topic' => $t('Topic detail', '专题详情', 'Themendetail', 'Detalle de tema', 'Détail du sujet', '특집 상세', 'Detalhe do tópico', '特集詳細'),
    'ui.tpl_f_actor' => $t('Actor detail', '演员详情', 'Darstellerdetail', 'Detalle de actor', 'Détail acteur', '배우 상세', 'Detalhe do ator', '俳優詳細'),
    'ui.tpl_f_art' => $t('Article detail', '文章详情', 'Artikeldetail', 'Detalle de artículo', 'Détail d’article', '기사 상세', 'Detalhe do artigo', '記事詳細'),
    'ui.tpl_f_arts' => $t('Article list', '文章列表', 'Artikelliste', 'Lista de artículos', 'Liste d’articles', '기사 목록', 'Lista de artigos', '記事一覧'),
    'ui.tpl_f_gbook' => $t('Guestbook', '留言本', 'Gästebuch', 'Libro de visitas', 'Livre d’or', '방명록', 'Livro de visitas', '伝言板'),
    'ui.tpl_f_role' => $t('Role detail', '角色详情', 'Rollendetail', 'Detalle de rol', 'Détail de rôle', '역할 상세', 'Detalhe do papel', '役割詳細'),
    'ui.tpl_f_roles' => $t('Role list', '角色列表', 'Rollenliste', 'Lista de roles', 'Liste de rôles', '역할 목록', 'Lista de papéis', '役割一覧'),
    'ui.tpl_f_site' => $t('Link detail', '网址详情', 'Linkdetail', 'Detalle de enlace', 'Détail de lien', '주소 상세', 'Detalhe do endereço', 'URL 詳細'),
    'ui.tpl_f_sites' => $t('Link list', '网址列表', 'Linkliste', 'Lista de enlaces', 'Liste de liens', '주소 목록', 'Lista de endereços', 'URL 一覧'),
    'ui.tpl_f_my_videos' => $t('My videos', '我的影片', 'Meine Videos', 'Mis vídeos', 'Mes vidéos', '내 영상', 'Os meus vídeos', '自分の映像'),
    'ui.tpl_f_inbox' => $t('Inbox', '站内信', 'Posteingang', 'Bandeja', 'Boîte de réception', '쪽지함', 'Caixa de entrada', '受信箱'),
    'ui.tpl_bad_path' => $t('Invalid path', '非法路径', 'Ungültiger Pfad', 'Ruta no válida', 'Chemin invalide', '잘못된 경로', 'Caminho inválido', '不正な経路'),
    'ui.tpl_blade_only' => $t('Only Blade templates can be edited', '只能编辑 blade 模板', 'Nur Blade-Vorlagen dürfen bearbeitet werden', 'Solo se pueden editar plantillas Blade', 'Seuls les modèles Blade sont éditables', 'Blade 템플릿만 고칠 수 있습니다', 'Só modelos Blade podem ser editados', 'Blade テンプレートだけ編集できます'),
    'ui.tpl_saved_backup' => $t('Saved, and a backup was made', '已保存，并做了备份', 'Gespeichert, Backup angelegt', 'Guardado, y se hizo una copia', 'Enregistré, avec une sauvegarde', '저장했고 백업도 만들었습니다', 'Guardado, e fez-se uma cópia', '保存し、バックアップも作りました'),
    'ui.tpl_backed_up' => $t('Backed up', '已备份', 'Gesichert', 'Copiado', 'Sauvegardé', '백업됨', 'Copiado', 'バックアップしました'),
    'ui.tpl_no_backup' => $t('No backup', '没有备份', 'Kein Backup', 'No hay copia', 'Pas de sauvegarde', '백업이 없습니다', 'Não há cópia', 'バックアップがありません'),
    'ui.tpl_no_file_backup' => $t('No backup for this file', '没有该文件的备份', 'Kein Backup für diese Datei', 'No hay copia de este archivo', 'Pas de sauvegarde pour ce fichier', '이 파일의 백업이 없습니다', 'Não há cópia deste ficheiro', 'このファイルのバックアップがありません'),
    'ui.tpl_rolled' => $t('Restored the last backup', '已回到上次备份', 'Letztes Backup wiederhergestellt', 'Se restauró la última copia', 'Dernière sauvegarde rétablie', '지난 백업으로 돌렸습니다', 'Restaurou a última cópia', '前回のバックアップに戻しました'),
    'ui.push_baidu' => $t('Baidu', '百度', 'Baidu', 'Baidu', 'Baidu', '바이두', 'Baidu', 'Baidu'),
    'ui.push_shenma' => $t('Shenma', '神马', 'Shenma', 'Shenma', 'Shenma', '선마', 'Shenma', '神馬'),
    'ui.push_bing' => $t('Bing', '必应', 'Bing', 'Bing', 'Bing', '빙', 'Bing', 'Bing'),
    'ui.push_hint_baidu' => $t('Webmaster tools → regular submit', '站长平台 → 普通收录', 'Webmaster-Tools → normale Übermittlung', 'Herramientas webmaster → envío normal', 'Outils webmaster → envoi normal', '웹마스터 → 일반 제출', 'Ferramentas webmaster → envio normal', 'ウェブマスター → 通常送信'),
    'ui.push_hint_shenma' => $t('Shenma webmaster → data push', '神马站长 → 数据推送', 'Shenma-Webmaster → Datenpush', 'Webmaster Shenma → envío de datos', 'Webmaster Shenma → envoi de données', '선마 웹마스터 → 데이터 푸시', 'Webmaster Shenma → envio de dados', '神馬ウェブマスター → データ送信'),
    'ui.push_hint_bing' => $t('Bing Webmaster API Key', 'Bing Webmaster API Key', 'Bing Webmaster API Key', 'Bing Webmaster API Key', 'Bing Webmaster API Key', 'Bing Webmaster API Key', 'Bing Webmaster API Key', 'Bing Webmaster API Key'),
    'ui.push_need_token' => $t('No :label Token yet. Fill it before pushing.', '还没填:label的 Token，填了才能推', 'Noch kein :label-Token. Erst eintragen, dann pushen.', 'Aún no hay Token de :label. Rellénelo antes de enviar.', 'Pas encore de jeton :label. Remplissez-le avant d’envoyer.', ':label Token이 없습니다. 채운 뒤에 푸시하세요.', 'Ainda não há Token :label. Preencha antes de enviar.', ':label の Token がまだありません。入れてから推してください。'),
    'ui.push_no_videos' => $t('No published videos to push', '没有已发布的影片可推', 'Keine veröffentlichten Videos zum Push', 'No hay vídeos publicados para enviar', 'Pas de vidéos publiées à envoyer', '푸시할 공개 영상이 없습니다', 'Não há vídeos publicados para enviar', '送る公開映像がありません'),
    'ui.push_unreach' => $t(':label unreachable: :err', ':label连不上：:err', ':label nicht erreichbar: :err', ':label no conecta: :err', ':label injoignable : :err', ':label에 연결 안 됨: :err', ':label não liga: :err', ':label に繋がりません: :err'),
    'ui.push_reject' => $t(':label did not accept: :err', ':label没收下：:err', ':label hat nicht angenommen: :err', ':label no aceptó: :err', ':label n’a pas pris : :err', ':label이 받지 않음: :err', ':label não aceitou: :err', ':labelは受け取りませんでした: :err'),
    'ui.push_ok' => $t(':label accepted :n URLs', ':label收下了 :n 条', ':label hat :n URLs angenommen', ':label aceptó :n URLs', ':label a pris :n URL', ':label이 :n건을 받음', ':label aceitou :n URLs', ':labelは :n 件を受け取りました'),
    'ui.push_ok_remain' => $t(':label accepted :n URLs, :remain quota left', ':label收下了 :n 条，额度还剩 :remain', ':label hat :n URLs angenommen, :remain Kontingent übrig', ':label aceptó :n URLs, quedan :remain', ':label a pris :n URL, quota restant :remain', ':label이 :n건을 받음, 한도 :remain 남음', ':label aceitou :n URLs, restam :remain', ':labelは :n 件を受け取り、枠は :remain 残'),
    'ui.push_map_ok' => $t('Wrote public/:files', '已生成 public/:files', 'public/:files geschrieben', 'Se escribió public/:files', 'Écrit public/:files', 'public/:files 를 썼습니다', 'Escreveu public/:files', 'public/:files を書きました'),
    'ui.ro_collect_logs' => $t('Collect logs are written by collect jobs. They cannot be edited by hand.', '采集日志由采集任务写入，不能手工改。', 'Sammelprotokolle schreibt der Sammeljob. Nicht von Hand ändern.', 'Los registros de recolección los escribe la tarea. No se editan a mano.', 'Les journaux de collecte sont écrits par la tâche. Pas à la main.', '수집 로그는 수집 작업이 씁니다. 손으로 고칠 수 없습니다.', 'Os registos de recolha são escritos pela tarefa. Não se editam à mão.', '収集ログは収集タスクが書きます。手では直せません。'),
    'ui.ro_collect_temps' => $t('Pending rows come from collect. Use Transfer to enter the library; do not edit fields here.', '待审记录由采集写入。要进片库请点转入，不要在这里改字段。', 'Wartende Zeilen kommen vom Sammeln. Zum Katalog überführen, hier keine Felder ändern.', 'Las filas pendientes vienen de la recolección. Use Transferir; no edite campos aquí.', 'Les lignes en attente viennent de la collecte. Transférez-les ; n’éditez pas ici.', '대기 기록은 수집이 씁니다. 라이브러리로 넘기려면 전입을 누르고, 여기서 필드를 고치지 마세요.', 'As linhas pendentes vêm da recolha. Use Transferir; não edite campos aqui.', '審査待ちは収集が書きます。庫に入れるなら転入を押し、ここで欄を直さないでください。'),
    'ui.ro_guestbooks' => $t('Guestbook posts come from the front. Admin only replies and reviews.', '留言由前台提交。后台只回复和审核。', 'Gästebucheinträge kommen vom Frontend. Admin antwortet und prüft nur.', 'Los mensajes del libro vienen del frente. El admin solo responde y revisa.', 'Les messages du livre d’or viennent du front. L’admin répond et relit seulement.', '방명록은 프론트가 올립니다. 관리자는 답과 심사만 합니다.', 'As mensagens do livro vêm da frente. O admin só responde e revê.', '伝言はフロントから。管理は返信と審査だけ。'),
    'ui.ro_playfails' => $t('Play failures are reported from the play page. Admin only handles them and takes lines offline.', '播放失败由前台播放页上报。后台只处理和下线线路。', 'Wiedergabefehler kommen von der Abspielseite. Admin bearbeitet und nimmt Leitungen offline.', 'Los fallos de reproducción los informa la página de play. El admin solo trata y da de baja líneas.', 'Les échecs de lecture viennent de la page play. L’admin traite et met les lignes hors ligne.', '재생 실패는 재생 페이지가 올립니다. 관리는 처리하고 회선을 내리기만 합니다.', 'As falhas de reprodução vêm da página de play. O admin só trata e desliga linhas.', '再生失敗は再生ページが報告。管理は処理と回線のオフだけ。'),
    'ui.ro_favorites' => $t('Favorites are marked by members on the video page. Admin only views and deletes.', '收藏由会员在影片页点出来。后台只查看和删除。', 'Favoriten setzen Mitglieder auf der Videoseite. Admin sieht und löscht nur.', 'Los favoritos los marcan los miembros en el vídeo. El admin solo ve y borra.', 'Les favoris sont marqués par les membres. L’admin voit et supprime seulement.', '즐겨찾기는 회원이 영상 페이지에서 누릅니다. 관리는 보기와 삭제만.', 'Os favoritos são marcados pelos membros. O admin só vê e apaga.', 'お気に入りは会員が映像ページで付けます。管理は閲覧と削除だけ。'),
    'ui.ro_manga_favors' => $t('Bookshelf items are marked by members on manga pages. Admin only views and cancels.', '书架由会员在漫画页点出来。后台只查看和取消。', 'Das Bücherregal setzen Mitglieder auf der Manga-Seite. Admin sieht und hebt nur auf.', 'La estantería la marcan los miembros en el manga. El admin solo ve y cancela.', 'L’étagère est marquée par les membres. L’admin voit et annule seulement.', '책장은 회원이 만화 페이지에서 누릅니다. 관리는 보기와 취소만.', 'A estante é marcada pelos membros. O admin só vê e cancela.', '本棚は会員が漫画ページで付けます。管理は閲覧と取消だけ。'),
    'ui.ro_task_logs' => $t('Task records are created when the front completes them. They cannot be added or edited by hand.', '任务记录由前台完成产生，不能手添或改。', 'Aufgabenprotokolle entstehen vorn. Nicht von Hand anlegen oder ändern.', 'Los registros de tarea los crea el frente. No se añaden ni editan a mano.', 'Les journaux de tâche viennent du front. Pas d’ajout ni d’édition à la main.', '과제 기록은 프론트가 완료할 때 생깁니다. 손으로 넣거나 고칠 수 없습니다.', 'Os registos de tarefa nascem na frente. Não se acrescentam nem editam à mão.', '課題記録はフロント完了で生まれます。手で足したり直せません。'),
    'ui.ro_signs' => $t('Check-ins are tapped by members on the front. Admin only views and deletes.', '签到由会员在前台点。后台只查看和删除。', 'Check-ins tippen Mitglieder vorn. Admin sieht und löscht nur.', 'El check-in lo pulsan los miembros. El admin solo ve y borra.', 'Le check-in est tapé par les membres. L’admin voit et supprime seulement.', '출석은 회원이 프론트에서 누릅니다. 관리는 보기와 삭제만.', 'O check-in é tocado pelos membros. O admin só vê e apaga.', 'チェックインは会員がフロントで押します。管理は閲覧と削除だけ。'),
    'ui.ro_botlogs' => $t('Spider logs are written when the front is visited. They cannot be added by hand.', '爬虫日志是前台访问记下来的，不能手添。', 'Spider-Logs schreibt der Frontend-Besuch. Nicht von Hand anlegen.', 'Los registros de araña los escribe la visita. No se añaden a mano.', 'Les journaux spider sont écrits par la visite. Pas d’ajout à la main.', '스파이더 로그는 프론트 방문이 남깁니다. 손으로 넣을 수 없습니다.', 'Os registos de spider nascem da visita. Não se acrescentam à mão.', 'クローラーログはフロント訪問が残します。手で足せません。'),
    'ui.ro_accesslogs' => $t('Visit rows are written when a page opens. They cannot be added by hand.', '访问流水是前台打开页面记下来的，不能手添。', 'Besuchszeilen schreibt das Öffnen einer Seite. Nicht von Hand anlegen.', 'Las visitas las escribe abrir una página. No se añaden a mano.', 'Les visites s’écrivent à l’ouverture d’une page. Pas d’ajout à la main.', '방문 기록은 페이지를 열 때 남깁니다. 손으로 넣을 수 없습니다.', 'As visitas nascem ao abrir uma página. Não se acrescentam à mão.', '訪問流水はページを開くと残ります。手で足せません。'),
    'ui.ro_withdraws' => $t('Withdrawals are requested by members. Admin only reviews payout or refusal.', '提现由会员申请。后台只审核打款或拒绝。', 'Auszahlungen beantragen Mitglieder. Admin prüft Auszahlung oder Ablehnung.', 'Los retiros los piden los miembros. El admin solo revisa pago o rechazo.', 'Les retraits sont demandés par les membres. L’admin relit paiement ou refus.', '출금은 회원이 신청합니다. 관리는 지급 또는 거절만 심사합니다.', 'Os levantamentos são pedidos pelos membros. O admin só revê pagamento ou recusa.', '出金は会員が申請。管理は振込か拒否の審査だけ。'),
    'ui.need_link_name' => $t('Enter a site name', '请填写网站名称', 'Einen Seitennamen eingeben', 'Escriba un nombre de sitio', 'Saisissez un nom de site', '사이트 이름을 입력하세요', 'Introduza um nome de sítio', 'サイト名を入力してください'),
    'ui.need_site_name' => $t('Enter a site name', '请填写站点名称', 'Einen Stationsnamen eingeben', 'Escriba un nombre de estación', 'Saisissez un nom de station', '스테이션 이름을 입력하세요', 'Introduza um nome de estação', 'サイト名を入力してください'),
    'ui.bad_url' => $t('URL format is wrong', '网址格式不对', 'URL-Format falsch', 'El formato de URL no es válido', 'Format d’URL incorrect', '주소 형식이 틀렸습니다', 'O formato do URL está errado', 'URL の形式が違います'),
    'ui.type_missing' => $t('Category not found', '分类不存在', 'Kategorie nicht gefunden', 'Categoría no encontrada', 'Catégorie introuvable', '분류가 없습니다', 'Categoria não encontrada', 'カテゴリがありません'),
    'ui.not_website_type' => $t('That category is not a link directory. Create one under Link categories.', '这个分类不是网址导航，请到「导航分类」里新建', 'Das ist keine Linkverzeichnis-Kategorie. Legen Sie eine unter Link-Kategorien an.', 'Esa categoría no es de directorio. Cree una en Categorías de enlaces.', 'Cette catégorie n’est pas un annuaire. Créez-en une dans Catégories de liens.', '그 분류는 사이트 디렉터리가 아닙니다. 「디렉터리 분류」에서 새로 만드세요.', 'Essa categoria não é de diretório. Crie uma em Categorias de ligações.', 'その分類はリンク集ではありません。「リンク分類」で新規作成してください。'),
    'ui.need_host' => $t('Enter a domain, without http or a path', '请填写域名，不要带 http 和路径', 'Domain ohne http und Pfad eingeben', 'Escriba un dominio, sin http ni ruta', 'Saisissez un domaine, sans http ni chemin', '도메인을 입력하세요. http와 경로는 빼세요', 'Introduza um domínio, sem http nem caminho', 'ドメインを入力。http と経路は付けないでください'),
    'ui.host_taken' => $t('That domain is already bound', '这个域名已经绑过', 'Diese Domain ist schon gebunden', 'Ese dominio ya está ligado', 'Ce domaine est déjà lié', '그 도메인은 이미 묶여 있습니다', 'Esse domínio já está ligado', 'そのドメインは既に紐づいています'),
    'ui.theme_dir_missing' => $t('That theme folder does not exist', '这个模板目录不存在', 'Dieser Vorlagenordner existiert nicht', 'Esa carpeta de tema no existe', 'Ce dossier de thème n’existe pas', '그 템플릿 폴더가 없습니다', 'Essa pasta de tema não existe', 'そのテンプレートフォルダはありません'),
    'ui.need_class_word' => $t('Enter a type word', '请填写类型词', 'Ein Typwort eingeben', 'Escriba una palabra de tipo', 'Saisissez un mot de type', '유형 단어를 입력하세요', 'Introduza uma palavra de tipo', 'タイプ語を入力してください'),
    'ui.one_word' => $t('One word at a time, no commas', '一次只写一个词，不要逗号', 'Nur ein Wort, keine Kommas', 'Una palabra cada vez, sin comas', 'Un seul mot, pas de virgules', '한 번에 한 단어, 쉼표 없이', 'Uma palavra de cada vez, sem vírgulas', '一度に一語、カンマなし'),
    'ui.word_taken' => $t('That word already exists', '这个词已经有了', 'Dieses Wort existiert schon', 'Esa palabra ya existe', 'Ce mot existe déjà', '그 단어는 이미 있습니다', 'Essa palavra já existe', 'その語は既にあります'),
    'ui.need_from_word' => $t('Enter the original word', '请填写原词', 'Das Ursprungswort eingeben', 'Escriba la palabra original', 'Saisissez le mot d’origine', '원래 단어를 입력하세요', 'Introduza a palavra original', '元の語を入力してください'),
    'ui.need_to_word' => $t('Enter the word to treat it as', '请填写要当成的词', 'Das Zielwort eingeben', 'Escriba la palabra de destino', 'Saisissez le mot cible', '바꿀 단어를 입력하세요', 'Introduza a palavra de destino', '見なす語を入力してください'),
    'ui.from_to_same' => $t('Original and treated-as cannot be the same', '原词和当成的词不能一样', 'Ursprung und Ziel dürfen nicht gleich sein', 'Original y destino no pueden ser iguales', 'Origine et cible ne peuvent pas être identiques', '원래 단어와 바꿀 단어가 같으면 안 됩니다', 'Original e destino não podem ser iguais', '元の語と見なす語は同じにできません'),
    'ui.from_taken' => $t('That original word already exists', '这个原词已经有了', 'Dieses Ursprungswort existiert schon', 'Esa palabra original ya existe', 'Ce mot d’origine existe déjà', '그 원래 단어는 이미 있습니다', 'Essa palavra original já existe', 'その元の語は既にあります'),
    'ui.need_downer_code' => $t('Enter an identifier matching the downloader field on lines', '请填写标识，要和线路上的下载器字段一致', 'Kennung eingeben, passend zum Downloader-Feld der Leitung', 'Escriba un identificador igual al campo de descargador de la línea', 'Saisissez un identifiant égal au champ downloader de la ligne', '식별자를 입력하세요. 회선의 다운로더 필드와 같아야 합니다', 'Introduza um identificador igual ao campo de downloader da linha', '識別を入力。回線のダウンローダー欄と一致させてください'),
    'ui.code_alpha_downer' => $t('Identifier must start with a letter, e.g. http, xunlei', '标识用英文字母开头，如 http、xunlei', 'Kennung mit Buchstaben beginnen, z. B. http, xunlei', 'El identificador empieza por letra, p. ej. http, xunlei', 'L’identifiant commence par une lettre, ex. http, xunlei', '식별자는 영문으로 시작, 예: http, xunlei', 'O identificador começa por letra, ex. http, xunlei', '識別は英字で開始。例: http、xunlei'),
    'ui.code_taken' => $t('That identifier already exists', '这个标识已经有了', 'Diese Kennung existiert schon', 'Ese identificador ya existe', 'Cet identifiant existe déjà', '그 식별자는 이미 있습니다', 'Esse identificador já existe', 'その識別は既にあります'),
    'ui.bad_tpl_protocol' => $t('That protocol is not allowed in the template URL', '模板地址不能用这种协议', 'Dieses Protokoll ist in der Vorlagen-URL nicht erlaubt', 'Ese protocolo no vale en la URL de plantilla', 'Ce protocole n’est pas permis dans l’URL du modèle', '템플릿 주소에 그 프로토콜은 쓸 수 없습니다', 'Esse protocolo não é permitido no URL do modelo', 'テンプレートURLにそのプロトコルは使えません'),
    'ui.name_taken' => $t('That name already exists', '这个名称已经有了', 'Dieser Name existiert schon', 'Ese nombre ya existe', 'Ce nom existe déjà', '그 이름은 이미 있습니다', 'Esse nome já existe', 'その名前は既にあります'),
    'ui.bad_prefix_protocol' => $t('That protocol is not allowed in the prefix', '前缀不能用这种协议', 'Dieses Protokoll ist im Präfix nicht erlaubt', 'Ese protocolo no vale en el prefijo', 'Ce protocole n’est pas permis dans le préfixe', '접두사에 그 프로토콜은 쓸 수 없습니다', 'Esse protocolo não é permitido no prefixo', '接頭辞にそのプロトコルは使えません'),
    'ui.prefix_incomplete' => $t('Prefix is incomplete', '前缀不完整', 'Präfix unvollständig', 'El prefijo está incompleto', 'Préfixe incomplet', '접두사가 불완전합니다', 'O prefixo está incompleto', '接頭辞が不完全です'),
    'ui.prefix_long' => $t('Prefix is too long', '前缀太长', 'Präfix zu lang', 'El prefijo es demasiado largo', 'Préfixe trop long', '접두사가 너무 깁니다', 'O prefixo é demasiado longo', '接頭辞が長すぎます'),
    'ui.need_api_url' => $t('Enter an API URL', '请填写接口地址', 'Eine API-URL eingeben', 'Escriba una URL de API', 'Saisissez une URL d’API', 'API 주소를 입력하세요', 'Introduza um URL de API', 'API アドレスを入力してください'),
    'ui.need_player_code' => $t('Enter an identifier matching the player field on lines', '请填写标识，要和线路上的播放器字段一致', 'Kennung eingeben, passend zum Player-Feld der Leitung', 'Escriba un identificador igual al campo de reproductor de la línea', 'Saisissez un identifiant égal au champ lecteur de la ligne', '식별자를 입력하세요. 회선의 플레이어 필드와 같아야 합니다', 'Introduza um identificador igual ao campo de leitor da linha', '識別を入力。回線のプレイヤー欄と一致させてください'),
    'ui.code_alpha_player' => $t('Identifier must start with a letter, e.g. artplayer, dplayer', '标识用英文字母开头，如 artplayer、dplayer', 'Kennung mit Buchstaben beginnen, z. B. artplayer, dplayer', 'El identificador empieza por letra, p. ej. artplayer, dplayer', 'L’identifiant commence par une lettre, ex. artplayer, dplayer', '식별자는 영문으로 시작, 예: artplayer, dplayer', 'O identificador começa por letra, ex. artplayer, dplayer', '識別は英字で開始。例: artplayer、dplayer'),
    'ui.need_role_name' => $t('Enter a role name', '请填写角色名', 'Einen Rollennamen eingeben', 'Escriba un nombre de rol', 'Saisissez un nom de rôle', '역할 이름을 입력하세요', 'Introduza um nome de papel', '役割名を入力してください'),
    'ui.video_missing' => $t('Video not found', '影片不存在', 'Video nicht gefunden', 'Vídeo no encontrado', 'Vidéo introuvable', '영상이 없습니다', 'Vídeo não encontrado', '映像がありません'),
    'ui.actor_missing' => $t('Actor not found', '演员不存在', 'Darsteller nicht gefunden', 'Actor no encontrado', 'Acteur introuvable', '배우가 없습니다', 'Ator não encontrado', '俳優がいません'),
    'ui.need_episode' => $t('Enter an episode number starting at 1', '请填写集数，从 1 开始', 'Folgennummer ab 1 eingeben', 'Escriba un número de episodio desde 1', 'Saisissez un numéro d’épisode à partir de 1', '회차는 1부터 입력하세요', 'Introduza um número de episódio a partir de 1', '話数は 1 から入力してください'),
    'ui.need_plot' => $t('Enter the plot for this episode', '请填写这一集的剧情', 'Die Handlung dieser Folge eingeben', 'Escriba la trama de este episodio', 'Saisissez l’intrigue de cet épisode', '이 회의 줄거리를 입력하세요', 'Introduza o enredo deste episódio', 'この話のあらすじを入力してください'),
    'ui.plot_dup' => $t('This episode already has a plot', '这一集已经写过剧情', 'Diese Folge hat schon eine Handlung', 'Este episodio ya tiene trama', 'Cet épisode a déjà une intrigue', '이 회는 이미 줄거리가 있습니다', 'Este episódio já tem enredo', 'この話には既にあらすじがあります'),
    'ui.need_actor_name' => $t('Actor name cannot be empty', '演员名称不能为空', 'Darstellername darf nicht leer sein', 'El nombre del actor no puede estar vacío', 'Le nom de l’acteur ne peut pas être vide', '배우 이름은 비울 수 없습니다', 'O nome do ator não pode estar vazio', '俳優名は空にできません'),
];
