<?php

/**
 * Accesslog / attachments / runtime / website-collect / video-form chrome.
 */
$t = static fn (string $de, string $es, string $fr, string $ko, string $pt, string $ja): array => [
    'de' => $de, 'es' => $es, 'fr' => $fr, 'ko' => $ko, 'pt' => $pt, 'ja' => $ja,
];

return [
    'ui.accesslog_lead_before' => $t(
        'Nur Frontend-GET. Admin, js/css und Plugin-Statik nicht. Klick auf IP filtert die Adresse.',
        'Solo GET del frente. Admin, js/css y estáticos de plugin no. Clic en IP filtra esa dirección.',
        'Seuls les GET du site. Admin, js/css et statiques plugin exclus. Un clic IP filtre l’adresse.',
        '프론트 GET만 기록. 관리/js/css/플러그인 정적은 제외. IP를 누르면 그 주소만.',
        'Só GET do site. Admin, js/css e estáticos de plugin não. Clique no IP para filtrar.',
        'フロントの GET のみ。管理・js/css・プラグイン静的は記録しません。IP をクリックするとその住所。'
    ),
    'ui.accesslog_lead_end' => $t('.', '.', '.', '.', '.', '。'),
    'ui.accesslog_lead_mid' => $t(
        '. Auch kein Rate-Limit. Die Allowlist gilt nur für ',
        '. Tampoco hay límite de ritmo. La lista blanca solo cubre ',
        '. Pas de limitation de débit. La liste blanche ne porte que sur ',
        '. 속도 제한도 없습니다. 허용 목록은 ',
        '. Sem limite de ritmo. A lista só cobre ',
        '。レート制限もありません。許可リストは '
    ),
    'ui.accesslog_lead_after_admin' => $t(
        '. Titel und Referer unter „',
        '. Títulos y procedencia en «',
        '. Titres et provenances dans « ',
        '. 제목과 유입은 「',
        '. Títulos e origem em «',
        '。タイトルと流入は「'
    ),
    'ui.accesslog_lead_after_detail' => $t(
        '“; Fehler unter „',
        '»; errores en «',
        ' » ; erreurs dans « ',
        '」; 오류는 「',
        '»; erros em «',
        '」；エラーは「'
    ),
    'ui.accesslog_lead_after_sys' => $t(
        '“; Spider teilen die Tabelle, Schnitt unter „',
        '»; los spiders comparten tabla, recorte en «',
        ' » ; les spiders partagent la table, extrait dans « ',
        '」; 스파이더는 같은 표, 절편은 「',
        '»; spiders partilham a tabela, recorte em «',
        '」；クローラは同じ表、切片は「'
    ),
    'ui.accesslog_lead_tail' => $t('“.', '».', ' ».', '」.', '».', '」。'),
    'ui.empty_front_visits' => $t('Noch keine Frontend-Zugriffe', 'Aún no hay visitas al frente', 'Pas encore de visites front', '프론트 방문이 없습니다', 'Ainda sem visitas ao site', 'まだフロントの訪問がありません'),
    'ui.empty_front_visits_hint' => $t(
        'Nur Admin lokal zählt nicht. Eine öffentliche Seite öffnen.',
        'Solo admin local no cuenta. Abra una página pública.',
        'Admin local seul ne compte pas. Ouvrez une page publique.',
        '관리만 열면 기록되지 않습니다. 공개 페이지를 여세요.',
        'Só admin local não conta. Abra uma página pública.',
        '管理だけ開いても記録しません。公開ページを開いてください。'
    ),
    'ui.confirm_batch_del_access' => $t('Diese :n Zeilen löschen? Nur Log, keine IP-Sperre.', '¿Borrar estas :n filas? Solo el log, no bloquea IP.', 'Supprimer ces :n lignes ? Journal seulement, pas de ban IP.', '이 :n건을 삭제할까요? 로그만, IP 차단 아님.', 'Apagar estas :n linhas? Só o log, sem banir IP.', 'この :n 件を削除しますか？ログのみ、IP 禁止ではありません。'),
    'ui.confirm_del_access' => $t('Diese Zeile löschen? Nur Log, keine IP-Sperre.', '¿Borrar esta fila? Solo el log, no bloquea IP.', 'Supprimer cette ligne ? Journal seulement, pas de ban IP.', '이 행을 삭제할까요? 로그만, IP 차단 아님.', 'Apagar esta linha? Só o log, sem banir IP.', 'この行を削除しますか？ログのみ、IP 禁止ではありません。'),
    'ui.please_select_rows' => $t('Zuerst Zeilen wählen', 'Seleccione filas primero', 'Sélectionnez d’abord des lignes', '먼저 행을 선택하세요', 'Selecione linhas primeiro', '先に行を選んでください'),
    'ui.open_front' => $t('Site öffnen', 'Abrir el sitio', 'Ouvrir le site', '사이트 열기', 'Abrir o site', 'サイトを開く'),
    'ui.files_title' => $t('Anhänge', 'Adjuntos', 'Pièces jointes', '첨부', 'Anexos', '添付'),
    'ui.files_lead' => $t(
        'Im Admin hochgeladene Dateien. Bilder zeigen Miniaturen; Klick vergrößert.',
        'Archivos subidos en admin. Las imágenes muestran miniatura; clic para ampliar.',
        'Fichiers envoyés dans l’admin. Miniatures pour les images ; clic pour agrandir.',
        '관리에서 올린 파일. 이미지는 썸네일, 클릭하면 확대.',
        'Ficheiros enviados no admin. Imagens têm miniatura; clique para ampliar.',
        '管理でアップロードしたファイル。画像はサムネイル、クリックで拡大。'
    ),
    'ui.files_note' => $t(
        'Nur indizierte Datensätze. PDF, Archive und Videos ohne Miniatur. Unindizierte Dateien auf der Platte fehlen.',
        'Solo registros indexados. PDF, archivos y vídeos sin miniatura. Lo no indexado en disco no aparece.',
        'Seuls les enregistrements indexés. PDF, archives et vidéos sans miniature. Le disque non indexé n’apparaît pas.',
        '인덱된 기록만. PDF·압축·영상은 썸네일 없음. 디스크에만 있는 파일은 안 나옵니다.',
        'Só registos indexados. PDF, arquivos e vídeos sem miniatura. O que está no disco sem índice não aparece.',
        '索引済みのみ。PDF・書庫・動画にサムネイルなし。ディスクだけの未登録は出ません。'
    ),
    'ui.ph_search_file' => $t('Name, Typ oder URL', 'Nombre, tipo o URL', 'Nom, type ou URL', '이름·유형·주소 검색', 'Nome, tipo ou URL', '名前・種類・URL を検索'),
    'ui.empty_files' => $t('Noch keine Anhänge', 'Aún no hay adjuntos', 'Pas encore de pièces jointes', '아직 첨부가 없습니다', 'Ainda sem anexos', 'まだ添付がありません'),
    'ui.empty_files_hint' => $t('Oben rechts hochladen. Bilder bekommen Miniaturen.', 'Suba arriba a la derecha. Las imágenes tendrán miniatura.', 'Envoyez en haut à droite. Les images auront une miniature.', '오른쪽 위에서 업로드. 이미지는 썸네일이 생깁니다.', 'Carregue no canto superior direito. Imagens ganham miniatura.', '右上からアップロード。画像はサムネイルが付きます。'),
    'ui.empty_file_search' => $t('Keine Datei mit diesem Namen', 'Ningún archivo con ese nombre', 'Aucun fichier de ce nom', '그 이름의 파일이 없습니다', 'Nenhum ficheiro com esse nome', 'その名前のファイルはありません'),
    'ui.empty_file_kind' => $t('Keine Dateien in dieser Kategorie', 'No hay archivos en esta categoría', 'Aucun fichier dans cette catégorie', '이 종류에 파일이 없습니다', 'Sem ficheiros nesta categoria', 'この種類のファイルはありません'),
    'ui.no_preview' => $t('Keine Vorschau', 'Sin vista previa', 'Pas d’aperçu', '미리보기 불가', 'Sem pré-visualização', 'プレビューできません'),
    'ui.click_to_enlarge' => $t('Zum Vergrößern klicken', 'Clic para ampliar', 'Cliquer pour agrandir', '클릭하여 확대', 'Clique para ampliar', 'クリックで拡大'),
    'ui.kind_video' => $t('Video', 'Vídeo', 'Vidéo', '영상', 'Vídeo', '動画'),
    'ui.kind_other' => $t('Sonstiges', 'Otros', 'Autres', '기타', 'Outros', 'その他'),
    'ui.kind_file' => $t('Datei', 'Archivo', 'Fichier', '파일', 'Ficheiro', 'ファイル'),
    'ui.upload_file' => $t('Datei hochladen', 'Subir archivo', 'Envoyer un fichier', '파일 업로드', 'Carregar ficheiro', 'ファイルをアップロード'),
    'ui.batch_delete' => $t('Auswahl löschen', 'Borrar selección', 'Supprimer la sélection', '일괄 삭제', 'Apagar seleção', '一括削除'),
    'ui.n_files' => $t(':n Dateien', ':n archivos', ':n fichiers', ':n개', ':n ficheiros', ':n 件'),
    'ui.confirm_batch_del_files' => $t('Ausgewählte Dateien löschen?', '¿Borrar los archivos seleccionados?', 'Supprimer les fichiers sélectionnés ?', '선택한 파일을 삭제할까요?', 'Apagar os ficheiros selecionados?', '選択したファイルを削除しますか？'),
    'ui.confirm_del_file' => $t('Diese Datei löschen?', '¿Borrar este archivo?', 'Supprimer ce fichier ?', '이 파일을 삭제할까요?', 'Apagar este ficheiro?', 'このファイルを削除しますか？'),
    'ui.cannot_open_image' => $t('Bild lässt sich nicht öffnen', 'No se puede abrir esta imagen', 'Impossible d’ouvrir cette image', '이 그림을 열 수 없습니다', 'Não é possível abrir esta imagem', 'この画像を開けません'),
    'ui.no_usable_link' => $t('Kein nutzbarer Link', 'Sin enlace usable', 'Pas de lien utilisable', '쓸 수 있는 링크 없음', 'Sem ligação utilizável', '使えるリンクがありません'),
    'ui.please_select_files' => $t('Dateien zum Löschen wählen', 'Seleccione archivos a borrar', 'Sélectionnez les fichiers à supprimer', '삭제할 파일을 선택하세요', 'Selecione ficheiros a apagar', '削除するファイルを選んでください'),
    'ui.aria_search_files' => $t('Anhänge suchen', 'Buscar adjuntos', 'Chercher des pièces jointes', '첨부 검색', 'Pesquisar anexos', '添付を検索'),
    'ui.firing_n' => $t(':n aktiv', ':n disparando', ':n en cours', ':n건 발생 중', ':n a disparar', ':n 件発生中'),
    'ui.cron_dead_before' => $t('Collector steht. Unter „', 'El recolector no corre. En «', 'Le collecteur est arrêté. Dans « ', '수집이 멈춤. 「', 'O coletor está parado. Em «', '収集が止まっています。「'),
    'ui.cron_dead_after' => $t('“ prüfen, ob ', '» confirme que ', ' » confirmez que ', '」에서 ', '» confirme que ', '」で '),
    'ui.cron_dead_end' => $t(' installiert ist.', ' está instalado.', ' est installé.', ' 설치를 확인.', ' está instalado.', ' の導入を確認。'),
    'ui.copy_cmd' => $t('Befehl kopieren', 'Copiar comando', 'Copier la commande', '명령 복사', 'Copiar comando', 'コマンドをコピー'),
    'ui.runtime_same_cron' => $t('Dieselbe crontab wie der Planer — kein Extra-Monitor-Plugin.', 'El mismo crontab que el programador; no hace falta plugin extra.', 'Même crontab que le planificateur — pas de plugin monitor.', '스케줄러와 같은 crontab, 별도 모니터 플러그인 없음.', 'O mesmo crontab do agendador — sem plugin extra.', 'スケジューラと同じ crontab。監視プラグインは不要。'),
    'ui.range_1h' => $t('1 Stunde', '1 hora', '1 heure', '1시간', '1 hora', '1時間'),
    'ui.range_6h' => $t('6 Stunden', '6 horas', '6 heures', '6시간', '6 horas', '6時間'),
    'ui.range_24h' => $t('24 Stunden', '24 horas', '24 heures', '24시간', '24 horas', '24時間'),
    'ui.range_72h' => $t('72 Stunden', '72 horas', '72 heures', '72시간', '72 horas', '72時間'),
    'ui.range_7d' => $t('7 Tage', '7 días', '7 jours', '7일', '7 dias', '7日'),
    'ui.range_30d' => $t('30 Tage', '30 días', '30 jours', '30일', '30 dias', '30日'),
    'ui.reading_samples' => $t('Proben werden gelesen…', 'Leyendo muestras…', 'Lecture des échantillons…', '샘플을 읽는 중…', 'A ler amostras…', 'サンプルを読み込み中…'),
    'ui.last_5min_hint' => $t('Letzte 5 Minuten. Leer heißt noch nicht erfasst, nicht 0.', 'Últimos 5 minutos. Vacío = aún no muestreado, no 0.', '5 dernières minutes. Vide = pas encore échantillonné, pas 0.', '최근 5분. 비어 있으면 아직 미수집, 0이 아님.', 'Últimos 5 minutos. Vazio = ainda não amostrado, não 0.', '直近5分。空は未採取であり 0 ではありません。'),
    'ui.pause' => $t('Pause', 'Pausa', 'Pause', '일시정지', 'Pausa', '一時停止'),
    'ui.resume' => $t('Weiter', 'Continuar', 'Reprendre', '계속', 'Continuar', '再開'),
    'ui.req_5min' => $t('Anfragen (5 Min.)', 'Peticiones (5 min)', 'Requêtes (5 min)', '요청(5분)', 'Pedidos (5 min)', 'リクエスト（5分）'),
    'ui.err_5min' => $t('5xx (5 Min.)', '5xx (5 min)', '5xx (5 min)', '5xx(5분)', '5xx (5 min)', '5xx（5分）'),
    'ui.slow_5min' => $t('Langsam (5 Min.)', 'Lentas (5 min)', 'Lentes (5 min)', '느린 요청(5분)', 'Lentos (5 min)', '遅いリクエスト（5分）'),
    'ui.load_label' => $t('Last', 'Carga', 'Charge', '부하', 'Carga', '負荷'),
    'ui.mem_pct' => $t('Speicher %', 'Memoria %', 'Mémoire %', '메모리 %', 'Memória %', 'メモリ %'),
    'ui.disk_pct' => $t('Disk %', 'Disco %', 'Disque %', '디스크 %', 'Disco %', 'ディスク %'),
    'ui.php_mem_pct' => $t('PHP-Speicher %', 'Memoria PHP %', 'Mémoire PHP %', 'PHP 메모리 %', 'Memória PHP %', 'PHP メモリ %'),
    'ui.enable_collect' => $t('Erfassung einschalten', 'Activar recolección', 'Activer la collecte', '수집 켜기', 'Ativar recolha', '収集をオン'),
    'ui.slow_threshold_ms' => $t('Langsam-Schwelle (ms)', 'Umbral lento (ms)', 'Seuil lent (ms)', '느린 요청 기준(ms)', 'Limiar lento (ms)', '遅いリクエスト閾値（ms）'),
    'ui.slow_threshold_hint' => $t('Länger dauernde Anfragen gelten als langsam', 'Las más lentas se marcan como lentas', 'Au-delà, la requête est lente', '이보다 느리면 느린 요청으로 기록', 'Acima disto conta como lento', 'これを超えると遅いリクエスト'),
    'ui.keep_min_days' => $t('Minuten-Daten (Tage)', 'Retención por minuto (días)', 'Rétention minute (jours)', '분 데이터 보관(일)', 'Retenção ao minuto (dias)', '分データの保持（日）'),
    'ui.keep_hour_days' => $t('Stunden-Daten (Tage)', 'Retención por hora (días)', 'Rétention heure (jours)', '시간 데이터 보관(일)', 'Retenção à hora (dias)', '時間データの保持（日）'),
    'ui.unusual_hit_threshold' => $t('Ungewöhnliche Zugriffe (24h)', 'Umbral de acceso inusual (24h)', 'Seuil d’accès inhabituel (24h)', '이상 접근 횟수(24시간)', 'Limiar de acesso invulgar (24h)', '異常アクセス回数（24時間）'),
    'ui.unusual_hit_hint' => $t('Darüber als hohe Zahl auf Ungewöhnlicher Zugriff', 'Por encima se marca alto en Acceso inusual', 'Au-delà, marqué élevé dans Accès inhabituel', '초과 시 이상 접근에 「횟수 높음」', 'Acima marca alto em Acesso invulgar', '超えると異常アクセスで「回数が多い」'),
    'ui.last_heartbeat' => $t('Letzter Heartbeat: :t', 'Último heartbeat: :t', 'Dernier heartbeat : :t', '최근 하트비트: :t', 'Último heartbeat: :t', '最終ハートビート：:t'),
    'ui.never_ran' => $t('Noch nie gelaufen', 'Nunca ejecutado', 'Jamais exécuté', '아직 실행 없음', 'Nunca correu', 'まだ実行なし'),
    'ui.collect_not_running' => $t('Collector idle', 'Recolector inactivo', 'Collecteur inactif', '수집 정지', 'Coletor inativo', '収集停止'),
    'ui.heartbeat' => $t('Heartbeat', 'Heartbeat', 'Heartbeat', '하트비트', 'Heartbeat', 'ハートビート'),
    'ui.os_label' => $t('System', 'Sistema', 'Système', '시스템', 'Sistema', 'システム'),
    'ui.rules_default_off' => $t('Empfohlene Regeln starten aus. Test prüft nur die aktuelle Probe.', 'Las reglas recomendadas empiezan apagadas. La prueba solo mira la muestra actual.', 'Les règles conseillées démarrent off. Le test ne lit que l’échantillon actuel.', '권장 규칙은 기본 꺼짐. 시험은 현재 샘플만 봅니다.', 'Regras recomendadas começam desligadas. O teste só vê a amostra atual.', '推奨ルールは初期オフ。試行は現在のサンプルのみ。'),
    'ui.metric' => $t('Metrik', 'Métrica', 'Métrique', '지표', 'Métrica', '指標'),
    'ui.condition' => $t('Bedingung', 'Condición', 'Condition', '조건', 'Condição', '条件'),
    'ui.n_minutes' => $t(':n Min.', ':n min', ':n min', ':n분', ':n min', ':n 分'),
    'ui.edit_threshold' => $t('Schwelle ändern', 'Editar umbral', 'Modifier le seuil', '임계값 변경', 'Editar limiar', '閾値を変更'),
    'ui.try_run' => $t('Testlauf', 'Probar', 'Essai', '시험 실행', 'Testar', '試行'),
    'ui.empty_rules' => $t('Noch keine Regeln', 'Aún no hay reglas', 'Pas encore de règles', '아직 규칙이 없습니다', 'Ainda sem regras', 'まだルールがありません'),
    'ui.threshold' => $t('Schwelle', 'Umbral', 'Seuil', '임계값', 'Limiar', '閾値'),
    'ui.events_local_only' => $t('Ereignisse bleiben in der DB; nichts wird versendet.', 'Los eventos quedan en la base; no se envía nada.', 'Les événements restent en base ; rien n’est envoyé.', '이벤트는 DB에만 남고 외부 발송 없음.', 'Os eventos ficam na base; nada é enviado.', 'イベントはDBのみ。外部通知なし。'),
    'ui.firing' => $t('Aktiv', 'Disparando', 'En cours', '발생 중', 'A disparar', '発生中'),
    'ui.recovered' => $t('Erholt', 'Recuperado', 'Rétabli', '복구됨', 'Recuperado', '回復済み'),
    'ui.acknowledged' => $t('Bestätigt', 'Confirmado', 'Accusé', '확인됨', 'Confirmado', '確認済み'),
    'ui.empty_events' => $t('Noch keine Ereignisse', 'Aún no hay eventos', 'Pas encore d’événements', '아직 이벤트가 없습니다', 'Ainda sem eventos', 'まだイベントがありません'),
    'ui.empty_events_status' => $t('Keine Ereignisse in diesem Status', 'No hay eventos en este estado', 'Aucun événement dans cet état', '이 상태의 이벤트가 없습니다', 'Sem eventos neste estado', 'この状態のイベントはありません'),
    'ui.runtime_access_lead_before' => $t('Nur ansehen — hier keine IP-Sperre. Admin drosseln über „', 'Solo ver — aquí no se bloquean IP. Para el admin use «', 'Consultation seule — pas de ban IP. Pour l’admin, « ', '보기만, 여기서 IP를 막을 수 없습니다. 관리는 「', 'Só ver — aqui não se bane IP. Para o admin use «', '閲覧のみ。ここでは IP を禁止できません。管理は「'),
    'ui.runtime_access_lead_after' => $t('“.', '».', ' ».', '」.', '».', '」。'),
    'ui.runtime_access_lead_ip' => $t('Klick auf IP zeigt die Spur.', 'Clic en IP muestra el rastro.', 'Un clic IP montre la piste.', 'IP를 누르면 흐름을 봅니다.', 'Clique no IP para ver o rasto.', 'IP をクリックするとログ。'),
    'ui.high_count' => $t('Hoch', 'Alto', 'Élevé', '높음', 'Alto', '高め'),
    'ui.trail_log' => $t('Spur', 'Rastro', 'Piste', '흐름', 'Rasto', 'ログ'),
    'ui.last_24h_cc' => $t('Letzte 24 Std. · Schwelle :n', 'Últimas 24 h · umbral :n', '24 dernières h · seuil :n', '최근 24시간 · 기준 :n회', 'Últimas 24 h · limiar :n', '直近24時間 · 閾値 :n 回'),
    'ui.flag_col' => $t('Kennzeichen', 'Marca', 'Marque', '표시', 'Marca', 'マーク'),
    'ui.path_col' => $t('Pfad', 'Ruta', 'Chemin', '경로', 'Caminho', 'パス'),
    'ui.view_ip_trail' => $t('Spur dieser IP', 'Rastro de esta IP', 'Piste de cette IP', '이 IP의 흐름', 'Rasto deste IP', 'この IP のログ'),
    'ui.empty_high_ips' => $t('Keine hohen oder Scan-IPs in 24 Std.', 'Sin IP altas o de escaneo en 24 h', 'Pas d’IP élevées ou scan en 24 h', '24시간 내 높음/스캔 IP 없음', 'Sem IPs altos ou de scan em 24 h', '24時間以内に高め・スキャン IP なし'),
    'ui.empty_access_ips' => $t('Keine sichtbaren IPs in 24 Std.', 'Sin IPs visibles en 24 h', 'Pas d’IP visibles en 24 h', '24시간 내 볼 IP 없음', 'Sem IPs visíveis em 24 h', '24時間以内に見える IP なし'),
    'ui.empty_chart' => $t('Keine Punkte in diesem Bereich; Kurve leer.', 'No hay puntos en este rango; la curva está vacía.', 'Aucun point dans cette plage ; courbe vide.', '이 구간에 점이 없어 곡선이 비어 있습니다.', 'Sem pontos neste intervalo; curva vazia.', 'この範囲に点がなく、曲線は空です。'),
    'ui.gran_hour' => $t('Dieser Bereich nach Stunden.', 'Este rango se agrupa por hora.', 'Cette plage est agrégée à l’heure.', '이 구간은 시간 단위.', 'Este intervalo agrega por hora.', 'この区間は時間集計です。'),
    'ui.gran_min' => $t('Dieser Bereich nach Minuten.', 'Este rango se agrupa por minuto.', 'Cette plage est agrégée à la minute.', '이 구간은 분 단위.', 'Este intervalo agrega por minuto.', 'この区間は分集計です。'),
    'ui.updated_at_clock' => $t('Aktualisiert :t', 'Actualizado :t', 'Mis à jour :t', '갱신 :t', 'Atualizado :t', '更新 :t'),
    'ui.please_fill_threshold' => $t('Schwelle eingeben', 'Introduzca un umbral', 'Saisissez un seuil', '임계값을 입력하세요', 'Introduza um limiar', '閾値を入力してください'),
    'ui.no_result' => $t('Kein Ergebnis', 'Sin resultado', 'Aucun résultat', '결과 없음', 'Sem resultado', '結果なし'),
    'ui.changed_ok' => $t('Geändert', 'Actualizado', 'Modifié', '변경됨', 'Atualizado', '変更しました'),
    'ui.ack_ok' => $t('Bestätigt', 'Confirmado', 'Accusé', '확인됨', 'Confirmado', '確認しました'),
    'ui.edit_threshold_named' => $t('Schwelle · :name', 'Umbral · :name', 'Seuil · :name', '임계값 · :name', 'Limiar · :name', '閾値 · :name'),
    'ui.flag_scan' => $t('Scan-Spuren', 'Rastros de escaneo', 'Traces de scan', '스캔 흔적', 'Vestígios de scan', 'スキャン痕跡'),
    'ui.flag_high' => $t('Hohe Zahl', 'Recuento alto', 'Volume élevé', '횟수 높음', 'Contagem alta', '回数が多い'),
    'ui.rule_on' => $t('An', 'Encendida', 'Active', '켜짐', 'Ligada', 'オン'),
    'ui.agg_avg' => $t('Mittel', 'Media', 'Moyenne', '평균', 'Média', '平均'),
    'ui.agg_max' => $t('Max', 'Máx', 'Max', '최대', 'Máx', '最大'),
    'ui.agg_sum' => $t('Summe', 'Suma', 'Somme', '합계', 'Soma', '合計'),
    'ui.agg_last' => $t('Letzter', 'Último', 'Dernier', '최신', 'Último', '最新'),
    'ui.metric_load1' => $t('1-Min-Last', 'Carga 1 min', 'Charge 1 min', '1분 부하', 'Carga 1 min', '1分負荷'),
    'ui.metric_load5' => $t('5-Min-Last', 'Carga 5 min', 'Charge 5 min', '5분 부하', 'Carga 5 min', '5分負荷'),
    'ui.metric_load15' => $t('15-Min-Last', 'Carga 15 min', 'Charge 15 min', '15분 부하', 'Carga 15 min', '15分負荷'),
    'ui.metric_cpu' => $t('CPU %', 'CPU %', 'CPU %', 'CPU %', 'CPU %', 'CPU %'),
    'ui.metric_req' => $t('Anfragen', 'Peticiones', 'Requêtes', '요청 수', 'Pedidos', 'リクエスト数'),
    'ui.metric_slow' => $t('Langsame Anfragen', 'Peticiones lentas', 'Requêtes lentes', '느린 요청', 'Pedidos lentos', '遅いリクエスト'),
    'ui.group_load' => $t('Systemlast', 'Carga del sistema', 'Charge système', '시스템 부하', 'Carga do sistema', 'システム負荷'),
    'ui.group_mem' => $t('Speicher und Disk', 'Memoria y disco', 'Mémoire et disque', '메모리와 디스크', 'Memória e disco', 'メモリとディスク'),
    'ui.group_req' => $t('Anfragevolumen', 'Volumen de peticiones', 'Volume de requêtes', '요청량', 'Volume de pedidos', 'リクエスト量'),
    'ui.group_http' => $t('Statuscodes', 'Códigos de estado', 'Codes de statut', '상태 코드', 'Códigos de estado', 'ステータスコード'),
    'ui.skip_req_count' => $t('Anfragezählung', 'Conteo de peticiones', 'Comptage des requêtes', '요청 카운트', 'Contagem de pedidos', 'リクエスト計数'),
    'ui.website_collect' => $t('Website-Sammlung', 'Recolección web', 'Collecte web', '사이트 수집', 'Recolha web', 'サイト収集'),
    'ui.new_website_collect' => $t('Neue Website-Sammlung', 'Nueva recolección web', 'Nouvelle collecte web', '사이트 수집 추가', 'Nova recolha web', 'サイト収集を追加'),
    'ui.edit_website_collect' => $t('Website-Sammlung bearbeiten', 'Editar recolección web', 'Modifier la collecte web', '사이트 수집 편집', 'Editar recolha web', 'サイト収集を編集'),
    'ui.cj_lead' => $t(
        'Von Webseiten, RSS oder JSON in Videos, Artikel oder Manga. Kein Ressourcen-API; für Apple-CMS täglich ',
        'Desde páginas, RSS o JSON a vídeos, artículos o manga. No es API de estación; para Apple CMS diario use ',
        'Depuis pages, RSS ou JSON vers vidéos, articles ou manga. Pas une API station ; pour Apple CMS quotidien, ',
        '웹·RSS·JSON에서 영상·기사·만화로. 자원국 API가 아닙니다. 애플 CMS 일상은 ',
        'De páginas, RSS ou JSON para vídeos, artigos ou manga. Não é API de estação; para Apple CMS diário use ',
        'ウェブ、RSS、JSON から動画・記事・漫画へ。資源站 API ではありません。Apple CMS の日常は'
    ),
    'ui.cj_lead_after' => $t(
        '. Erst Testabruf, dann aktivieren. Manga-Listen legen nur Werke an; Kapitel über Sammelquellen.',
        '. Pruebe primero, luego active. Listas manga solo crean obras; capítulos por fuentes.',
        '. Essayez d’abord, puis activez. Les listes manga ne créent que des œuvres.',
        '. 먼저 시험 수집 후 켜세요. 만화 목록은 작품만 만들고 챕터는 수집원.',
        '. Teste primeiro, depois ative. Listas manga só criam obras; capítulos nas fontes.',
        '。先に試抓し、タイトルが正しければ有効化。漫画一覧は作品のみ。章は収集源へ。'
    ),
    'ui.jobs' => $t('Aufgaben', 'Tareas', 'Tâches', '작업', 'Tarefas', 'タスク'),
    'ui.run_logs' => $t('Laufprotokoll', 'Registro de ejecución', 'Journal d’exécution', '실행 로그', 'Registo de execução', '実行ログ'),
    'ui.ph_cj_name' => $t('z. B. Site-Update-Liste', 'p. ej. lista de actualizaciones', 'ex. liste des mises à jour', '예: 사이트 업데이트 목록', 'ex. lista de atualizações', '例: サイト更新一覧'),
    'ui.collect_method' => $t('Sammelmethode', 'Método de recolección', 'Méthode de collecte', '수집 방식', 'Método de recolha', '収集方法'),
    'ui.cj_type_html' => $t('Webseite', 'Página web', 'Page web', '웹 페이지', 'Página web', 'ウェブページ'),
    'ui.cj_type_html_hint' => $t('Titel von der Liste; blättern und Details fürs Excerpt', 'Títulos de la lista; paginar y abrir detalle para el resumen', 'Titres de la liste ; pagination et détail pour le résumé', '목록에서 제목, 페이지·상세에서 소개', 'Títulos da lista; paginar e abrir detalhe para o resumo', '一覧からタイトル。ページ送りと詳細で紹介'),
    'ui.cj_type_rss' => $t('RSS-Feed', 'Fuente RSS', 'Flux RSS', 'RSS 구독', 'Feed RSS', 'RSS 購読'),
    'ui.cj_type_rss_hint' => $t('Öffentliche RSS-/Atom-URL einfügen', 'Pegue una URL RSS / Atom pública', 'Collez une URL RSS / Atom publique', '공개 RSS / Atom 주소를 넣으세요', 'Cole um URL RSS / Atom público', '公開 RSS / Atom アドレスを入れる'),
    'ui.cj_type_json' => $t('JSON-API', 'API JSON', 'API JSON', 'JSON API', 'API JSON', 'JSON API'),
    'ui.cj_type_json_hint' => $t('Titel und Links per Feldname aus der Liste', 'Títulos y enlaces por nombre de campo', 'Titres et liens par nom de champ', '필드명으로 목록에서 제목·링크', 'Títulos e ligações pelo nome do campo', 'フィールド名で一覧からタイトルとリンク'),
    'ui.cj_type_regex' => $t('Regex', 'Regex', 'Regex', '정규식', 'Regex', '正規表現'),
    'ui.write_into' => $t('Schreiben nach', 'Escribir en', 'Écrire dans', '기록 대상', 'Escrever em', '書き込み先'),
    'ui.cj_into_vod_hint' => $t('In die Videothek. m3u8 / mp4 zum Abspielen nötig', 'A la mediateca. Hace falta m3u8 / mp4 para reproducir', 'Vers la médiathèque. m3u8 / mp4 pour jouer vraiment', '영상 라이브러리. 재생엔 m3u8 / mp4 필요', 'Para a biblioteca. Precisa m3u8 / mp4 para tocar', '動画庫へ。再生には m3u8 / mp4'),
    'ui.cj_into_art_hint' => $t('In Artikel; Listenexcerpt wird Text', 'A artículos; el resumen de lista es el cuerpo', 'Vers articles ; l’extrait de liste devient le corps', '기사 라이브러리, 목록 소개가 본문', 'Para artigos; o resumo da lista vira corpo', '記事庫へ。一覧紹介が本文'),
    'ui.cj_into_manga_hint' => $t('Nach Manga; nur Werke. Kapitel über Quellen oder Inbound-API', 'A manga; solo obras. Capítulos por fuentes o API', 'Vers manga ; œuvres seulement. Chapitres via sources ou API', '만화 라이브러리, 작품만. 챕터는 수집원/입고 API', 'Para manga; só obras. Capítulos nas fontes ou API', '漫画庫へ。作品のみ。章は収集源か入库 API'),
    'ui.manga_plugin_off' => $t('Manga-Plugin ist aus', 'El plugin manga está apagado', 'Le plugin manga est off', '만화 플러그인 꺼짐', 'O plugin manga está desligado', '漫画プラグイン未有効'),
    'ui.cj_into_hint' => $t('Drei Bibliotheken getrennt. Ressourcen-APIs gehören zu Sammelquellen.', 'Tres bibliotecas aparte. Las APIs de estación van a Fuentes.', 'Trois bibliothèques séparées. Les API station vont aux sources.', '세 라이브러리는 따로. 자원국 API는 수집원으로.', 'Três bibliotecas à parte. APIs de estação vão às fontes.', '3つの庫は別。資源站 API は収集源へ。'),
    'ui.list_page_url' => $t('Listen-URL', 'URL de lista', 'URL de liste', '목록 주소', 'URL da lista', '一覧ページURL'),
    'ui.cj_url_hint_html' => $t('Nur erlaubte öffentliche Seiten. Details nur gleiche Site. Intranet wird abgelehnt.', 'Solo páginas públicas permitidas. Detalle en el mismo sitio. Intranet se rechaza.', 'Pages publiques autorisées seulement. Détail même site. Intranet refusé.', '권한이 있는 공개 페이지만. 상세는 같은 사이트. 내부망은 거절.', 'Só páginas públicas permitidas. Detalhe no mesmo site. Intranet recusado.', '権限のある公開ページのみ。詳細は同一サイト。イントラは拒否。'),
    'ui.write_category' => $t('In Kategorie', 'Escribir a categoría', 'Écrire dans la catégorie', '기록 분류', 'Escrever na categoria', '書き込み分類'),
    'ui.no_category' => $t('Keine Kategorie', 'Sin categoría', 'Sans catégorie', '분류 지정 안 함', 'Sem categoria', '分類なし'),
    'ui.cj_cat_hint' => $t('Eingehendes landet hier; später änderbar.', 'Lo entrante cae aquí; se puede cambiar después.', 'L’entrant arrive ici ; modifiable plus tard.', '들어온 항목이 이 분류로, 나중에 바꿀 수 있습니다.', 'O que entra cai aqui; pode mudar depois.', '取り込まれた項目はこの分類。後から変更可。'),
    'ui.interval_min' => $t('Intervall (Minuten)', 'Intervalo (minutos)', 'Intervalle (minutes)', '간격(분)', 'Intervalo (minutos)', '間隔（分）'),
    'ui.max_items_each' => $t('Max. Einträge pro Lauf', 'Máx. ítems por ejecución', 'Max. éléments par run', '실행당 최대 건수', 'Máx. itens por execução', '毎回の最大件数'),
    'ui.enable_with_schedule' => $t('Aktiv; läuft mit fälligen Sammeljobs', 'Activar; corre con recolectas vencidas', 'Activer ; suit les collectes dues', '사용, 기한 수집과 함께 실행', 'Ativar; corre com recolhas devidas', '有効。期限の収集と一緒に実行'),
    'ui.publish_vod' => $t('Sofort listen, wenn Play-URL da (erst prüfen)', 'Publicar al haber URL (revise primero)', 'Publier dès qu’il y a une URL (vérifier d’abord)', '재생주소 있으면 바로 공개(먼저 확인)', 'Publicar se houver URL (rever primeiro)', '再生URLがあれば即公開（先に確認）'),
    'ui.publish_vod_hint' => $t('Ohne m3u8 / mp4 / flv bleibt es off; Haken täuscht nicht.', 'Sin m3u8 / mp4 / flv sigue off; marcar no finge.', 'Sans m3u8 / mp4 / flv reste off ; cocher ne feint pas.', 'm3u8 / mp4 / flv 없으면 계속 비공개.', 'Sem m3u8 / mp4 / flv fica off; marcar não finge.', 'm3u8 / mp4 / flv がなければ下架のまま。'),
    'ui.how_html' => $t('Seite parsen', 'Cómo parsear la página', 'Comment parser la page', '페이지 추출 방법', 'Como analisar a página', 'ページの取り方'),
    'ui.html_how_hint' => $t('Rechtsklick Untersuchen; Tags je Listeneintrag. Häufig: article, li.item, h2 a.', 'Clic derecho Inspeccionar; etiquetas de cada ítem. Común: article, li.item, h2 a.', 'Clic droit Inspecter ; balises de chaque item. Courant : article, li.item, h2 a.', '검사에서 목록 각 항목 태그를 넣으세요. 흔한 예: article, li.item, h2 a.', 'Clique direito Inspecionar; tags de cada item. Comum: article, li.item, h2 a.', '検証で各一覧項目のタグを入れる。よくある例: article、li.item、h2 a。'),
    'ui.list_items' => $t('Listeneinträge', 'Ítems de lista', 'Entrées de liste', '목록 항목', 'Itens da lista', '一覧項目'),
    'ui.list_items_hint' => $t('Der Block um einen Eintrag, nicht die ganze Seite.', 'El bloque de un ítem, no toda la página.', 'Le bloc d’un item, pas toute la page.', '한 항목을 감싼 블록, 페이지 전체가 아님.', 'O bloco de um item, não a página toda.', '1件を囲むブロック。ページ全体ではない。'),
    'ui.title_link' => $t('Titel-Link', 'Enlace del título', 'Lien du titre', '제목 링크', 'Ligação do título', 'タイトルリンク'),
    'ui.title_link_hint' => $t('Relativ zum Eintrag oben. Standard: erster Link.', 'Relativo al ítem. Por defecto el primer enlace.', 'Relatif à l’item. Défaut : premier lien.', '위 항목 기준. 기본은 첫 링크.', 'Relativo ao item. Predefinição: primeira ligação.', '上の項目基準。既定は最初のリンク。'),
    'ui.title_optional' => $t('Titel (optional)', 'Título (opcional)', 'Titre (facultatif)', '제목(선택)', 'Título (opcional)', 'タイトル（任意）'),
    'ui.summary_optional' => $t('Kurztext (optional)', 'Resumen (opcional)', 'Résumé (facultatif)', '소개(선택)', 'Resumo (opcional)', '紹介（任意）'),
    'ui.cover_optional' => $t('Cover (optional)', 'Portada (opcional)', 'Couverture (facultatif)', '표지(선택)', 'Capa (opcional)', '表紙（任意）'),
    'ui.play_url_optional' => $t('Play-URL (optional)', 'URL de reproducción (opcional)', 'URL de lecture (facultatif)', '재생 주소(선택)', 'URL de reprodução (opcional)', '再生URL（任意）'),
    'ui.play_url_hint' => $t('m3u8 / mp4 in der Liste. Leer: Titel-Link als Play-URL. Unnötig für Artikel/Manga.', 'm3u8 / mp4 en la lista. Vacío: el título es la URL. No aplica a artículos/manga.', 'm3u8 / mp4 dans la liste. Vide : le lien titre. Inutile pour articles/manga.', '목록의 m3u8 / mp4. 비우면 제목 링크를 재생주소로. 기사·만화 불필요.', 'm3u8 / mp4 na lista. Vazio: o título é o URL. Inútil para artigos/manga.', '一覧の m3u8 / mp4。空ならタイトルリンクを再生URLに。記事・漫画は不要。'),
    'ui.detail_summary' => $t('Detail-Kurztext (optional)', 'Resumen de detalle (opcional)', 'Résumé détail (facultatif)', '상세 소개(선택)', 'Resumo de detalhe (opcional)', '詳細紹介（任意）'),
    'ui.detail_summary_hint' => $t('Dann jede URL fürs Excerpt, gleiche Site; Fallback Listenexcerpt.', 'Luego abre cada enlace; mismo sitio; si falla, el de lista.', 'Chaque lien est ouvert ; même site ; repli sur la liste.', '각 링크를 열어 소개. 같은 사이트. 실패 시 목록 소개.', 'Abre cada ligação; mesmo site; se falhar, o da lista.', '各リンクを開いて紹介。同一サイト。失敗時は一覧の紹介。'),
    'ui.paging' => $t('Blättern', 'Paginación', 'Pagination', '페이지', 'Paginação', 'ページ送り'),
    'ui.max_pages' => $t('Max. Seiten', 'Máx. páginas', 'Pages max', '최대 페이지', 'Máx. páginas', '最大ページ数'),
    'ui.max_pages_hint' => $t('1 = nur aktuelle Liste. Cap 10, um die ganze Site nicht zu crawlen.', '1 = solo esta lista. Tope 10 para no rastrear todo el sitio.', '1 = liste actuelle. Plafond 10 pour ne pas tout crawler.', '1은 현재 목록만. 최대 10페이지.', '1 = só esta lista. Teto 10 para não rastear o site.', '1は現在の一覧のみ。最大10ページ。'),
    'ui.page_url_opt' => $t('Seiten-URL (optional)', 'URL de página (opcional)', 'URL de page (facultatif)', '페이지 주소(선택)', 'URL de página (opcional)', 'ページURL（任意）'),
    'ui.page_url_hint' => $t('{page} für die Seitenzahl. Leer hängt page=2 an. Gleiche Site.', '{page} es el número. Vacío añade page=2. Mismo sitio.', '{page} = numéro. Vide ajoute page=2. Même site.', '{page}가 페이지 번호. 비우면 page=2. 같은 사이트.', '{page} é o número. Vazio acrescenta page=2. Mesmo site.', '{page} がページ番号。空なら page=2。同一サイト。'),
    'ui.next_btn' => $t('Weiter-Button (optional)', 'Botón siguiente (opcional)', 'Bouton suivant (facultatif)', '다음 버튼(선택)', 'Botão seguinte (opcional)', '次へボタン（任意）'),
    'ui.next_btn_hint' => $t('Dann den „Weiter“-Links folgen statt der Seiten-URL. Gleiche Site.', 'Sigue «siguiente» en vez de la URL de página. Mismo sitio.', 'Suit « suivant » au lieu de l’URL. Même site.', '페이지 URL 대신 「다음」링크. 같은 사이트.', 'Segue «seguinte» em vez do URL. Mesmo site.', 'ページURLではなく「次へ」リンク。同一サイト。'),
    'ui.api_fields' => $t('API-Felder', 'Campos de API', 'Champs d’API', 'API 필드', 'Campos de API', 'API フィールド'),
    'ui.list_path' => $t('Listenpfad', 'Ruta de lista', 'Chemin de liste', '목록 경로', 'Caminho da lista', '一覧パス'),
    'ui.list_path_hint' => $t('Wo die Liste sitzt. Wurzelarray ist .', 'Dónde está la lista. Array raíz: .', 'Où vit la liste. Tableau racine : .', '목록이 있는 층. 루트 배열은 .', 'Onde está a lista. Array raiz: .', '一覧の階層。ルート配列は .'),
    'ui.title_field' => $t('Titelfeld', 'Campo título', 'Champ titre', '제목 필드', 'Campo título', 'タイトルフィールド'),
    'ui.link_field' => $t('Linkfeld', 'Campo enlace', 'Champ lien', '링크 필드', 'Campo ligação', 'リンクフィールド'),
    'ui.summary_field' => $t('Kurztextfeld', 'Campo resumen', 'Champ résumé', '소개 필드', 'Campo resumo', '紹介フィールド'),
    'ui.content_field' => $t('Textfeld', 'Campo cuerpo', 'Champ corps', '본문 필드', 'Campo corpo', '本文フィールド'),
    'ui.guid_field' => $t('Dedup-Feld', 'Campo de duplicados', 'Champ dédup', '중복 제거 필드', 'Campo de duplicados', '重複排除フィールド'),
    'ui.cover_field' => $t('Cover-Feld', 'Campo portada', 'Champ couverture', '표지 필드', 'Campo capa', '表紙フィールド'),
    'ui.play_field' => $t('Play-URL-Feld', 'Campo URL de reproducción', 'Champ URL de lecture', '재생 주소 필드', 'Campo URL de reprodução', '再生URLフィールド'),
    'ui.play_field_hint' => $t('http(s) m3u8 / mp4. Sonst off-shelf. Ignoriert für Artikel/Manga.', 'http(s) m3u8 / mp4. Si no, off. Ignorado en artículos/manga.', 'http(s) m3u8 / mp4. Sin quoi, off. Ignoré pour articles/manga.', 'http(s) m3u8 / mp4. 아니면 비공개. 기사·만화는 무시.', 'http(s) m3u8 / mp4. Senão fica off. Ignorado em artigos/manga.', 'http(s) の m3u8 / mp4。合わなければ下架。記事・漫画は無視。'),
    'ui.try_fetch' => $t('Testabruf', 'Probar captura', 'Essai de collecte', '시험 수집', 'Testar recolha', '試抓'),
    'ui.recent_runs' => $t('Letzte Läufe', 'Ejecuciones recientes', 'Derniers runs', '최근 실행', 'Execuções recentes', '最近の実行'),
    'ui.result' => $t('Ergebnis', 'Resultado', 'Résultat', '결과', 'Resultado', '結果'),
    'ui.note_col' => $t('Hinweis', 'Nota', 'Note', '설명', 'Nota', '説明'),
    'ui.ph_search_cj_logs' => $t('Hinweis oder Regel-ID', 'Notas o ID de regla', 'Notes ou n° de règle', '설명·규칙 번호 검색', 'Notas ou ID da regra', '説明・ルール番号を検索'),
    'ui.ph_search_cj' => $t('Name oder URL', 'Nombre o URL', 'Nom ou URL', '이름·주소 검색', 'Nome ou URL', '名前・URL を検索'),
    'ui.method_aria' => $t('Methode', 'Método', 'Méthode', '방식', 'Método', '方式'),
    'ui.fetching' => $t('Abruf…', 'Capturando…', 'Collecte…', '수집 중…', 'A recolher…', '取得中…'),
    'ui.try_fetch_fail' => $t('Testabruf fehlgeschlagen', 'Falló la captura de prueba', 'Échec de l’essai', '시험 수집 실패', 'Falha na recolha de teste', '試抓に失敗'),
    'ui.try_fetch_fail_hint' => $t('Testabruf fehlgeschlagen. URL und Selektoren prüfen.', 'Falló. Revise URL y selectores.', 'Échec. Vérifiez URL et sélecteurs.', '실패. 주소와 선택자를 확인하세요.', 'Falhou. Verifique URL e seletores.', '失敗。URL とセレクタを確認。'),
    'ui.untitled' => $t('Ohne Titel', 'Sin título', 'Sans titre', '제목 없음', 'Sem título', '無題'),
    'ui.empty_cj_logs' => $t('Noch keine Läufe', 'Aún no hay ejecuciones', 'Pas encore d’exécutions', '아직 실행 기록이 없습니다', 'Ainda sem execuções', 'まだ実行記録がありません'),
    'ui.empty_cj_logs_hint' => $t('Nach dem Speichern „Jetzt sammeln“; jeder Pull landet hier.', 'Tras guardar, Recolectar ahora; cada tirada queda aquí.', 'Après enregistrement, Collecter ; chaque tirage est ici.', '저장 후 즉시 수집을 누르면 여기에 기록.', 'Depois de guardar, Recolher agora; cada puxada fica aqui.', '保存後に「今すぐ収集」。各回がここに残ります。'),
    'ui.empty_cj' => $t('Noch keine Website-Sammlungen', 'Aún no hay recolecciones web', 'Pas encore de collectes web', '아직 사이트 수집이 없습니다', 'Ainda sem recolhas web', 'まだサイト収集がありません'),
    'ui.empty_cj_hint' => $t('Von Seiten, RSS oder APIs in Videos, Artikel oder Manga. Erst Testabruf.', 'Desde páginas, RSS o APIs. Pruebe primero, luego active.', 'Depuis pages, RSS ou API. Essayez d’abord.', '페이지·RSS·API에서 가져옵니다. 먼저 시험 수집.', 'De páginas, RSS ou APIs. Teste primeiro.', 'ページ・RSS・API から取り込み。先に試抓。'),
    'ui.collect_source_col' => $t('Sammelquelle', 'Fuente', 'Source', '수집원', 'Fonte', '収集源'),
    'ui.every_n_min_max' => $t('Alle :min Min. · bis :n je Lauf', 'Cada :min min · hasta :n por run', 'Toutes les :min min · jusqu’à :n', '매 :min분 · 회당 최대 :n건', 'A cada :min min · até :n', ':min 分ごと · 毎回最大 :n 件'),
    'ui.write_col' => $t('Ziel', 'Destino', 'Cible', '기록', 'Destino', '書き込み'),
    'ui.last_run' => $t('Zuletzt', 'Última', 'Dernier', '지난번', 'Última', '前回'),
    'ui.last_fail' => $t('Letzter Lauf fehlgeschlagen', 'Falló la última ejecución', 'Dernier run en échec', '지난번 실패', 'Última execução falhou', '前回失敗'),
    'ui.collect_now' => $t('Jetzt sammeln', 'Recolectar ahora', 'Collecter maintenant', '즉시 수집', 'Recolher agora', '今すぐ収集'),
    'ui.confirm_del_cj' => $t('„:name“ löschen? Bereits eingeholtes bleibt.', '¿Borrar «:name»? Lo ya ingerido se queda.', 'Supprimer « :name » ? Le déjà collecté reste.', '「:name」을 삭제할까요? 이미 들어온 내용은 남습니다.', 'Apagar «:name»? O já ingerido fica.', '「:name」を削除しますか？取り込み済みは残ります。'),
    'ui.rss_url' => $t('Feed-URL', 'URL del feed', 'URL du flux', '구독 주소', 'URL do feed', 'フィードURL'),
    'ui.rss_url_hint' => $t('Öffentliche RSS-/Atom-URL, z. B. https://example.com/feed.xml', 'URL RSS / Atom pública, p. ej. https://example.com/feed.xml', 'URL RSS / Atom publique, ex. https://example.com/feed.xml', '공개 RSS / Atom, 예: https://example.com/feed.xml', 'URL RSS / Atom pública, ex. https://example.com/feed.xml', '公開 RSS / Atom。例: https://example.com/feed.xml'),
    'ui.json_url' => $t('API-URL', 'URL de API', 'URL d’API', 'API 주소', 'URL da API', 'API URL'),
    'ui.json_url_hint' => $t('JSON-URL mit Liste. Titel und Link per Feldname unten.', 'URL JSON de lista. Título y enlace por los campos abajo.', 'URL JSON de liste. Titre et lien via les champs ci-dessous.', '목록 JSON 주소. 아래 필드명으로 제목·링크.', 'URL JSON da lista. Título e ligação pelos campos abaixo.', '一覧を返す JSON。下のフィールド名でタイトルとリンク。'),
    'ui.publish_art' => $t('Artikel sofort publizieren (Text prüfen)', 'Publicar artículos al instante (revise el cuerpo)', 'Publier les articles tout de suite (relire)', '기사 바로 공개(본문 확인)', 'Publicar artigos já (rever o corpo)', '記事を即公開（本文を確認）'),
    'ui.publish_art_hint' => $t('Artikel haben keine Play-URL. Ungehakt bleibt unveröffentlicht.', 'Los artículos no tienen URL. Sin marca quedan sin publicar.', 'Pas d’URL de lecture. Décoché = non publié.', '기사엔 재생주소가 없음. 체크 안하면 미발행.', 'Artigos não têm URL. Desmarcado fica por publicar.', '記事に再生URLはありません。未チェックは未公開。'),
    'ui.publish_manga' => $t('Werke sofort listen (prüfen)', 'Listar obras al instante (revise)', 'Lister les œuvres tout de suite (vérifier)', '작품 바로 공개(확인)', 'Listar obras já (rever)', '作品を即公開（確認）'),
    'ui.publish_manga_hint' => $t('Legt nur Manga-Werke an; erfindet keine Kapitel/Bilder.', 'Solo crea obras; no inventa capítulos ni imágenes.', 'Crée seulement des œuvres ; n’invente pas chapitres/images.', '만화 작품만 만듭니다. 챕터·이미지를 지어내지 않습니다.', 'Só cria obras; não inventa capítulos nem imagens.', '漫画作品のみ作成。章や画像は捏造しません。'),
    'ui.cat_hint_vod' => $t('Eingehende Videos in diese Kategorie; später änderbar.', 'Los vídeos caen aquí; se pueden cambiar luego.', 'Les vidéos arrivent ici ; modifiable ensuite.', '들어온 영상은 이 분류, 나중에 변경 가능.', 'Os vídeos caem aqui; pode mudar depois.', '取り込んだ動画はこの分類。後から変更可。'),
    'ui.cat_hint_art' => $t('Eingehende Artikel in diese Kategorie.', 'Los artículos caen en esta categoría.', 'Les articles arrivent dans cette catégorie.', '들어온 기사는 이 분류.', 'Os artigos caem nesta categoria.', '取り込んだ記事はこの分類。'),
    'ui.cat_hint_manga' => $t('Eingehende Werke in diese Manga-Kategorie.', 'Las obras caen en esta categoría manga.', 'Les œuvres arrivent dans cette catégorie manga.', '들어온 작품은 이 만화 분류.', 'As obras caem nesta categoria manga.', '取り込んだ作品はこの漫画分類。'),
    'ui.name_list_hint' => $t('Name in der Admin-Liste.', 'Nombre en la lista admin.', 'Nom dans la liste admin.', '관리 목록에 보이는 이름.', 'Nome na lista admin.', '管理一覧に出る名前。'),
    'ui.edit_video' => $t('Video bearbeiten', 'Editar vídeo', 'Modifier la vidéo', '영상 편집', 'Editar vídeo', '動画を編集'),
    'ui.back_list' => $t('Zurück zur Liste', 'Volver a la lista', 'Retour à la liste', '목록으로', 'Voltar à lista', '一覧へ戻る'),
    'ui.play_lines' => $t('Wiedergabelinien', 'Líneas de reproducción', 'Lignes de lecture', '재생 회선', 'Linhas de reprodução', '再生回線'),
    'ui.video_form_lead_edit' => $t('Metadaten ändern die Play-URLs nicht. Linien rechts unter „Wiedergabelinien“.', 'Guardar ficha no cambia URLs. Añada líneas en «Líneas de reproducción».', 'Les métadonnées ne touchent pas aux URL. Lignes sous « Lignes de lecture ».', '자료 저장은 재생주소를 바꾸지 않습니다. 회선은 「재생 회선」.', 'Guardar ficha não muda URLs. Linhas em «Linhas de reprodução».', '資料保存は再生URLを変えません。回線は「再生回線」で追加。'),
    'ui.video_form_lead_new' => $t(
        'Titel ist Pflicht. Ohne Play-URL zuerst als Entwurf speichern, dann Wiedergabelinien ergänzen.',
        'El título es obligatorio. Sin URL, guarde primero como borrador y luego añada líneas de reproducción.',
        'Le titre est obligatoire. Sans URL, enregistrez d’abord en brouillon, puis ajoutez des lignes de lecture.',
        '제목은 필수. 재생주소가 없으면 먼저 초안으로 저장한 뒤 재생 회선을 추가.',
        'O título é obrigatório. Sem URL, grave primeiro como rascunho e depois adicione linhas de reprodução.',
        'タイトルは必須。再生URLがなければ先に下書き保存し、あとで再生回線を足す。'
    ),
    'ui.this_title' => $t('Dieser Titel', 'Este título', 'Ce titre', '이 작품', 'Este título', 'この作品'),
    'ui.ph_front_name' => $t('Name auf Liste und Play-Seite', 'Nombre en lista y página de play', 'Nom sur liste et page lecture', '목록·재생 페이지의 이름', 'Nome na lista e página de play', '一覧と再生ページの名前'),
    'ui.ph_subtitle' => $t('Optional, z. B. engl. Name', 'Opcional, p. ej. nombre en inglés', 'Facultatif, ex. nom anglais', '선택, 예: 영문명', 'Opcional, ex. nome em inglês', '任意。例: 英語名'),
    'ui.pick_later' => $t('Später wählen', 'Elegir después', 'Choisir plus tard', '나중에 선택', 'Escolher depois', 'あとで選ぶ'),
    'ui.empty_types_hint' => $t('Noch keine Kategorien. Erst eine anlegen; Besucher browsen danach.', 'Aún no hay categorías. Cree una; los visitantes filtran así.', 'Pas encore de catégories. Créez-en une ; le site filtre ainsi.', '아직 분류가 없습니다. 먼저 만드세요.', 'Ainda sem categorias. Crie uma; os visitantes filtram assim.', 'まだ分類がありません。先に作成。'),
    'ui.types_hint' => $t('Filme und Serien getrennt. Mehr unter Kategorien.', 'Separe cine y series. Añada más en Categorías.', 'Films et séries à part. Plus sous Catégories.', '영화와 드라마는 따로. 분류에서 추가.', 'Separe filmes e séries. Mais em Categorias.', '映画とドラマは分ける。分類で追加。'),
    'ui.ph_remarks' => $t('z. B. bis Folge 12, abgeschlossen', 'p. ej. actualizado a ep. 12, completo', 'ex. à l’ép. 12, terminé', '예: 12화까지, 완결', 'ex. atualizado ao ep. 12, completo', '例: 12話まで、完結'),
    'ui.remarks_hint' => $t('Steht in Listen, damit Gäste den Stand sehen.', 'Sale en listas para indicar hasta dónde va.', 'S’affiche en liste pour le point d’avancement.', '목록에 나와 진행을 알립니다.', 'Aparece nas listas para o progresso.', '一覧に出て進捗を知らせます。'),
    'ui.poster' => $t('Poster', 'Póster', 'Affiche', '포스터', 'Poster', 'ポスター'),
    'ui.no_poster' => $t('Noch kein Poster', 'Aún no hay póster', 'Pas encore d’affiche', '아직 포스터 없음', 'Ainda sem poster', 'まだポスターがありません'),
    'ui.ph_image_or_upload' => $t('Bild-URL oder Upload', 'URL de imagen, o subir', 'URL d’image, ou envoi', '이미지 주소 또는 업로드', 'URL da imagem, ou carregar', '画像URL、またはアップロード'),
    'ui.poster_hint' => $t('Hochformat für Liste und Detail. Leer markiert „kein Cover“.', 'Vertical para lista y ficha. Vacío marca «sin portada».', 'Portrait pour liste et fiche. Vide = « sans couverture ».', '세로 그림. 없으면 목록에 「표지 없음」.', 'Vertical para lista e ficha. Vazio marca «sem capa».', '縦長。空なら一覧に「表紙なし」。'),
    'ui.banner' => $t('Banner', 'Banner', 'Bannière', '배너', 'Faixa', 'バナー'),
    'ui.ph_banner' => $t('Breites Bild, optional', 'Imagen ancha, opcional', 'Image large, facultatif', '가로 이미지, 선택', 'Imagem larga, opcional', '横長画像、任意'),
    'ui.banner_hint' => $t('Home-Hero. Ohne Banner nur das Poster.', 'Hero de inicio. Sin él, solo el póster.', 'Hero d’accueil. Sans, seulement l’affiche.', '홈 큰 그림. 없으면 포스터만.', 'Hero da home. Sem ele, só o poster.', 'ホーム大画像。なければポスターのみ。'),
    'ui.meta_block' => $t('Angaben', 'Ficha', 'Fiche', '자료', 'Ficha', '資料'),
    'ui.year' => $t('Jahr', 'Año', 'Année', '연도', 'Ano', '年'),
    'ui.ph_area' => $t('z. B. Festland', 'p. ej. continental', 'ex. continent', '예: 대륙', 'ex. continental', '例: 大陸'),
    'ui.lang_label' => $t('Sprache', 'Idioma', 'Langue', '언어', 'Língua', '言語'),
    'ui.ph_lang' => $t('z. B. Mandarin', 'p. ej. mandarín', 'ex. mandarin', '예: 국어', 'ex. mandarim', '例: 普通話'),
    'ui.weekday' => $t('Update-Tage', 'Días de actualización', 'Jours de mise à jour', '업데이트 주기', 'Dias de atualização', '更新曜日'),
    'ui.ph_weekday_csv' => $t('Mo,Mi,Fr', 'lun,mié,vie', 'lun,mer,ven', '월,수,금', 'seg,qua,sex', '月,水,金'),
    'ui.meta_filter_hint' => $t('Region, Sprache, Jahr speisen Kategoriefilter. Lexikon in Site-Einstellungen → Mehr.', 'Región, idioma y año alimentan filtros. Léxico en Ajustes → Más.', 'Région, langue, année alimentent les filtres. Lexique dans Réglages → Plus.', '지역·언어·연도는 분류 필터. 사전은 사이트 설정 → 더보기.', 'Região, língua e ano alimentam filtros. Léxico em Definições → Mais.', '地域・言語・年は分類フィルタ。語彙はサイト設定 → その他。'),
    'ui.class_words' => $t('Genre-Wörter', 'Palabras de género', 'Mots de genre', '유형어', 'Palavras de género', 'ジャンル語'),
    'ui.ph_class_words' => $t('Kommagetrennt, z. B. Komödie,Action', 'Separadas por coma, p. ej. Comedia,Acción', 'Séparés par virgule, ex. Comédie,Action', '쉼표로 구분, 예: 코미디,액션', 'Separadas por vírgula, ex. Comédia,Ação', 'カンマ区切り。例: コメディ,アクション'),
    'ui.class_words_hint' => $t('Für den Genre-Filter, nicht den Kategoriebaum. Lexikon unter Genrefilter. Tags separat.', 'Para el filtro Género, no el árbol. Léxico en Filtros. Tags aparte.', 'Pour le filtre Genre, pas l’arbre. Lexique sous Filtres. Tags à part.', '분류 페이지 「유형」필터용, 카테고리 트리가 아님. 태그는 별개.', 'Para o filtro Género, não a árvore. Léxico em Filtros. Tags à parte.', '分類ページのジャンル絞り。欄ではない。タグは別。'),
    'ui.director' => $t('Regie', 'Director', 'Réalisateur', '감독', 'Realizador', '監督'),
    'ui.starring' => $t('Besetzung', 'Protagonistas', 'Distribution', '주연', 'Elenco', '主演'),
    'ui.ph_actors' => $t('Kommagetrennt, z. B. Anna,Jan', 'Separados por coma, p. ej. Ana,Juan', 'Séparés par virgule, ex. Anne,Jean', '쉼표로 구분, 예: 홍길동,이몽룡', 'Separados por vírgula, ex. Ana,João', 'カンマ区切り。例: 山田,佐藤'),
    'ui.actors_save_hint' => $t('Speichern schreibt ins Darstellerarchiv.', 'Al guardar se escribe en el archivo de actores.', 'L’enregistrement écrit dans la bibliothèque acteurs.', '저장 시 배우 라이브러리에 기록.', 'Ao gravar escreve na biblioteca de atores.', '保存時に俳優庫へ書きます。'),
    'ui.ph_tags' => $t('Kommagetrennt, z. B. Neujahr,Highscore', 'Separadas por coma, p. ej. Año nuevo,Alta nota', 'Séparés par virgule, ex. Nouvel an,Note haute', '쉼표로 구분, 예: 설날,고득점', 'Separadas por vírgula, ex. Ano novo,Nota alta', 'カンマ区切り。例: 正月,高得点'),
    'ui.tags_save_hint' => $t('Sammelbegriffe für Tags. Komödie/Action gehören zu Genre-Wörtern.', 'Palabras de agregación a Tags. Comedia/Acción van en género.', 'Mots d’agrégat vers Tags. Comédie/Action = genre.', '집계어는 태그. 코미디/액션은 유형어.', 'Palavras de agregação para Tags. Comédia/Ação vão em género.', '集約語はタグへ。コメディ/アクションはジャンル語。'),
    'ui.synopsis' => $t('Kurzinhalt', 'Sinopsis', 'Synopsis', '소개', 'Sinopse', 'あらすじ'),
    'ui.plot_label' => $t('Handlung', 'Trama', 'Intrigue', '줄거리', 'Enredo', 'あらすじ'),
    'ui.ph_plot' => $t('Ein, zwei Absätze — nicht das ganze Skript', 'Uno o dos párrafos, no el guion entero', 'Un ou deux paragraphes, pas tout le script', '한두 단락, 대본 전부는 아님', 'Um ou dois parágrafos, não o guião todo', '1〜2段落。台本全部は不要'),
    'ui.no_roles_hint' => $t('Noch keine Rollen. Im Rollenarchiv Charaktere für diesen Titel anlegen.', 'Aún no hay roles. Añada nombres en la biblioteca de roles.', 'Pas encore de rôles. Ajoutez des noms dans la bibliothèque.', '아직 역할이 없습니다. 역할 라이브러리에서 추가.', 'Ainda sem papéis. Adicione nomes na biblioteca de papéis.', 'まだ役割がありません。役割庫で追加。'),
    'ui.roles_edit_hint' => $t('Im Rollenarchiv ändern. Die Detailseite listet aktive Rollen.', 'Edite en la biblioteca. La ficha lista los activos.', 'Modifiez dans la bibliothèque. La fiche liste les actifs.', '역할 라이브러리에서 수정. 상세는 사용 중인 것만.', 'Edite na biblioteca. A ficha lista os ativos.', '役割庫で変更。詳細は有効なもののみ。'),
    'ui.no_plots_hint' => $t('Noch keine Folgenhandlungen. Unter Folgenhandlungen schreiben. Die Gesamtsynopsis ist oben.', 'Aún no hay tramas por episodio. Escríbalas en Tramas. La sinopsis global está arriba.', 'Pas encore de synopses d’épisode. Écrivez-les dans Synopses. La globale est au-dessus.', '아직 회차별 줄거리가 없습니다. 회차 줄거리에서 작성. 전체 소개는 위.', 'Ainda sem enredos por episódio. Escreva em Enredos. A sinopse global está acima.', 'まだ話ごとのあらすじがありません。分集劇情で書く。全体紹介は上。'),
    'ui.plots_edit_hint' => $t('Unter Folgenhandlungen ändern. Nicht aus Play-URLs erzeugt.', 'Edite en Tramas. No se genera desde URLs.', 'Modifiez dans Synopses. Pas généré depuis les URL.', '회차 줄거리에서 수정. 재생주소에서 자동 생성되지 않음.', 'Edite em Enredos. Não é gerado a partir de URLs.', '分集劇情で変更。再生URLから自動生成しません。'),
    'ui.episode_n' => $t('F. :n', 'Ep. :n', 'Ép. :n', ':n화', 'Ep. :n', '第:n話'),
    'ui.listing' => $t('Veröffentlichung', 'Publicación', 'Publication', '공개', 'Publicação', '公開'),
    'ui.draft_hidden' => $t('Entwurf (auf der Site unsichtbar)', 'Borrador (oculto en el sitio)', 'Brouillon (invisible sur le site)', '초안(사이트에 안 보임)', 'Rascunho (oculto no site)', '下書き（サイトに出ない）'),
    'ui.schedule_publish' => $t('Zeitplanen', 'Programar', 'Planifier', '예약 공개', 'Agendar', '予約公開'),
    'ui.publish_at' => $t('Veröffentlichen um', 'Publicar a las', 'Publier à', '공개 시각', 'Publicar às', '公開日時'),
    'ui.publish_at_hint' => $t('Wechselt zur Listung zu dieser Zeit (Serverzeitzone).', 'Pasa a publicado a esta hora (zona del servidor).', 'Passe en publié à cette heure (fuseau serveur).', '이 시각에 공개로 바뀝니다. 서버 시간대.', 'Passa a publicado nesta hora (fuso do servidor).', 'この時刻に公開へ。サーバー時区。'),
    'ui.vod_points' => $t('VOD-Punkte', 'Puntos VOD', 'Points VOD', 'VOD 포인트', 'Pontos VOD', '点播ポイント'),
    'ui.vod_points_hint' => $t('0 ist frei. Gruppen können überschreiben.', '0 es gratis. Los grupos pueden anular.', '0 = gratuit. Les groupes peuvent outrepasser.', '0은 무료. 회원 그룹에서 따로 설정 가능.', '0 é grátis. Os grupos podem substituir.', '0 は無料。会員グループで上書き可。'),
    'ui.score' => $t('Bewertung', 'Puntuación', 'Note', '평점', 'Pontuação', '評点'),
    'ui.sort_desc_hint' => $t('Höher steht vorn. Meist unverändert lassen.', 'Más alto va primero. Suele no tocarse.', 'Plus haut = plus haut. Souvent inchangé.', '숫자가 클수록 앞. 보통 그대로.', 'Mais alto vai primeiro. Costuma não se mexer.', '大きいほど前。通常はそのまま。'),
    'ui.rec_home' => $t('Auf der Startseite empfehlen', 'Recomendar en inicio', 'Recommander en accueil', '홈에 추천', 'Recomendar na home', 'ホームに推薦'),
    'ui.mark_hot' => $t('Als heiß markieren', 'Marcar como popular', 'Marquer comme populaire', '인기로 표시', 'Marcar como popular', '人気にする'),
    'ui.lock_collect' => $t('Sperren, damit Sammeln nicht überschreibt', 'Bloquear para que la recolección no pise', 'Verrouiller pour que la collecte n’écrase pas', '잠그기, 수집이 덮어쓰지 않음', 'Bloquear para a recolha não substituir', 'ロック。収集で上書きしない'),
    'ui.collect_match' => $t('Sammelabgleich', 'Correspondencia de recolección', 'Correspondance de collecte', '수집 대조', 'Correspondência de recolha', '収集対照'),
    'ui.collect_match_hint' => $t('Meist leer bei Handanlage. Matching vermeidet Duplikate.', 'Suele vacío en altas manuales. El match evita duplicados.', 'Souvent vide en saisie manuelle. Le match évite les doublons.', '수동 추가는 보통 비움. 맞으면 중복 삽입 안 함.', 'Costuma vazio em altas manuais. O match evita duplicados.', '手動追加は空でよい。一致すれば重複挿入しない。'),
    'ui.collect_source' => $t('Sammelquelle', 'Fuente de recolección', 'Source de collecte', '수집원', 'Fonte de recolha', '収集源'),
    'ui.none_opt' => $t('Keine', 'Ninguna', 'Aucune', '없음', 'Nenhuma', 'なし'),
    'ui.stopped_paren' => $t('(aus)', '(apagado)', '(off)', '(중지)', '(desligado)', '（停止）'),
    'ui.collect_id' => $t('Sammel-ID', 'ID de recolección', 'ID de collecte', '수집 ID', 'ID de recolha', '収集 ID'),
    'ui.save_and_add_play' => $t('Speichern und Wiedergabe-URLs hinzufügen', 'Guardar y añadir reproducción', 'Enregistrer et ajouter la lecture', '저장하고 재생주소 추가', 'Guardar e adicionar reprodução', '保存して再生アドレスを追加'),
    'ui.go_create_type' => $t('Zuerst eine anlegen', 'Cree una primero', 'Créez-en une d’abord', '먼저 하나 만들기', 'Crie uma primeiro', '先に作成'),
    'ui.add_action' => $t('Hinzufügen', 'Añadir', 'Ajouter', '추가', 'Adicionar', '追加'),
    'ui.cj_try_ok' => $t(':n Einträge geholt; nichts geschrieben.', 'Traídos :n; nada escrito.', ':n éléments lus ; rien écrit.', ':n건 가져옴. 라이브러리에 안 씀.', 'Obtidos :n; nada escrito.', ':n 件取得。ライブラリ未書き込み。'),
    'ui.dict_lead' => $t('Optionen nach Typ. Region, Sprache, Jahr erscheinen im Filter, wenn aktiv.', 'Opciones por tipo. Área, idioma y año salen en filtros si están activos.', 'Options par type. Région, langue, année dans les filtres si actifs.', '유형별 옵션. 지역·언어·연도는 켜면 필터에 나옵니다.', 'Opções por tipo. Área, língua e ano saem nos filtros se ativos.', '種類ごとの選択肢。地域・言語・年は有効ならフィルタに出ます。'),
    'ui.dict_add' => $t('Wörterbuch hinzufügen', 'Añadir diccionario', 'Ajouter au lexique', '사전 추가', 'Adicionar dicionário', '辞書を追加'),
    'ui.vt_string' => $t('Zeichenkette', 'Cadena', 'Chaîne', '문자열', 'Cadeia', '文字列'),
    'ui.vt_json_obj' => $t('JSON-Objekt', 'Objeto JSON', 'Objet JSON', 'JSON객체', 'Objeto JSON', 'JSONオブジェクト'),
    'ui.vt_json_arr' => $t('JSON-Array', 'Array JSON', 'Tableau JSON', 'JSON배열', 'Array JSON', 'JSON配列'),
    'ui.vt_enum' => $t('Enum', 'Enum', 'Énum', '열거', 'Enum', '列挙'),
    'ui.vt_html' => $t('Rich-Text', 'Texto enriquecido', 'Texte riche', '리치 텍스트', 'Texto rico', 'リッチテキスト'),
    'ui.dict_value_cfg' => $t('Wert', 'Valor', 'Valeur', '사전 값', 'Valor', '辞書値'),
    'ui.make_opt' => $t('Generieren', 'Generar', 'Générer', '생성 옵션', 'Gerar', '生成オプション'),
    'ui.disk_static' => $t('Statische Disk-Seiten', 'Páginas estáticas en disco', 'Pages statiques disque', '디스크 정적 페이지', 'Páginas estáticas em disco', 'ディスク静的ページ'),
    'ui.enable_disk_html' => $t('Aktiv; statische Dateien im Admin erzeugen', 'Activar generación de estáticos en admin', 'Activer la génération de fichiers statiques', '관리에서 정적 파일 생성 허용', 'Ativar geração de estáticos no admin', '管理画面で静的ファイル生成を許可'),
    'ui.vod_types' => $t('Video-Kategorien', 'Categorías de vídeo', 'Catégories vidéo', '영상 분류', 'Categorias de vídeo', '動画分類'),
    'ui.make_all_cats' => $t('Alle Kategorien', 'Todas las categorías', 'Toutes les catégories', '전체 분류', 'Todas as categorias', '全分類'),
    'ui.today_content' => $t('Heutige Titel', 'Contenido de hoy', 'Contenu du jour', '오늘 내용', 'Conteúdo de hoje', '当日の内容'),
    'ui.one_click_today' => $t('Heute in einem Klick', 'Hoy en un clic', 'Aujourd’hui en un clic', '원클릭 당일', 'Hoje num clique', 'ワンクリック当日'),
    'ui.home_not_wap' => $t('Listen-Home, kein WAP.', 'Home de lista, no WAP.', 'Accueil liste, pas WAP.', '목록 홈, WAP 아님.', 'Home da lista, sem WAP.', '一覧ホーム。WAPではありません。'),
    'ui.gen_home' => $t('Home erzeugen', 'Generar inicio', 'Générer l’accueil', '홈 생성', 'Gerar início', 'ホーム生成'),
    'ui.gen_map' => $t('Karte erzeugen', 'Generar mapa', 'Générer la carte', '지도 생성', 'Gerar mapa', '地図生成'),
    'ui.gen_rss' => $t('RSS erzeugen', 'Generar RSS', 'Générer le RSS', 'RSS 생성', 'Gerar RSS', 'RSS 生成'),
    'ui.page_cache' => $t('Ganzseiten-Cache', 'Caché de página', 'Cache pleine page', '전체 페이지 캐시', 'Cache de página', '全ページキャッシュ'),
    'ui.enable_page_cache' => $t('Aktiv; Besucher sehen die erzeugte Seite', 'Activar; los visitantes ven la página generada', 'Activer ; les visiteurs voient la page générée', '사용, 방문자는 생성된 페이지를 봄', 'Ativar; os visitantes veem a página gerada', '有効。訪問者は生成済みページを見る'),
    'ui.keep_how_long' => $t('Aufbewahren', 'Conservar', 'Conserver', '보관 기간', 'Guardar durante', '保存期間'),
    'ui.ttl_now' => $t('Sofort nach Inhaltsänderung', 'En cuanto cambie el contenido', 'Dès que le contenu change', '내용 바뀌면 바로 갱신', 'Assim que o conteúdo mudar', '内容変更ですぐ更新'),
    'ui.warm_common' => $t('Häufige Seiten vorwärmen', 'Precalentar páginas comunes', 'Préchauffer les pages courantes', '자주 쓰는 페이지 예열', 'Aquecer páginas comuns', 'よく使うページを予熱'),
    'ui.clear_cached' => $t('Gespeicherte Seiten leeren', 'Vaciar páginas guardadas', 'Vider les pages stockées', '저장된 페이지 비우기', 'Limpar páginas guardadas', '保存ページを空にする'),
    'ui.please_select' => $t('Bitte zuerst ankreuzen', 'Marque primero', 'Cochez d’abord', '먼저 선택하세요', 'Marque primeiro', '先にチェック'),
    'ui.spider_pv_today' => $t('Spider-PV heute', 'PV de spiders hoy', 'PV spiders aujourd’hui', '오늘 스파이더 PV', 'PV de spiders hoje', '今日のスパイダー PV'),
    'ui.dict_value' => $t('Wörterbuchwert', 'Valor de diccionario', 'Valeur du lexique', '사전 값', 'Valor do dicionário', '辞書値'),
    'ui.need_role_name' => $t('Rollenname fehlt', 'Falta el nombre del rol', 'Nom du rôle manquant', '역할 이름을 입력하세요', 'Indique o nome do papel', '役割名を入力してください'),
    'ui.please_select_roles' => $t('Zuerst Rollen wählen', 'Seleccione roles primero', 'Sélectionnez d’abord des rôles', '먼저 역할을 선택하세요', 'Selecione papéis primeiro', '先に役割を選んでください'),
    'ui.confirm_del_roles' => $t('Gewählte Rollen löschen?', '¿Borrar los roles seleccionados?', 'Supprimer les rôles cochés ?', '선택한 역할을 삭제할까요?', 'Apagar os papéis selecionados?', '選んだ役割を削除しますか？'),
    'ui.confirm_del_role' => $t('Rolle „:name“ löschen?', '¿Borrar el rol «:name»?', 'Supprimer le rôle « :name » ?', '역할 「:name」을 삭제할까요?', 'Apagar o papel «:name»?', '役割「:name」を削除しますか？'),
    'ui.batch_gen' => $t('Stapel erzeugen', 'Generar en lote', 'Générer en lot', '일괄 생성', 'Gerar em lote', '一括生成'),
    'ui.run_due_collect' => $t('Fällige Sammlung ausführen', 'Ejecutar recolecciones vencidas', 'Lancer les collectes dues', '만기 수집 실행', 'Executar recolhas devidas', '期限の収集を実行'),
    'ui.run_job' => $t('Ausführen', 'Ejecutar', 'Exécuter', '실행', 'Executar', '実行'),
    'ui.import_in' => $t('Einlesen', 'Ingresar', 'Ingérer', '입고', 'Ingerir', '取り込み'),
    'ui.offline_fail_line' => $t('Leitung offline', 'Línea fuera', 'Ligne hors ligne', '회선 내리기', 'Linha offline', '回線を停止'),
    'ui.prompt_invite_gen' => $t('Anzahl,Punkte,Mitglieds-ID', 'Cantidad,puntos,ID de miembro', 'Nombre,points,ID membre', '수량,포인트,회원ID', 'Quantidade,pontos,ID membro', '数量,ポイント,会員ID'),
    'ui.prompt_card_gen' => $t('Anzahl,Punkte', 'Cantidad,puntos', 'Nombre,points', '수량,포인트', 'Quantidade,pontos', '数量,ポイント'),
    'ui.prompt_video_ids' => $t('Video-IDs, kommagetrennt', 'IDs de vídeo, separados por coma', 'IDs vidéo, séparés par virgule', '영상 ID, 쉼표 구분', 'IDs de vídeo, separados por vírgula', '動画ID、カンマ区切り'),
    'ui.try_run_n' => $t('Probelauf :n', 'Prueba :n', 'Essai :n', '시험 :n건', 'Ensaio :n', '試行 :n 件'),
    'ui.confirm_cj_import' => $t('Nach dieser Regel einlesen? Gleichnamige Titel werden übersprungen.', '¿Ingresar con esta regla? Se omiten títulos del mismo nombre.', 'Ingérer selon cette règle ? Les titres homonymes sont ignorés.', '이 규칙으로 입고할까요? 같은 제목은 건너뜁니다.', 'Ingerir com esta regra? Títulos iguais são saltados.', 'この規則で取り込みますか？同名は飛ばします。'),
    'ui.confirm_offline_fail' => $t('Die verknüpfte Wiedergabeleitung offline nehmen?', '¿Poner fuera la línea de reproducción vinculada?', 'Mettre hors ligne la ligne de lecture liée ?', '연결된 재생 회선을 내릴까요?', 'Colocar offline a linha de reprodução ligada?', '紐づいた再生回線を停止しますか？'),
    'ui.confirm_del_simple' => $t('Diesen Eintrag löschen?', '¿Borrar esta fila?', 'Supprimer cette ligne ?', '이 행을 삭제할까요?', 'Apagar esta linha?', 'この行を削除しますか？'),
    'ui.ph_jump_url' => $t('https:// oder /arts', 'https:// o /arts', 'https:// ou /arts', 'https:// 또는 /arts', 'https:// ou /arts', 'https:// または /arts'),
    'ui.publish_default_title' => $t('Adressseite', 'Página de direcciones', 'Page d’adresses', '주소 공개 페이지', 'Página de endereços', 'アドレス公開ページ'),
    'ui.sc_todo' => $t('Zu erledigen', 'Por hacer', 'À traiter', '처리할 일', 'Por fazer', '処理待ち'),
    'ui.sc_todo_hint' => $t('Zuerst Einträge mit Zahl öffnen', 'Abra primero los que tienen cifra', 'Ouvrez d’abord ceux avec un chiffre', '숫자 있는 항목부터', 'Abra primeiro os com número', '数字のある項目から'),
    'ui.sc_todo_empty' => $t('Nichts wartet', 'Nada pendiente', 'Rien en attente', '지금 할 일 없음', 'Nada à espera', '今は待ちがありません'),
    'ui.sc_library' => $t('Mediathek', 'Mediateca', 'Médiathèque', '영상 라이브러리', 'Biblioteca', 'ライブラリ'),
    'ui.sc_maintain' => $t('Wartung', 'Mantenimiento', 'Maintenance', '유지보수', 'Manutenção', '保守'),
    'ui.sc_plugins_hint' => $t('Manga, Shop und Chat hier installieren — nicht im Kernmenü', 'Manga, tienda y chat se instalan aquí, no en el menú núcleo', 'Manga, boutique et chat s’installent ici, pas au menu noyau', '만화·몰·채팅은 여기. 핵심 메뉴 아님', 'Manga, loja e chat instalam-se aqui, não no menu núcleo', '漫画・モール・チャットはここ。コアメニューではありません'),
    'auth.sub' => $t(
        'Filme, Manga, Romane, Galerien und Live haben je einen Arbeitsbereich — kein endloses Menü.',
        'Vídeo, manga, novelas, galerías y directo, cada uno con su mesa — no un menú interminable.',
        'Vidéo, manga, romans, galeries et live ont chacun un bureau — pas un menu sans fin.',
        '영상·만화·소설·도집·라이브를 나눠 관리합니다. 메뉴를 한 줄로 쌓지 않습니다.',
        'Vídeo, manga, romances, galerias e live têm cada um a sua secretária — não um menu sem fim.',
        '動画・漫画・小説・図集・ライブ配信を分けて管理。メニューを一列に積みません。'
    ),
    'auth.pitch_1' => $t(
        'Oben wechseln Filme / Manga / Romane / Galerien / Live; die Seitenleiste bleibt bei diesem Bereich',
        'La barra superior cambia Películas / Manga / Novelas / Galerías / Directo; la lateral se queda en esa mesa',
        'La barre du haut passe Films / Manga / Romans / Galeries / Live ; la latérale reste sur ce bureau',
        '위쪽에서 영상 / 만화 / 소설 / 도집 / 라이브를 바꾸고, 사이드바는 그 칸만',
        'A barra de cima muda Filmes / Manga / Romances / Galerias / Live; a lateral fica nessa secretária',
        'トップで 映像 / 漫画 / 小説 / 図集 / 配信 を切替え、サイドバーは今の欄だけ'
    ),
    'auth.pitch_2' => $t(
        'Sammeln, prüfen, veröffentlichen in einer Linie; PV / UV / Spider sind eingebaut',
        'Recolección, revisión y publicación en una línea; PV / UV / arañas van de serie',
        'Collecte, relecture et publication sur une ligne ; PV / UV / spiders sont intégrés',
        '수집·심사·공개가 한 줄. PV / UV / 스파이더 통계는 기본 제공',
        'Recolha, revisão e publicação numa linha; PV / UV / spiders já vêm incluídos',
        '収集・審査・公開が一本。PV / UV / クローラ統計は最初から入っています'
    ),
    'auth.pitch_3' => $t(
        'Zahlung und SMS als Plugins; die Admin-Oberfläche spricht neun Sprachen',
        'Pago y SMS se instalan como complementos; el admin habla nueve idiomas',
        'Paiement et SMS s’installent en extensions ; l’admin parle neuf langues',
        '결제와 문자는 플러그인. 관리 화면은 아홉 개 언어',
        'Pagamento e SMS instalam-se como extensões; o admin fala nove idiomas',
        '決済と SMS はプラグイン。管理画面は九つの言語'
    ),
];
