<?php

/**
 * Traffic log / spider stats display labels (visitor, referrer, page titles, devices).
 * Applied by tools/patch-display-i18n.php.
 */
$t = static fn (
    string $en,
    string $zh,
    string $de,
    string $es,
    string $fr,
    string $ko,
    string $pt,
    string $ja,
): array => [
    'en' => $en,
    'zh_cn' => $zh,
    'de' => $de,
    'es' => $es,
    'fr' => $fr,
    'ko' => $ko,
    'pt' => $pt,
    'ja' => $ja,
];

return [
    'ui.direct_visit' => $t('Direct', '直接访问', 'Direkt', 'Directo', 'Direct', '직접 방문', 'Direto', '直接アクセス'),
    'ui.internal_jump' => $t('Internal', '站内跳转', 'Intern', 'Interno', 'Interne', '내부 이동', 'Interno', 'サイト内'),
    'ui.device_desktop' => $t('Desktop', '桌面', 'Desktop', 'Escritorio', 'Bureau', '데스크톱', 'Ambiente de trabalho', 'デスクトップ'),
    'ui.device_mobile' => $t('Phone', '手机', 'Telefon', 'Móvil', 'Téléphone', '휴대폰', 'Telemóvel', '携帯'),
    'ui.device_tablet' => $t('Tablet', '平板', 'Tablet', 'Tableta', 'Tablette', '태블릿', 'Tablet', 'タブレット'),
    'ui.browser_wechat' => $t('WeChat', '微信', 'WeChat', 'WeChat', 'WeChat', '위챗', 'WeChat', 'WeChat'),
    'dash.vs_prev' => $t('vs previous', '较上期', 'ggü. Vorperiode', 'vs anterior', 'vs période préc.', '이전 대비', 'vs anterior', '前期比'),
    'ui.page_search' => $t('Search', '搜索', 'Suche', 'Búsqueda', 'Recherche', '검색', 'Pesquisa', '検索'),
    'ui.page_latest' => $t('Latest', '最新', 'Neueste', 'Recientes', 'Récents', '최신', 'Recentes', '最新'),
    'ui.page_arts_news' => $t('Articles', '资讯', 'Artikel', 'Artículos', 'Articles', '기사', 'Artigos', '記事'),
    'ui.page_plot' => $t('Plot', '剧情', 'Handlung', 'Trama', 'Intrigue', '줄거리', 'Enredo', 'あらすじ'),
    'ui.page_gbook' => $t('Guestbook', '留言', 'Gästebuch', 'Libro de visitas', 'Livre d’or', '방명록', 'Livro de visitas', '伝言'),
    'ui.page_member' => $t('Member center', '会员中心', 'Mitgliederbereich', 'Centro de miembros', 'Espace membre', '회원 센터', 'Centro de membros', '会員センター'),
    'ui.page_member_login' => $t('Member login', '会员登录', 'Mitglieder-Login', 'Entrada de miembro', 'Connexion membre', '회원 로그인', 'Entrada de membro', '会員ログイン'),
    'ui.page_member_register' => $t('Member register', '会员注册', 'Mitglieder-Registrierung', 'Registro de miembro', 'Inscription membre', '회원 가입', 'Registo de membro', '会員登録'),
    'ui.page_history' => $t('Watch history', '观看历史', 'Wiedergabeverlauf', 'Historial', 'Historique', '시청 기록', 'Histórico', '視聴履歴'),
    'ui.page_inbox' => $t('Inbox', '站内信', 'Posteingang', 'Bandeja', 'Boîte de réception', '쪽지함', 'Caixa de entrada', '受信箱'),
    'ui.page_sitemap' => $t('Sitemap', '站点地图', 'Sitemap', 'Mapa del sitio', 'Plan du site', '사이트맵', 'Mapa do sítio', 'サイトマップ'),
    'ui.page_vod_n' => $t('Video #:id', '影片 #:id', 'Video #:id', 'Vídeo #:id', 'Vidéo #:id', '영상 #:id', 'Vídeo #:id', '映像 #:id'),
    'ui.page_type' => $t('Category', '分类', 'Kategorie', 'Categoría', 'Catégorie', '분류', 'Categoria', 'カテゴリ'),
    'ui.page_type_slug' => $t('Category :slug', '分类 :slug', 'Kategorie :slug', 'Categoría :slug', 'Catégorie :slug', '분류 :slug', 'Categoria :slug', 'カテゴリ :slug'),
    'ui.page_actor' => $t('Actor', '演员', 'Schauspieler', 'Actor', 'Acteur', '배우', 'Actor', '俳優'),
    'ui.page_topic' => $t('Topic', '专题', 'Thema', 'Tema', 'Sujet', '특집', 'Tópico', '特集'),
    'ui.page_art' => $t('Article', '文章', 'Artikel', 'Artículo', 'Article', '기사', 'Artigo', '記事'),
    'ui.page_tag' => $t('Tag :name', '标签 :name', 'Tag :name', 'Etiqueta :name', 'Tag :name', '태그 :name', 'Etiqueta :name', 'タグ :name'),
    'ui.spider_search_engine' => $t('Search engines', '搜索引擎', 'Suchmaschinen', 'Motores de búsqueda', 'Moteurs de recherche', '검색 엔진', 'Motores de pesquisa', '検索エンジン'),
    'ui.spider_seo_tools' => $t('SEO tools', 'SEO 工具', 'SEO-Tools', 'Herramientas SEO', 'Outils SEO', 'SEO 도구', 'Ferramentas SEO', 'SEO ツール'),
    'ui.spider_ai' => $t('AI crawlers', 'AI 爬虫', 'KI-Crawler', 'Rastreadores IA', 'Crawlers IA', 'AI 크롤러', 'Rastreadores IA', 'AI クローラ'),
    'ui.spider_other_bot' => $t('Other crawlers', '其他爬虫', 'Andere Crawler', 'Otros rastreadores', 'Autres crawlers', '기타 크롤러', 'Outros rastreadores', 'その他クローラ'),
    'ui.engine_sogou' => $t('Sogou', '搜狗', 'Sogou', 'Sogou', 'Sogou', '소고우', 'Sogou', 'Sogou'),
    'ui.engine_bytedance' => $t('ByteDance', '字节', 'ByteDance', 'ByteDance', 'ByteDance', '바이트댄스', 'ByteDance', 'ByteDance'),
    'ui.client_col' => $t('Client', '客户端', 'Client', 'Cliente', 'Client', '클라이언트', 'Cliente', 'クライアント'),
    'ui.stats_overview' => $t('Overview', '概览', 'Überblick', 'Resumen', 'Aperçu', '개요', 'Resumo', '概要'),
    'ui.csv_period' => $t('Range', '时段', 'Zeitraum', 'Periodo', 'Période', '기간', 'Período', '期間'),
    'ui.csv_days30' => $t('Last 30 days', '近30天', 'Letzte 30 Tage', 'Últimos 30 días', '30 derniers jours', '최근 30일', 'Últimos 30 dias', '直近30日'),
    'ui.csv_change' => $t('Change', '变化', 'Änderung', 'Cambio', 'Variation', '변화', 'Variação', '変化'),
    'ui.csv_source' => $t('Source', '来源', 'Quelle', 'Fuente', 'Source', '출처', 'Fonte', '出典'),
    'ui.csv_type' => $t('Kind', '类型', 'Art', 'Tipo', 'Type', '종류', 'Tipo', '種類'),
    'ui.csv_name' => $t('Name', '名称', 'Name', 'Nombre', 'Nom', '이름', 'Nome', '名前'),
    'ui.csv_engine_visit' => $t('Search-engine visits', '搜索引擎到访', 'Suchmaschinenbesuche', 'Visitas de motores', 'Visites des moteurs', '검색 엔진 방문', 'Visitas de motores', '検索エンジン来訪'),
    'ui.csv_spider_summary' => $t('Spider summary', '蜘蛛汇总', 'Spider-Zusammenfassung', 'Resumen de arañas', 'Résumé des spiders', '스파이더 요약', 'Resumo de spiders', 'スパイダー集計'),
    'ui.csv_spider_pages' => $t('Most crawled pages', '被爬最多的页', 'Meist gecrawlte Seiten', 'Páginas más rastreadas', 'Pages les plus crawlées', '가장 많이 크롤된 페이지', 'Páginas mais rastreadas', '最もクロールされたページ'),
    'ui.csv_non_200' => $t('Non-200 crawls', '非200抓取', 'Crawls ungleich 200', 'Rastreos no 200', 'Crawls non-200', '비 200 수집', 'Rastreios não 200', '非200クロール'),
    'ui.csv_today_spider_pv' => $t('Today spider PV', '今日蜘蛛PV', 'Spider-PV heute', 'PV araña hoy', 'PV spider aujourd’hui', '오늘 스파이더 PV', 'PV spider hoje', '今日スパイダーPV'),
    'ui.csv_period_urls' => $t('Distinct URLs this period', '本期独立URL', 'Eindeutige URLs in der Periode', 'URL distintas del periodo', 'URL distinctes de la période', '이번 기간 고유 URL', 'URL distintas do período', '今期の独立 URL'),
    'ui.csv_non_200_n' => $t('Non-200 count', '非200次数', 'Anzahl ungleich 200', 'Recuento no 200', 'Nombre non-200', '비 200 횟수', 'Contagem não 200', '非200回数'),
    'ui.csv_tool_ai_share' => $t('Tools+AI share', '工具+AI占比', 'Anteil Tools+KI', 'Cuota herramientas+IA', 'Part outils+IA', '도구+AI 비중', 'Quota ferramentas+IA', 'ツール+AI 割合'),
    'ui.csv_engine' => $t('Engine', '引擎', 'Engine', 'Motor', 'Moteur', '엔진', 'Motor', 'エンジン'),
    'ui.csv_last_seen_days' => $t('Days since last visit', '距上次天数', 'Tage seit letztem Besuch', 'Días desde la última visita', 'Jours depuis la dernière visite', '마지막 방문 후 일수', 'Dias desde a última visita', '前回からの日数'),
    'ui.csv_spider' => $t('Spider', '蜘蛛', 'Spider', 'Araña', 'Spider', '스파이더', 'Spider', 'スパイダー'),
    'ui.csv_share_pct' => $t('Share %', '占比%', 'Anteil %', 'Cuota %', 'Part %', '비중 %', 'Quota %', '割合%'),
    'ui.csv_referer_hosts' => $t('Referrer hosts', '来路域名', 'Referrer-Hosts', 'Hosts de referrer', 'Hôtes referrer', '리퍼러 호스트', 'Anfitriões de referrer', 'リファラホスト'),
];
