<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {

        Schema::create('mac_actor', function (Blueprint $table) {
            $table->unsignedInteger('actor_id')->autoIncrement();
            $table->unsignedSmallInteger('type_id')->default(0);
            $table->unsignedSmallInteger('type_id_1')->default(0);
            $table->string('actor_name', 255);
            $table->string('actor_en', 255);
            $table->string('actor_alias', 255);
            $table->unsignedTinyInteger('actor_status')->default(0);
            $table->unsignedTinyInteger('actor_lock')->default(0);
            $table->char('actor_letter', 1);
            $table->char('actor_sex', 1);
            $table->string('actor_color', 6);
            $table->string('actor_pic', 1024);
            $table->string('actor_blurb', 255);
            $table->string('actor_remarks', 100);
            $table->string('actor_area', 20);
            $table->string('actor_height', 10);
            $table->string('actor_weight', 10);
            $table->string('actor_birthday', 10);
            $table->string('actor_birtharea', 20);
            $table->string('actor_blood', 10);
            $table->string('actor_starsign', 10);
            $table->string('actor_school', 20);
            $table->string('actor_works', 255);
            $table->string('actor_tag', 255);
            $table->string('actor_class', 255);
            $table->unsignedTinyInteger('actor_level')->default(0);
            $table->unsignedInteger('actor_time')->default(0);
            $table->unsignedInteger('actor_time_add')->default(0);
            $table->unsignedInteger('actor_time_hits')->default(0);
            $table->unsignedInteger('actor_time_make')->default(0);
            $table->unsignedMediumInteger('actor_hits')->default(0);
            $table->unsignedMediumInteger('actor_hits_day')->default(0);
            $table->unsignedMediumInteger('actor_hits_week')->default(0);
            $table->unsignedMediumInteger('actor_hits_month')->default(0);
            $table->decimal('actor_score', 3, 1)->unsigned()->default(0.0);
            $table->unsignedMediumInteger('actor_score_all')->default(0);
            $table->unsignedMediumInteger('actor_score_num')->default(0);
            $table->unsignedMediumInteger('actor_up')->default(0);
            $table->unsignedMediumInteger('actor_down')->default(0);
            $table->string('actor_tpl', 30);
            $table->string('actor_jumpurl', 150);
            $table->text('actor_content');
            $table->index('type_id', 'type_id');
            $table->index('type_id_1', 'type_id_1');
            $table->index('actor_name', 'actor_name');
            $table->index('actor_en', 'actor_en');
            $table->index('actor_letter', 'actor_letter');
            $table->index('actor_level', 'actor_level');
            $table->index('actor_time', 'actor_time');
            $table->index('actor_time_add', 'actor_time_add');
            $table->index('actor_sex', 'actor_sex');
            $table->index('actor_area', 'actor_area');
            $table->index('actor_up', 'actor_up');
            $table->index('actor_down', 'actor_down');
            $table->index('actor_tag', 'actor_tag');
            $table->index('actor_class', 'actor_class');
            $table->index('actor_score', 'actor_score');
            $table->index('actor_score_all', 'actor_score_all');
            $table->index('actor_score_num', 'actor_score_num');
        });

        Schema::create('mac_role', function (Blueprint $table) {
            $table->unsignedInteger('role_id')->autoIncrement();
            $table->unsignedInteger('role_rid')->default(0);
            $table->string('role_name', 255);
            $table->string('role_en', 255);
            $table->unsignedTinyInteger('role_status')->default(0);
            $table->unsignedTinyInteger('role_lock')->default(0);
            $table->char('role_letter', 1);
            $table->string('role_color', 6);
            $table->string('role_actor', 255);
            $table->string('role_remarks', 100);
            $table->string('role_pic', 1024);
            $table->unsignedSmallInteger('role_sort')->default(0);
            $table->unsignedTinyInteger('role_level')->default(0);
            $table->unsignedInteger('role_time')->default(0);
            $table->unsignedInteger('role_time_add')->default(0);
            $table->unsignedInteger('role_time_hits')->default(0);
            $table->unsignedInteger('role_time_make')->default(0);
            $table->unsignedMediumInteger('role_hits')->default(0);
            $table->unsignedMediumInteger('role_hits_day')->default(0);
            $table->unsignedMediumInteger('role_hits_week')->default(0);
            $table->unsignedMediumInteger('role_hits_month')->default(0);
            $table->decimal('role_score', 3, 1)->unsigned()->default(0.0);
            $table->unsignedMediumInteger('role_score_all')->default(0);
            $table->unsignedMediumInteger('role_score_num')->default(0);
            $table->unsignedMediumInteger('role_up')->default(0);
            $table->unsignedMediumInteger('role_down')->default(0);
            $table->string('role_tpl', 30);
            $table->string('role_jumpurl', 150);
            $table->text('role_content');
            $table->index('role_rid', 'role_rid');
            $table->index('role_name', 'role_name');
            $table->index('role_en', 'role_en');
            $table->index('role_letter', 'role_letter');
            $table->index('role_actor', 'role_actor');
            $table->index('role_level', 'role_level');
            $table->index('role_time', 'role_time');
            $table->index('role_time_add', 'role_time_add');
            $table->index('role_score', 'role_score');
            $table->index('role_score_all', 'role_score_all');
            $table->index('role_score_num', 'role_score_num');
            $table->index('role_up', 'role_up');
            $table->index('role_down', 'role_down');
        });

        Schema::create('mac_topic', function (Blueprint $table) {
            $table->unsignedSmallInteger('topic_id')->autoIncrement();
            $table->string('topic_name', 255);
            $table->string('topic_en', 255);
            $table->string('topic_sub', 255);
            $table->unsignedTinyInteger('topic_status')->default(1);
            $table->unsignedSmallInteger('topic_sort')->default(0);
            $table->char('topic_letter', 1);
            $table->string('topic_color', 6);
            $table->string('topic_tpl', 30);
            $table->string('topic_type', 255);
            $table->string('topic_pic', 1024);
            $table->string('topic_pic_thumb', 1024);
            $table->string('topic_pic_slide', 1024);
            $table->string('topic_key', 255);
            $table->string('topic_des', 255);
            $table->string('topic_title', 255);
            $table->string('topic_blurb', 255);
            $table->string('topic_remarks', 100);
            $table->unsignedTinyInteger('topic_level')->default(0);
            $table->unsignedMediumInteger('topic_up')->default(0);
            $table->unsignedMediumInteger('topic_down')->default(0);
            $table->decimal('topic_score', 3, 1)->unsigned()->default(0.0);
            $table->unsignedMediumInteger('topic_score_all')->default(0);
            $table->unsignedMediumInteger('topic_score_num')->default(0);
            $table->unsignedMediumInteger('topic_hits')->default(0);
            $table->unsignedMediumInteger('topic_hits_day')->default(0);
            $table->unsignedMediumInteger('topic_hits_week')->default(0);
            $table->unsignedMediumInteger('topic_hits_month')->default(0);
            $table->unsignedInteger('topic_time')->default(0);
            $table->unsignedInteger('topic_time_add')->default(0);
            $table->unsignedInteger('topic_time_hits')->default(0);
            $table->unsignedInteger('topic_time_make')->default(0);
            $table->string('topic_tag', 255);
            $table->text('topic_rel_vod');
            $table->text('topic_rel_art');
            $table->text('topic_content');
            $table->text('topic_extend');
            $table->index('topic_sort', 'topic_sort');
            $table->index('topic_level', 'topic_level');
            $table->index('topic_score', 'topic_score');
            $table->index('topic_score_all', 'topic_score_all');
            $table->index('topic_score_num', 'topic_score_num');
            $table->index('topic_hits', 'topic_hits');
            $table->index('topic_hits_day', 'topic_hits_day');
            $table->index('topic_hits_week', 'topic_hits_week');
            $table->index('topic_hits_month', 'topic_hits_month');
            $table->index('topic_time_add', 'topic_time_add');
            $table->index('topic_time', 'topic_time');
            $table->index('topic_time_hits', 'topic_time_hits');
            $table->index('topic_name', 'topic_name');
            $table->index('topic_en', 'topic_en');
            $table->index('topic_up', 'topic_up');
            $table->index('topic_down', 'topic_down');
        });

        Schema::create('mac_website', function (Blueprint $table) {
            $table->unsignedInteger('website_id')->autoIncrement();
            $table->unsignedSmallInteger('type_id')->default(0);
            $table->unsignedSmallInteger('type_id_1')->default(0);
            $table->string('website_name', 60);
            $table->string('website_sub', 255);
            $table->string('website_en', 255);
            $table->unsignedTinyInteger('website_status')->default(0);
            $table->char('website_letter', 1);
            $table->string('website_color', 6);
            $table->unsignedTinyInteger('website_lock')->default(0);
            $table->integer('website_sort')->default(0);
            $table->string('website_jumpurl', 255);
            $table->string('website_pic', 1024);
            $table->text('website_pic_screenshot')->nullable();
            $table->string('website_logo', 255);
            $table->string('website_area', 20);
            $table->string('website_lang', 10);
            $table->unsignedTinyInteger('website_level')->default(0);
            $table->unsignedInteger('website_time')->default(0);
            $table->unsignedInteger('website_time_add')->default(0);
            $table->unsignedInteger('website_time_hits')->default(0);
            $table->unsignedInteger('website_time_make')->default(0);
            $table->unsignedInteger('website_time_referer')->default(0);
            $table->unsignedMediumInteger('website_hits')->default(0);
            $table->unsignedMediumInteger('website_hits_day')->default(0);
            $table->unsignedMediumInteger('website_hits_week')->default(0);
            $table->unsignedMediumInteger('website_hits_month')->default(0);
            $table->decimal('website_score', 3, 1)->unsigned()->default(0.0);
            $table->unsignedMediumInteger('website_score_all')->default(0);
            $table->unsignedMediumInteger('website_score_num')->default(0);
            $table->unsignedMediumInteger('website_up')->default(0);
            $table->unsignedMediumInteger('website_down')->default(0);
            $table->unsignedMediumInteger('website_referer')->default(0);
            $table->unsignedMediumInteger('website_referer_day')->default(0);
            $table->unsignedMediumInteger('website_referer_week')->default(0);
            $table->unsignedMediumInteger('website_referer_month')->default(0);
            $table->string('website_tag', 100);
            $table->string('website_class', 255);
            $table->string('website_remarks', 100);
            $table->string('website_tpl', 30);
            $table->string('website_blurb', 255);
            $table->mediumText('website_content');
            $table->index('type_id', 'type_id');
            $table->index('type_id_1', 'type_id_1');
            $table->index('website_name', 'website_name');
            $table->index('website_en', 'website_en');
            $table->index('website_letter', 'website_letter');
            $table->index('website_sort', 'website_sort');
            $table->index('website_lock', 'website_lock');
            $table->index('website_time', 'website_time');
            $table->index('website_time_add', 'website_time_add');
            $table->index('website_time_referer', 'website_time_referer');
            $table->index('website_hits', 'website_hits');
            $table->index('website_hits_day', 'website_hits_day');
            $table->index('website_hits_week', 'website_hits_week');
            $table->index('website_hits_month', 'website_hits_month');
            $table->index('website_time_make', 'website_time_make');
            $table->index('website_score', 'website_score');
            $table->index('website_score_all', 'website_score_all');
            $table->index('website_score_num', 'website_score_num');
            $table->index('website_up', 'website_up');
            $table->index('website_down', 'website_down');
            $table->index('website_level', 'website_level');
            $table->index('website_tag', 'website_tag');
            $table->index('website_class', 'website_class');
            $table->index('website_referer', 'website_referer');
            $table->index('website_referer_day', 'website_referer_day');
            $table->index('website_referer_week', 'website_referer_week');
            $table->index('website_referer_month', 'website_referer_month');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('mac_website');
        Schema::dropIfExists('mac_topic');
        Schema::dropIfExists('mac_role');
        Schema::dropIfExists('mac_actor');
    }
};
