<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {

        Schema::create('mac_vod', function (Blueprint $table) {
            $table->unsignedInteger('vod_id')->autoIncrement();
            $table->smallInteger('type_id')->default(0);
            $table->unsignedSmallInteger('type_id_1')->default(0);
            $table->unsignedSmallInteger('group_id')->default(0);
            $table->string('vod_name', 255);
            $table->string('vod_sub', 255);
            $table->string('vod_en', 255);
            $table->unsignedTinyInteger('vod_status')->default(0);
            $table->char('vod_letter', 1);
            $table->string('vod_color', 6);
            $table->string('vod_tag', 100);
            $table->string('vod_class', 255);
            $table->string('vod_pic', 1024);
            $table->string('vod_pic_thumb', 1024);
            $table->string('vod_pic_slide', 1024);
            $table->text('vod_pic_screenshot')->nullable();
            $table->string('vod_actor', 255);
            $table->string('vod_director', 255);
            $table->string('vod_writer', 100);
            $table->string('vod_behind', 100);
            $table->string('vod_blurb', 255);
            $table->string('vod_remarks', 100);
            $table->string('vod_pubdate', 100);
            $table->unsignedMediumInteger('vod_total')->default(0);
            $table->string('vod_serial', 20)->default(0);
            $table->string('vod_tv', 30);
            $table->string('vod_weekday', 30);
            $table->string('vod_area', 20);
            $table->string('vod_lang', 10);
            $table->string('vod_year', 10);
            $table->string('vod_version', 30);
            $table->string('vod_state', 30);
            $table->string('vod_author', 60);
            $table->string('vod_jumpurl', 150);
            $table->string('vod_tpl', 30);
            $table->string('vod_tpl_play', 30);
            $table->string('vod_tpl_down', 30);
            $table->unsignedTinyInteger('vod_isend')->default(0);
            $table->unsignedTinyInteger('vod_lock')->default(0);
            $table->unsignedTinyInteger('vod_level')->default(0);
            $table->unsignedTinyInteger('vod_copyright')->default(0);
            $table->unsignedSmallInteger('vod_points')->default(0);
            $table->unsignedSmallInteger('vod_points_play')->default(0);
            $table->unsignedSmallInteger('vod_points_down')->default(0);
            $table->unsignedMediumInteger('vod_hits')->default(0);
            $table->unsignedMediumInteger('vod_hits_day')->default(0);
            $table->unsignedMediumInteger('vod_hits_week')->default(0);
            $table->unsignedMediumInteger('vod_hits_month')->default(0);
            $table->string('vod_duration', 10);
            $table->unsignedMediumInteger('vod_up')->default(0);
            $table->unsignedMediumInteger('vod_down')->default(0);
            $table->decimal('vod_score', 3, 1)->unsigned()->default(0.0);
            $table->unsignedMediumInteger('vod_score_all')->default(0);
            $table->unsignedMediumInteger('vod_score_num')->default(0);
            $table->unsignedInteger('vod_time')->default(0);
            $table->unsignedInteger('vod_time_add')->default(0);
            $table->unsignedInteger('vod_time_hits')->default(0);
            $table->unsignedInteger('vod_time_make')->default(0);
            $table->unsignedSmallInteger('vod_trysee')->default(0);
            $table->unsignedInteger('vod_douban_id')->default(0);
            $table->decimal('vod_douban_score', 3, 1)->unsigned()->default(0.0);
            $table->string('vod_reurl', 255);
            $table->string('vod_rel_vod', 255);
            $table->string('vod_rel_art', 255);
            $table->string('vod_pwd', 10);
            $table->string('vod_pwd_url', 255);
            $table->string('vod_pwd_play', 10);
            $table->string('vod_pwd_play_url', 255);
            $table->string('vod_pwd_down', 10);
            $table->string('vod_pwd_down_url', 255);
            $table->mediumText('vod_content');
            $table->string('vod_play_from', 255);
            $table->string('vod_play_server', 255);
            $table->string('vod_play_note', 255);
            $table->mediumText('vod_play_url');
            $table->string('vod_down_from', 255);
            $table->string('vod_down_server', 255);
            $table->string('vod_down_note', 255);
            $table->mediumText('vod_down_url');
            $table->unsignedTinyInteger('vod_plot')->default(0);
            $table->mediumText('vod_plot_name');
            $table->mediumText('vod_plot_detail');
            $table->index('type_id', 'type_id');
            $table->index('type_id_1', 'type_id_1');
            $table->index('vod_level', 'vod_level');
            $table->index('vod_hits', 'vod_hits');
            $table->index('vod_letter', 'vod_letter');
            $table->index('vod_name', 'vod_name');
            $table->index('vod_year', 'vod_year');
            $table->index('vod_area', 'vod_area');
            $table->index('vod_lang', 'vod_lang');
            $table->index('vod_tag', 'vod_tag');
            $table->index('vod_class', 'vod_class');
            $table->index('vod_lock', 'vod_lock');
            $table->index('vod_up', 'vod_up');
            $table->index('vod_down', 'vod_down');
            $table->index('vod_en', 'vod_en');
            $table->index('vod_hits_day', 'vod_hits_day');
            $table->index('vod_hits_week', 'vod_hits_week');
            $table->index('vod_hits_month', 'vod_hits_month');
            $table->index('vod_plot', 'vod_plot');
            $table->index('vod_points_play', 'vod_points_play');
            $table->index('vod_points_down', 'vod_points_down');
            $table->index('group_id', 'group_id');
            $table->index('vod_time_add', 'vod_time_add');
            $table->index('vod_time', 'vod_time');
            $table->index('vod_time_make', 'vod_time_make');
            $table->index('vod_actor', 'vod_actor');
            $table->index('vod_director', 'vod_director');
            $table->index('vod_score_all', 'vod_score_all');
            $table->index('vod_score_num', 'vod_score_num');
            $table->index('vod_total', 'vod_total');
            $table->index('vod_score', 'vod_score');
            $table->index('vod_version', 'vod_version');
            $table->index('vod_state', 'vod_state');
            $table->index('vod_isend', 'vod_isend');
        });

        Schema::create('mac_art', function (Blueprint $table) {
            $table->unsignedInteger('art_id')->autoIncrement();
            $table->unsignedSmallInteger('type_id')->default(0);
            $table->unsignedSmallInteger('type_id_1')->default(0);
            $table->unsignedSmallInteger('group_id')->default(0);
            $table->string('art_name', 255);
            $table->string('art_sub', 255);
            $table->string('art_en', 255);
            $table->unsignedTinyInteger('art_status')->default(0);
            $table->char('art_letter', 1);
            $table->string('art_color', 6);
            $table->string('art_from', 30);
            $table->string('art_author', 30);
            $table->string('art_tag', 100);
            $table->string('art_class', 255);
            $table->string('art_pic', 1024);
            $table->string('art_pic_thumb', 1024);
            $table->string('art_pic_slide', 1024);
            $table->text('art_pic_screenshot')->nullable();
            $table->string('art_blurb', 255);
            $table->string('art_remarks', 100);
            $table->string('art_jumpurl', 150);
            $table->string('art_tpl', 30);
            $table->unsignedTinyInteger('art_level')->default(0);
            $table->unsignedTinyInteger('art_lock')->default(0);
            $table->unsignedSmallInteger('art_points')->default(0);
            $table->unsignedSmallInteger('art_points_detail')->default(0);
            $table->unsignedMediumInteger('art_up')->default(0);
            $table->unsignedMediumInteger('art_down')->default(0);
            $table->unsignedMediumInteger('art_hits')->default(0);
            $table->unsignedMediumInteger('art_hits_day')->default(0);
            $table->unsignedMediumInteger('art_hits_week')->default(0);
            $table->unsignedMediumInteger('art_hits_month')->default(0);
            $table->unsignedInteger('art_time')->default(0);
            $table->unsignedInteger('art_time_add')->default(0);
            $table->unsignedInteger('art_time_hits')->default(0);
            $table->unsignedInteger('art_time_make')->default(0);
            $table->decimal('art_score', 3, 1)->unsigned()->default(0.0);
            $table->decimal('art_score', 3, 1)->unsigned()->default(0.0);
            $table->unsignedMediumInteger('art_score_all')->default(0);
            $table->unsignedMediumInteger('art_score_num')->default(0);
            $table->mediumText('art_title');
            $table->mediumText('art_note');
            $table->mediumText('art_content');
            $table->string('art_rel_art', 255);
            $table->string('art_rel_vod', 255);
            $table->string('art_pwd', 10);
            $table->string('art_pwd_url', 255);
            $table->mediumText('art_title');
            $table->mediumText('art_note');
            $table->mediumText('art_content');
            $table->index('type_id', 'type_id');
            $table->index('type_id_1', 'type_id_1');
            $table->index('art_level', 'art_level');
            $table->index('art_hits', 'art_hits');
            $table->index('art_time', 'art_time');
            $table->index('art_letter', 'art_letter');
            $table->index('art_down', 'art_down');
            $table->index('art_up', 'art_up');
            $table->index('art_tag', 'art_tag');
            $table->index('art_name', 'art_name');
            $table->index('art_en', 'art_enn');
            $table->index('art_hits_day', 'art_hits_day');
            $table->index('art_hits_week', 'art_hits_week');
            $table->index('art_hits_month', 'art_hits_month');
            $table->index('art_time_add', 'art_time_add');
            $table->index('art_time_make', 'art_time_make');
            $table->index('art_lock', 'art_lock');
            $table->index('art_score', 'art_score');
            $table->index('art_score_all', 'art_score_all');
            $table->index('art_score_num', 'art_score_num');
        });

        Schema::create('mac_manga', function (Blueprint $table) {
            $table->unsignedInteger('manga_id')->autoIncrement();
            $table->unsignedSmallInteger('type_id')->default(0);
            $table->unsignedSmallInteger('type_id_1')->default(0);
            $table->unsignedSmallInteger('group_id')->default(0);
            $table->string('manga_name', 255);
            $table->string('manga_sub', 255);
            $table->string('manga_en', 255);
            $table->unsignedTinyInteger('manga_status')->default(0);
            $table->char('manga_letter', 1);
            $table->string('manga_color', 6);
            $table->string('manga_from', 30);
            $table->string('manga_author', 255);
            $table->string('manga_tag', 100);
            $table->string('manga_class', 255);
            $table->string('manga_pic', 1024);
            $table->string('manga_pic_thumb', 1024);
            $table->string('manga_pic_slide', 1024);
            $table->text('manga_pic_screenshot')->nullable()->default('NULL COMMENT');
            $table->string('manga_blurb', 255);
            $table->string('manga_remarks', 100);
            $table->string('manga_jumpurl', 150);
            $table->string('manga_tpl', 30);
            $table->unsignedTinyInteger('manga_level')->default(0);
            $table->unsignedTinyInteger('manga_lock')->default(0);
            $table->unsignedSmallInteger('manga_points')->default(0);
            $table->unsignedSmallInteger('manga_points_detail')->default(0);
            $table->unsignedMediumInteger('manga_up')->default(0);
            $table->unsignedMediumInteger('manga_down')->default(0);
            $table->unsignedMediumInteger('manga_hits')->default(0);
            $table->unsignedMediumInteger('manga_hits_day')->default(0);
            $table->unsignedMediumInteger('manga_hits_week')->default(0);
            $table->unsignedMediumInteger('manga_hits_month')->default(0);
            $table->unsignedInteger('manga_time')->default(0);
            $table->unsignedInteger('manga_time_add')->default(0);
            $table->unsignedInteger('manga_time_hits')->default(0);
            $table->unsignedInteger('manga_time_make')->default(0);
            $table->decimal('manga_score', 3, 1)->unsigned()->default(0.0);
            $table->decimal('manga_score', 3, 1)->unsigned()->default(0.0);
            $table->unsignedMediumInteger('manga_score_all')->default(0);
            $table->unsignedMediumInteger('manga_score_num')->default(0);
            $table->mediumText('manga_content')->nullable();
            $table->string('manga_rel_manga', 255);
            $table->string('manga_rel_vod', 255);
            $table->string('manga_pwd', 10);
            $table->string('manga_pwd_url', 255);
            $table->mediumText('manga_content')->nullable();
            $table->string('manga_serial', 20)->default('0');
            $table->unsignedMediumInteger('manga_total')->default(0);
            $table->string('manga_chapter_from', 255);
            $table->mediumText('manga_chapter_url')->nullable();
            $table->unsignedInteger('manga_last_update_time')->default(0);
            $table->unsignedTinyInteger('manga_age_rating')->default(0);
            $table->unsignedTinyInteger('manga_orientation')->default(0);
            $table->unsignedTinyInteger('manga_is_vip')->default(0);
            $table->string('manga_copyright_info', 255);
            $table->index('type_id', 'type_id');
            $table->index('type_id_1', 'type_id_1');
            $table->index('manga_level', 'manga_level');
            $table->index('manga_hits', 'manga_hits');
            $table->index('manga_time', 'manga_time');
            $table->index('manga_letter', 'manga_letter');
            $table->index('manga_down', 'manga_down');
            $table->index('manga_up', 'manga_up');
            $table->index('manga_tag', 'manga_tag');
            $table->index('manga_name', 'manga_name');
            $table->index('manga_en', 'manga_en');
            $table->index('manga_hits_day', 'manga_hits_day');
            $table->index('manga_hits_week', 'manga_hits_week');
            $table->index('manga_hits_month', 'manga_hits_month');
            $table->index('manga_time_add', 'manga_time_add');
            $table->index('manga_time_make', 'manga_time_make');
            $table->index('manga_lock', 'manga_lock');
            $table->index('manga_score', 'manga_score');
            $table->index('manga_score_all', 'manga_score_all');
            $table->index('manga_score_num', 'manga_score_num');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('mac_manga');
        Schema::dropIfExists('mac_art');
        Schema::dropIfExists('mac_vod');
    }
};
