<?php

namespace App\Services\Admin\System;

/**
 * 库表字段目录：表和字段干什么。SQLite 没有备注，不编 MySQL comment。
 */
class SysDatabaseDictCatalog
{
    /** @return array<string, string> */
    public function groups(): array
    {
        return [
            'catalog' => admin_t('db.group_catalog'),
            'manga' => admin_t('db.group_manga'),
            'novel' => admin_t('db.group_novel'),
            'gallery' => admin_t('db.group_gallery'),
            'live' => admin_t('db.group_live'),
            'member' => admin_t('db.group_member'),
            'collect' => admin_t('db.group_collect'),
            'site' => admin_t('db.group_site'),
            'stats' => admin_t('db.group_stats'),
            'plugin' => admin_t('db.group_plugin'),
            'system' => admin_t('db.group_system'),
            'framework' => admin_t('db.group_framework'),
            'other' => admin_t('db.group_other'),
        ];
    }

    /**
     * @return array<string, array{group:string,label:string,hint:string,url:string}>
     */
    public function tables(): array
    {
        return [
            'videos' => ['group' => 'catalog', 'label' => admin_t('ui.videos'), 'hint' => admin_t('db.hint_videos'), 'url' => '/admin/video'],
            'video_types' => ['group' => 'catalog', 'label' => admin_t('ui.types'), 'hint' => admin_t('db.hint_video_types'), 'url' => '/admin/video/types'],
            'video_stats' => ['group' => 'catalog', 'label' => admin_t('db.tbl_video_stats'), 'hint' => admin_t('db.hint_video_stats'), 'url' => '/admin/video'],
            'video_sources' => ['group' => 'catalog', 'label' => admin_t('ui.play_lines'), 'hint' => admin_t('db.hint_video_sources'), 'url' => '/admin/video'],
            'video_episodes' => ['group' => 'catalog', 'label' => admin_t('db.tbl_video_episodes'), 'hint' => admin_t('db.hint_video_episodes'), 'url' => '/admin/video'],
            'video_players' => ['group' => 'catalog', 'label' => admin_t('ui.players'), 'hint' => admin_t('db.hint_video_players'), 'url' => '/admin/video/players'],
            'video_tags' => ['group' => 'catalog', 'label' => admin_t('ui.tags'), 'hint' => admin_t('db.hint_video_tags'), 'url' => '/admin/video/tags'],
            'video_tag_rel' => ['group' => 'catalog', 'label' => admin_t('db.tbl_video_tag_rel'), 'hint' => admin_t('db.hint_video_tag_rel'), 'url' => '/admin/video/tags'],
            'actors' => ['group' => 'catalog', 'label' => admin_t('ui.actors'), 'hint' => admin_t('db.hint_actors'), 'url' => '/admin/video/actors'],
            'video_actor_rel' => ['group' => 'catalog', 'label' => admin_t('db.tbl_video_actor_rel'), 'hint' => admin_t('db.hint_video_actor_rel'), 'url' => '/admin/video/actors'],
            'video_roles' => ['group' => 'catalog', 'label' => admin_t('db.tbl_video_roles'), 'hint' => admin_t('db.hint_video_roles'), 'url' => '/admin/video/roles'],
            'video_topics' => ['group' => 'catalog', 'label' => admin_t('ui.topics'), 'hint' => admin_t('db.hint_video_topics'), 'url' => '/admin/video/topics'],
            'video_topic_rel' => ['group' => 'catalog', 'label' => admin_t('db.tbl_video_topic_rel'), 'hint' => admin_t('db.hint_video_topic_rel'), 'url' => '/admin/video/topics'],
            'video_topic_art_rel' => ['group' => 'catalog', 'label' => admin_t('db.tbl_video_topic_art_rel'), 'hint' => admin_t('db.hint_video_topic_art_rel'), 'url' => '/admin/video/topics'],
            'video_arts' => ['group' => 'catalog', 'label' => admin_t('ui.articles'), 'hint' => admin_t('db.hint_video_arts'), 'url' => '/admin/video/arts'],
            'video_art_tags' => ['group' => 'catalog', 'label' => admin_t('db.tbl_video_art_tags'), 'hint' => admin_t('db.hint_video_art_tags'), 'url' => '/admin/video/art-tags'],
            'video_art_tag_rel' => ['group' => 'catalog', 'label' => admin_t('db.tbl_video_art_tag_rel'), 'hint' => admin_t('db.hint_video_art_tag_rel'), 'url' => '/admin/video/art-tags'],
            'video_plots' => ['group' => 'catalog', 'label' => admin_t('ui.plots'), 'hint' => admin_t('db.hint_video_plots'), 'url' => '/admin/video/plots'],
            'video_classes' => ['group' => 'catalog', 'label' => admin_t('ui.ext_classes'), 'hint' => admin_t('db.hint_video_classes'), 'url' => '/admin/video/classes'],
            'video_synonyms' => ['group' => 'catalog', 'label' => admin_t('ui.synonyms'), 'hint' => admin_t('db.hint_video_synonyms'), 'url' => '/admin/video/synonyms'],
            'video_downloaders' => ['group' => 'catalog', 'label' => admin_t('ui.col_downer'), 'hint' => admin_t('db.hint_video_downloaders'), 'url' => '/admin/video/downloaders'],
            'video_servers' => ['group' => 'catalog', 'label' => admin_t('ui.servers'), 'hint' => admin_t('db.hint_video_servers'), 'url' => '/admin/video/servers'],
            'collect_sources' => ['group' => 'collect', 'label' => admin_t('ui.collects'), 'hint' => admin_t('db.hint_collect_sources'), 'url' => '/admin/video/collects'],
            'video_collect_tasks' => ['group' => 'collect', 'label' => admin_t('ui.collect_tasks'), 'hint' => admin_t('db.hint_video_collect_tasks'), 'url' => '/admin/video/collect_tasks'],
            'video_collect_logs' => ['group' => 'collect', 'label' => admin_t('ui.collect_logs'), 'hint' => admin_t('db.hint_video_collect_logs'), 'url' => '/admin/video/collect_logs'],
            'video_collect_temps' => ['group' => 'collect', 'label' => admin_t('db.tbl_video_collect_temps'), 'hint' => admin_t('db.hint_video_collect_temps'), 'url' => '/admin/video/collect_temps'],
            'video_audit_rules' => ['group' => 'collect', 'label' => admin_t('db.tbl_video_audit_rules'), 'hint' => admin_t('db.hint_video_audit_rules'), 'url' => '/admin/video/audits'],
            'video_cj_rules' => ['group' => 'collect', 'label' => admin_t('ui.cj_link'), 'hint' => admin_t('db.hint_video_cj_rules'), 'url' => '/admin/video/cj'],
            'video_cj_rule_logs' => ['group' => 'collect', 'label' => admin_t('db.tbl_video_cj_rule_logs'), 'hint' => admin_t('db.hint_video_cj_rule_logs'), 'url' => '/admin/video/cj?desk=logs'],
            'video_unions' => ['group' => 'collect', 'label' => admin_t('db.tbl_video_unions'), 'hint' => admin_t('db.hint_video_unions'), 'url' => '/admin/video/unions'],
            'members' => ['group' => 'member', 'label' => admin_t('ui.members'), 'hint' => admin_t('db.hint_members'), 'url' => '/admin/video/members'],
            'member_groups' => ['group' => 'member', 'label' => admin_t('ui.member_groups'), 'hint' => admin_t('db.hint_member_groups'), 'url' => '/admin/video/groups'],
            'member_favorites' => ['group' => 'member', 'label' => admin_t('ui.favors'), 'hint' => admin_t('db.hint_member_favorites'), 'url' => '/admin/video/favorites'],
            'member_histories' => ['group' => 'member', 'label' => admin_t('db.tbl_member_histories'), 'hint' => admin_t('db.hint_member_histories'), 'url' => '/admin/video/members'],
            'member_orders' => ['group' => 'member', 'label' => admin_t('ui.orders'), 'hint' => admin_t('db.hint_member_orders'), 'url' => '/admin/video/orders'],
            'member_withdraws' => ['group' => 'member', 'label' => admin_t('db.tbl_member_withdraws'), 'hint' => admin_t('db.hint_member_withdraws'), 'url' => '/admin/video/withdraws'],
            'member_pms' => ['group' => 'member', 'label' => admin_t('ui.pms'), 'hint' => admin_t('db.hint_member_pms'), 'url' => '/admin/video/pms'],
            'member_point_logs' => ['group' => 'member', 'label' => admin_t('ui.plogs'), 'hint' => admin_t('db.hint_member_point_logs'), 'url' => '/admin/video/members'],
            'member_invites' => ['group' => 'member', 'label' => admin_t('ui.invites'), 'hint' => admin_t('db.hint_member_invites'), 'url' => '/admin/video/invites'],
            'member_follows' => ['group' => 'member', 'label' => admin_t('db.tbl_member_follows'), 'hint' => admin_t('db.hint_member_follows'), 'url' => '/admin/video/members'],
            'member_dynamics' => ['group' => 'member', 'label' => admin_t('db.tbl_member_dynamics'), 'hint' => admin_t('db.hint_member_dynamics'), 'url' => '/admin/video/members'],
            'member_shares' => ['group' => 'member', 'label' => admin_t('db.tbl_member_shares'), 'hint' => admin_t('db.hint_member_shares'), 'url' => '/admin/video/members'],
            'member_signs' => ['group' => 'member', 'label' => admin_t('db.tbl_member_signs'), 'hint' => admin_t('db.hint_member_signs'), 'url' => '/admin/video/activity?desk=signs'],
            'member_tasks' => ['group' => 'member', 'label' => admin_t('db.tbl_member_tasks'), 'hint' => admin_t('db.hint_member_tasks'), 'url' => '/admin/video/activity'],
            'member_task_logs' => ['group' => 'member', 'label' => admin_t('db.tbl_member_task_logs'), 'hint' => admin_t('db.hint_member_task_logs'), 'url' => '/admin/video/activity?desk=logs'],
            'member_sign_milestones' => ['group' => 'member', 'label' => admin_t('db.tbl_member_sign_milestones'), 'hint' => admin_t('db.hint_member_sign_milestones'), 'url' => '/admin/video/activity?desk=milestones'],
            'member_sign_milestone_logs' => ['group' => 'member', 'label' => admin_t('db.tbl_member_sign_milestone_logs'), 'hint' => admin_t('db.hint_member_sign_milestone_logs'), 'url' => '/admin/video/activity?desk=milestones'],
            'video_cards' => ['group' => 'member', 'label' => admin_t('ui.cards'), 'hint' => admin_t('db.hint_video_cards'), 'url' => '/admin/video/cards'],
            'video_coupons' => ['group' => 'member', 'label' => admin_t('db.tbl_video_coupons'), 'hint' => admin_t('db.hint_video_coupons'), 'url' => '/admin/video/coupons'],
            'video_comments' => ['group' => 'site', 'label' => admin_t('ui.comments'), 'hint' => admin_t('db.hint_video_comments'), 'url' => '/admin/video/comments'],
            'video_reports' => ['group' => 'site', 'label' => admin_t('ui.reports'), 'hint' => admin_t('db.hint_video_reports'), 'url' => '/admin/video/reports'],
            'video_play_fails' => ['group' => 'site', 'label' => admin_t('ui.playfails'), 'hint' => admin_t('db.hint_video_play_fails'), 'url' => '/admin/video/playfails'],
            'video_guestbooks' => ['group' => 'site', 'label' => admin_t('ui.guestbooks'), 'hint' => admin_t('db.hint_video_guestbooks'), 'url' => '/admin/video/guestbooks'],
            'video_notifies' => ['group' => 'site', 'label' => admin_t('ui.col_notify'), 'hint' => admin_t('db.hint_video_notifies'), 'url' => '/admin/video/notifies'],
            'video_ads' => ['group' => 'site', 'label' => admin_t('ui.col_ad'), 'hint' => admin_t('db.hint_video_ads'), 'url' => '/admin/video/ads'],
            'video_slides' => ['group' => 'site', 'label' => admin_t('ui.col_slide'), 'hint' => admin_t('db.hint_video_slides'), 'url' => '/admin/video/slides'],
            'friend_links' => ['group' => 'site', 'label' => admin_t('ui.friend_links'), 'hint' => admin_t('db.hint_friend_links'), 'url' => '/admin/video/links'],
            'video_websites' => ['group' => 'site', 'label' => admin_t('ui.websites_nav'), 'hint' => admin_t('db.hint_video_websites'), 'url' => '/admin/video/websites'],
            'video_domains' => ['group' => 'site', 'label' => admin_t('ui.domains'), 'hint' => admin_t('db.hint_video_domains'), 'url' => '/admin/video/domains'],
            'video_options' => ['group' => 'site', 'label' => admin_t('db.tbl_video_options'), 'hint' => admin_t('db.hint_video_options'), 'url' => '/admin/video/settings'],
            'video_search_words' => ['group' => 'site', 'label' => admin_t('ui.searchwords'), 'hint' => admin_t('db.hint_video_search_words'), 'url' => '/admin/video/searchwords'],
            'video_ulogs' => ['group' => 'stats', 'label' => admin_t('db.tbl_video_ulogs'), 'hint' => admin_t('db.hint_video_ulogs'), 'url' => '/admin/video/members'],
            'video_visit_days' => ['group' => 'stats', 'label' => admin_t('db.tbl_video_visit_days'), 'hint' => admin_t('db.hint_video_visit_days'), 'url' => '/admin/stats'],
            'video_visit_items' => ['group' => 'stats', 'label' => admin_t('db.tbl_video_visit_items'), 'hint' => admin_t('db.hint_video_visit_items'), 'url' => '/admin/stats'],
            'video_access_logs' => ['group' => 'stats', 'label' => admin_t('db.tbl_video_access_logs'), 'hint' => admin_t('db.hint_video_access_logs'), 'url' => '/admin/system/runtime?desk=access&view=logs'],
            'stat_hits' => ['group' => 'stats', 'label' => admin_t('db.tbl_stat_hits'), 'hint' => admin_t('db.hint_stat_hits'), 'url' => '/admin/stats'],
            'plugin_mangas' => ['group' => 'manga', 'label' => admin_t('db.tbl_plugin_mangas'), 'hint' => admin_t('db.hint_plugin_mangas'), 'url' => '/admin/video/mangas'],
            'plugin_manga_chapters' => ['group' => 'manga', 'label' => admin_t('db.tbl_plugin_manga_chapters'), 'hint' => admin_t('db.hint_plugin_manga_chapters'), 'url' => '/admin/video/mangas?desk=chapters'],
            'plugin_manga_types' => ['group' => 'manga', 'label' => admin_t('ui.title_types_manga'), 'hint' => admin_t('db.hint_plugin_manga_types'), 'url' => '/admin/video/manga-types'],
            'plugin_manga_tags' => ['group' => 'manga', 'label' => admin_t('db.tbl_plugin_manga_tags'), 'hint' => admin_t('db.hint_plugin_manga_tags'), 'url' => '/admin/video/manga-tags'],
            'plugin_manga_authors' => ['group' => 'manga', 'label' => admin_t('db.tbl_plugin_manga_authors'), 'hint' => admin_t('db.hint_plugin_manga_authors'), 'url' => '/admin/video/manga-authors'],
            'plugin_manga_pics' => ['group' => 'manga', 'label' => admin_t('db.tbl_plugin_manga_pics'), 'hint' => admin_t('db.hint_plugin_manga_pics'), 'url' => '/admin/video/mangas?desk=pics'],
            'plugin_manga_comments' => ['group' => 'manga', 'label' => admin_t('db.tbl_plugin_manga_comments'), 'hint' => admin_t('db.hint_plugin_manga_comments'), 'url' => '/admin/video/mangas?desk=comments'],
            'plugin_manga_favors' => ['group' => 'manga', 'label' => admin_t('db.tbl_plugin_manga_favors'), 'hint' => admin_t('db.hint_plugin_manga_favors'), 'url' => '/admin/video/mangas?desk=favors'],
            'plugin_manga_histories' => ['group' => 'manga', 'label' => admin_t('db.tbl_plugin_manga_histories'), 'hint' => admin_t('db.hint_plugin_manga_histories'), 'url' => '/admin/video/mangas'],
            'plugin_novels' => ['group' => 'novel', 'label' => admin_t('db.tbl_plugin_novels'), 'hint' => admin_t('db.hint_plugin_novels'), 'url' => '/admin/video/novels'],
            'plugin_novel_chapters' => ['group' => 'novel', 'label' => admin_t('db.tbl_plugin_novel_chapters'), 'hint' => admin_t('db.hint_plugin_novel_chapters'), 'url' => '/admin/video/novels?desk=chapters'],
            'plugin_novel_types' => ['group' => 'novel', 'label' => admin_t('db.tbl_plugin_novel_types'), 'hint' => admin_t('db.hint_plugin_novel_types'), 'url' => '/admin/video/novels?desk=types'],
            'plugin_novel_tags' => ['group' => 'novel', 'label' => admin_t('db.tbl_plugin_novel_tags'), 'hint' => admin_t('db.hint_plugin_novel_tags'), 'url' => '/admin/video/novel-tags'],
            'plugin_novel_authors' => ['group' => 'novel', 'label' => admin_t('db.tbl_plugin_novel_authors'), 'hint' => admin_t('db.hint_plugin_novel_authors'), 'url' => '/admin/video/novel-authors'],
            'plugin_novel_comments' => ['group' => 'novel', 'label' => admin_t('db.tbl_plugin_novel_comments'), 'hint' => admin_t('db.hint_plugin_novel_comments'), 'url' => '/admin/video/novels?desk=comments'],
            'plugin_novel_favors' => ['group' => 'novel', 'label' => admin_t('db.tbl_plugin_novel_favors'), 'hint' => admin_t('db.hint_plugin_novel_favors'), 'url' => '/admin/video/novels?desk=favors'],
            'plugin_novel_histories' => ['group' => 'novel', 'label' => admin_t('db.tbl_plugin_novel_histories'), 'hint' => admin_t('db.hint_plugin_novel_histories'), 'url' => '/admin/video/novels'],
            'plugin_galleries' => ['group' => 'gallery', 'label' => admin_t('db.group_gallery'), 'hint' => admin_t('db.hint_plugin_galleries'), 'url' => '/admin/video/galleries'],
            'plugin_gallery_pics' => ['group' => 'gallery', 'label' => admin_t('db.tbl_plugin_gallery_pics'), 'hint' => admin_t('db.hint_plugin_gallery_pics'), 'url' => '/admin/video/galleries?desk=pics'],
            'plugin_gallery_types' => ['group' => 'gallery', 'label' => admin_t('db.tbl_plugin_gallery_types'), 'hint' => admin_t('db.hint_plugin_gallery_types'), 'url' => '/admin/video/galleries?desk=types'],
            'plugin_gallery_tags' => ['group' => 'gallery', 'label' => admin_t('db.tbl_plugin_gallery_tags'), 'hint' => admin_t('db.hint_plugin_gallery_tags'), 'url' => '/admin/video/gallery-tags'],
            'plugin_gallery_authors' => ['group' => 'gallery', 'label' => admin_t('db.tbl_plugin_gallery_authors'), 'hint' => admin_t('db.hint_plugin_gallery_authors'), 'url' => '/admin/video/gallery-authors'],
            'plugin_gallery_comments' => ['group' => 'gallery', 'label' => admin_t('db.tbl_plugin_gallery_comments'), 'hint' => admin_t('db.hint_plugin_gallery_comments'), 'url' => '/admin/video/galleries?desk=comments'],
            'plugin_gallery_favors' => ['group' => 'gallery', 'label' => admin_t('db.tbl_plugin_gallery_favors'), 'hint' => admin_t('db.hint_plugin_gallery_favors'), 'url' => '/admin/video/galleries?desk=favors'],
            'plugin_live_channels' => ['group' => 'live', 'label' => admin_t('db.tbl_plugin_live_channels'), 'hint' => admin_t('db.hint_plugin_live_channels'), 'url' => '/admin/video/lives'],
            'plugin_live_categories' => ['group' => 'live', 'label' => admin_t('db.tbl_plugin_live_categories'), 'hint' => admin_t('db.hint_plugin_live_categories'), 'url' => '/admin/video/lives?desk=categories'],
            'plugin_mall_goods' => ['group' => 'plugin', 'label' => admin_t('db.tbl_plugin_mall_goods'), 'hint' => admin_t('db.hint_plugin_mall_goods'), 'url' => '/admin/plugins'],
            'plugin_mall_orders' => ['group' => 'plugin', 'label' => admin_t('db.tbl_plugin_mall_orders'), 'hint' => admin_t('db.hint_plugin_mall_orders'), 'url' => '/admin/plugins'],
            'plugin_friend_links' => ['group' => 'plugin', 'label' => admin_t('ui.friend_links'), 'hint' => admin_t('db.hint_plugin_friend_links'), 'url' => '/admin/plugins'],
            'plugin_friend_link_cates' => ['group' => 'plugin', 'label' => admin_t('db.tbl_plugin_friend_link_cates'), 'hint' => admin_t('db.hint_plugin_friend_link_cates'), 'url' => '/admin/plugins'],
            'plugin_friend_link_clicks' => ['group' => 'plugin', 'label' => admin_t('db.tbl_plugin_friend_link_clicks'), 'hint' => admin_t('db.hint_plugin_friend_link_clicks'), 'url' => '/admin/plugins'],
            'plugin_friend_link_hits' => ['group' => 'plugin', 'label' => admin_t('db.tbl_plugin_friend_link_hits'), 'hint' => admin_t('db.hint_plugin_friend_link_hits'), 'url' => '/admin/plugins'],
            'plugin_friend_link_options' => ['group' => 'plugin', 'label' => admin_t('db.tbl_plugin_friend_link_options'), 'hint' => admin_t('db.hint_plugin_friend_link_options'), 'url' => '/admin/plugins'],
            'plugin_ads' => ['group' => 'plugin', 'label' => admin_t('ui.col_ad'), 'hint' => admin_t('db.hint_plugin_ads'), 'url' => '/admin/plugins'],
            'plugin_ad_clicks' => ['group' => 'plugin', 'label' => admin_t('db.tbl_plugin_ad_clicks'), 'hint' => admin_t('db.hint_plugin_ad_clicks'), 'url' => '/admin/plugins'],
            'plugin_ad_days' => ['group' => 'plugin', 'label' => admin_t('db.tbl_plugin_ad_days'), 'hint' => admin_t('db.hint_plugin_ad_days'), 'url' => '/admin/plugins'],
            'plugin_publish_options' => ['group' => 'plugin', 'label' => admin_t('db.tbl_plugin_publish_options'), 'hint' => admin_t('db.hint_plugin_publish_options'), 'url' => '/admin/plugins'],
            'plugin_chat_messages' => ['group' => 'plugin', 'label' => admin_t('db.tbl_plugin_chat_messages'), 'hint' => admin_t('db.hint_plugin_chat_messages'), 'url' => '/admin/plugins'],
            'plugin_sms_codes' => ['group' => 'plugin', 'label' => admin_t('db.tbl_plugin_sms_codes'), 'hint' => admin_t('db.hint_plugin_sms_codes'), 'url' => '/admin/plugins'],
            'video_danmaku' => ['group' => 'plugin', 'label' => admin_t('db.tbl_video_danmaku'), 'hint' => admin_t('db.hint_video_danmaku'), 'url' => '/admin/plugins'],
            'sys_user' => ['group' => 'system', 'label' => admin_t('db.tbl_sys_user'), 'hint' => admin_t('db.hint_sys_user'), 'url' => '/admin/user'],
            'sys_user_log' => ['group' => 'system', 'label' => admin_t('db.tbl_sys_user_log'), 'hint' => admin_t('db.hint_sys_user_log'), 'url' => '/admin/system/monitor/login-logs'],
            'sys_user_role' => ['group' => 'system', 'label' => admin_t('db.tbl_sys_user_role'), 'hint' => admin_t('db.hint_sys_user_role'), 'url' => '/admin/user'],
            'sys_role' => ['group' => 'system', 'label' => admin_t('ui.cast'), 'hint' => admin_t('db.hint_sys_role'), 'url' => '/admin/system/roles'],
            'sys_perm' => ['group' => 'system', 'label' => admin_t('db.tbl_sys_perm'), 'hint' => admin_t('db.hint_sys_perm'), 'url' => '/admin/system/roles'],
            'sys_role_perm' => ['group' => 'system', 'label' => admin_t('db.tbl_sys_role_perm'), 'hint' => admin_t('db.hint_sys_role_perm'), 'url' => '/admin/system/roles'],
            'sys_schedule' => ['group' => 'system', 'label' => admin_t('db.tbl_sys_schedule'), 'hint' => admin_t('db.hint_sys_schedule'), 'url' => '/admin/system/tools/schedule'],
            'sys_schedule_log' => ['group' => 'system', 'label' => admin_t('db.tbl_sys_schedule_log'), 'hint' => admin_t('db.hint_sys_schedule_log'), 'url' => '/admin/system/tools/schedule'],
            'video_monitor_min' => ['group' => 'system', 'label' => admin_t('db.tbl_video_monitor_min'), 'hint' => admin_t('db.hint_video_monitor_min'), 'url' => '/admin/system/runtime'],
            'video_monitor_hour' => ['group' => 'system', 'label' => admin_t('db.tbl_video_monitor_hour'), 'hint' => admin_t('db.hint_video_monitor_hour'), 'url' => '/admin/system/runtime'],
            'video_monitor_state' => ['group' => 'system', 'label' => admin_t('db.tbl_video_monitor_state'), 'hint' => admin_t('db.hint_video_monitor_state'), 'url' => '/admin/system/runtime'],
            'video_monitor_rules' => ['group' => 'system', 'label' => admin_t('db.tbl_video_monitor_rules'), 'hint' => admin_t('db.hint_video_monitor_rules'), 'url' => '/admin/system/runtime?desk=rules'],
            'video_monitor_events' => ['group' => 'system', 'label' => admin_t('db.tbl_video_monitor_events'), 'hint' => admin_t('db.hint_video_monitor_events'), 'url' => '/admin/system/runtime?desk=events'],
            'sys_dict' => ['group' => 'system', 'label' => admin_t('db.tbl_sys_dict'), 'hint' => admin_t('db.hint_sys_dict'), 'url' => '/admin/system/dicts'],
            'sys_file' => ['group' => 'system', 'label' => admin_t('ui.files_title'), 'hint' => admin_t('db.hint_sys_file'), 'url' => '/admin/system/attachments'],
            'sys_operate_log' => ['group' => 'system', 'label' => admin_t('db.tbl_sys_operate_log'), 'hint' => admin_t('db.hint_sys_operate_log'), 'url' => '/admin/system/monitor/operate-logs'],
            'sys_system_log' => ['group' => 'system', 'label' => admin_t('db.tbl_sys_system_log'), 'hint' => admin_t('db.hint_sys_system_log'), 'url' => '/admin/system/monitor/system-logs'],
            'users' => ['group' => 'framework', 'label' => admin_t('db.tbl_users'), 'hint' => admin_t('db.hint_users'), 'url' => ''],
            'password_reset_tokens' => ['group' => 'framework', 'label' => admin_t('db.tbl_password_reset_tokens'), 'hint' => admin_t('db.hint_password_reset_tokens'), 'url' => ''],
            'sessions' => ['group' => 'framework', 'label' => admin_t('db.tbl_sessions'), 'hint' => admin_t('db.hint_sessions'), 'url' => ''],
            'cache' => ['group' => 'framework', 'label' => admin_t('db.tbl_cache'), 'hint' => admin_t('db.hint_cache'), 'url' => '/admin/system/tools/cache'],
            'cache_locks' => ['group' => 'framework', 'label' => admin_t('db.tbl_cache_locks'), 'hint' => admin_t('db.hint_cache_locks'), 'url' => '/admin/system/tools/cache'],
            'jobs' => ['group' => 'framework', 'label' => admin_t('db.tbl_jobs'), 'hint' => admin_t('db.hint_jobs'), 'url' => ''],
            'job_batches' => ['group' => 'framework', 'label' => admin_t('db.tbl_job_batches'), 'hint' => admin_t('db.hint_job_batches'), 'url' => ''],
            'failed_jobs' => ['group' => 'framework', 'label' => admin_t('db.tbl_failed_jobs'), 'hint' => admin_t('db.hint_failed_jobs'), 'url' => ''],
            'migrations' => ['group' => 'framework', 'label' => admin_t('db.tbl_migrations'), 'hint' => admin_t('db.hint_migrations'), 'url' => ''],
        ];
    }

    public function tableMeta(string $name): array
    {
        $known = $this->tables()[$name] ?? null;
        if ($known === null) {
            $auto = $this->guessPluginContentGroup($name);
            if ($auto !== null) {
                $groups = $this->groups();

                return [
                    'group' => $auto,
                    'group_label' => $groups[$auto] ?? $auto,
                    'label' => $name,
                    'hint' => admin_t('db.hint_plugin_content'),
                    'url' => match ($auto) {
                        'manga' => '/admin/video/mangas',
                        'novel' => '/admin/video/novels',
                        'gallery' => '/admin/video/galleries',
                        'live' => '/admin/video/lives',
                        default => '/admin/plugins',
                    },
                    'known' => false,
                ];
            }
            $plugin = str_starts_with($name, 'plugin_');

            return [
                'group' => $plugin ? 'plugin' : 'other',
                'group_label' => $plugin ? admin_t('db.group_plugin') : admin_t('db.group_other'),
                'label' => $name,
                'hint' => $plugin
                    ? admin_t('db.hint_plugin_unknown')
                    : admin_t('db.hint_other_unknown'),
                'url' => $plugin ? '/admin/plugins' : '',
                'known' => false,
            ];
        }
        $groups = $this->groups();

        return [
            'group' => $known['group'],
            'group_label' => $groups[$known['group']] ?? $known['group'],
            'label' => $known['label'],
            'hint' => $known['hint'],
            'url' => $known['url'],
            'known' => true,
        ];
    }

    private function guessPluginContentGroup(string $name): ?string
    {
        return match (true) {
            str_starts_with($name, 'plugin_manga') => 'manga',
            str_starts_with($name, 'plugin_novel') => 'novel',
            str_starts_with($name, 'plugin_gallery') => 'gallery',
            str_starts_with($name, 'plugin_live') => 'live',
            default => null,
        };
    }

    public function fieldPurpose(string $table, string $field): string
    {
        $field = trim($field);
        $specific = $this->tableFields()[$table][$field] ?? null;
        if (is_string($specific) && $specific !== '') {
            return $specific;
        }
        $common = $this->commonFields()[$field] ?? null;
        if (is_string($common) && $common !== '') {
            return $common;
        }

        return $this->guessField($field);
    }

    /** @return array<string, string> */
    public function commonFields(): array
    {
        return [
            'id' => admin_t('db.cf_id'),
            'created_at' => admin_t('db.cf_created_at'),
            'updated_at' => admin_t('db.cf_updated_at'),
            'create_time' => admin_t('db.cf_create_time'),
            'update_time' => admin_t('db.cf_update_time'),
            'create_at' => admin_t('db.cf_create_at'),
            'update_at' => admin_t('db.cf_update_at'),
            'deleted_at' => admin_t('db.cf_deleted_at'),
            'status' => admin_t('db.cf_status'),
            'sort' => admin_t('db.cf_sort'),
            'name' => admin_t('ui.name'),
            'title' => admin_t('ui.label_title'),
            'slug' => admin_t('db.cf_slug'),
            'cover' => admin_t('db.cf_cover'),
            'pic' => admin_t('ui.ph_pic'),
            'url' => admin_t('db.cf_url'),
            'content' => admin_t('db.cf_content'),
            'remark' => admin_t('ui.remarks'),
            'remarks' => admin_t('db.cf_remarks'),
            'note' => admin_t('ui.note_col'),
            'blurb' => admin_t('db.cf_blurb'),
            'description' => admin_t('ui.intro'),
            'ip' => 'IP',
            'login_ip' => admin_t('db.cf_login_ip'),
            'ip_address' => admin_t('db.cf_ip_address'),
            'member_id' => admin_t('db.cf_member_id'),
            'video_id' => admin_t('db.cf_video_id'),
            'type_id' => admin_t('db.cf_type_id'),
            'parent_id' => admin_t('db.cf_parent_id'),
            'user_id' => admin_t('db.cf_user_id'),
            'role_id' => admin_t('db.cf_role_id'),
            'hits' => admin_t('db.cf_hits'),
            'password' => admin_t('db.cf_password'),
            'email' => admin_t('ui.email'),
            'username' => admin_t('ui.login_name'),
            'token' => admin_t('db.cf_token'),
            'uid' => admin_t('db.cf_uid'),
            'code' => admin_t('db.cf_code'),
            'label' => admin_t('db.cf_label'),
            'icon' => admin_t('db.cf_icon'),
            'method' => admin_t('db.cf_method'),
            'module' => admin_t('db.cf_module'),
            'level' => admin_t('db.cf_level'),
            'points' => admin_t('ui.points'),
            'amount' => admin_t('db.cf_amount'),
            'avatar' => admin_t('db.cf_avatar'),
            'logo' => admin_t('db.cf_logo'),
            'banner' => admin_t('db.cf_banner'),
            'area' => admin_t('ui.area'),
            'lang' => admin_t('ui.lang_label'),
            'year' => admin_t('db.cf_year'),
            'letter' => admin_t('db.cf_letter'),
            'seo_title' => admin_t('ui.seo_title'),
            'seo_keywords' => admin_t('db.cf_seo_keywords'),
            'seo_description' => admin_t('ui.seo_des'),
            'seo_key' => admin_t('db.cf_seo_keywords'),
            'seo_des' => admin_t('ui.seo_des'),
            'tpl' => admin_t('db.cf_tpl'),
            'parse' => admin_t('db.cf_parse'),
            'engine' => admin_t('db.cf_engine'),
            'is_read' => admin_t('db.cf_is_read'),
            'is_bot' => admin_t('db.cf_is_bot'),
            'is_spider' => admin_t('db.cf_is_spider'),
            'is_recommend' => admin_t('db.cf_is_recommend'),
            'is_hot' => admin_t('db.cf_is_hot'),
            'is_regex' => admin_t('db.cf_is_regex'),
            'remember_token' => admin_t('db.cf_remember_token'),
            'email_verified_at' => admin_t('db.cf_email_verified_at'),
            'payload' => admin_t('db.cf_payload'),
            'user_agent' => admin_t('db.cf_user_agent'),
            'ua' => admin_t('db.cf_user_agent'),
            'referer' => admin_t('db.cf_referer'),
            'locale' => admin_t('db.cf_locale'),
            'path' => admin_t('ui.path_col'),
            'query' => admin_t('db.cf_query'),
            'host' => admin_t('db.cf_host'),
            'theme' => admin_t('db.cf_theme'),
            'slot' => admin_t('db.cf_slot'),
            'msg' => admin_t('db.cf_msg'),
            'last_msg' => admin_t('db.cf_last_msg'),
            'last_error' => admin_t('db.cf_last_error'),
            'expire_at' => admin_t('db.cf_expire_at'),
            'used_by' => admin_t('db.cf_used_by'),
            'used_at' => admin_t('db.cf_used_at'),
            'from_id' => admin_t('db.cf_from_id'),
            'to_id' => admin_t('db.cf_to_id'),
            'order_no' => admin_t('db.cf_order_no'),
            'trade_no' => admin_t('db.cf_trade_no'),
            'channel' => admin_t('db.cf_channel'),
            'account' => admin_t('db.cf_account'),
            'group_id' => admin_t('db.cf_group_id'),
            'collect_source_id' => admin_t('db.cf_collect_source_id'),
            'collect_id' => admin_t('db.cf_collect_id'),
            'source_id' => admin_t('db.cf_source_id'),
            'episode_id' => admin_t('db.cf_episode_id'),
            'episode_num' => admin_t('db.cf_episode_num'),
            'episode_name' => admin_t('db.cf_episode_name'),
            'actor_id' => admin_t('db.cf_actor_id'),
            'tag_id' => admin_t('db.cf_tag_id'),
            'topic_id' => admin_t('db.cf_topic_id'),
            'art_id' => admin_t('db.cf_art_id'),
            'perm_id' => admin_t('db.cf_perm_id'),
            'server_id' => admin_t('db.cf_server_id'),
            'type_pid' => admin_t('db.cf_type_pid'),
            'hits_day' => admin_t('db.cf_hits_day'),
            'hits_week' => admin_t('db.cf_hits_week'),
            'hits_month' => admin_t('db.cf_hits_month'),
            'score' => admin_t('ui.score'),
            'score_all' => admin_t('db.cf_score_all'),
            'score_num' => admin_t('db.cf_score_num'),
            'up' => admin_t('db.cf_up'),
            'down' => admin_t('db.cf_down'),
            'pv' => admin_t('db.cf_pv'),
            'uv' => admin_t('db.cf_uv'),
            'day' => admin_t('db.cf_day'),
            'weekday' => admin_t('db.cf_weekday'),
            'publish_at' => admin_t('db.cf_publish_at'),
            'published_at' => admin_t('db.cf_published_at'),
            'duration' => admin_t('ui.duration'),
            'subtitle' => admin_t('ui.subtitle'),
            'director' => admin_t('ui.director'),
            'writer' => admin_t('db.cf_writer'),
            'serial' => admin_t('db.cf_serial'),
            'total' => admin_t('db.cf_total'),
            'isend' => admin_t('db.cf_isend'),
            'lock' => admin_t('db.cf_lock'),
            'class' => admin_t('db.cf_class'),
            'author_name' => admin_t('db.cf_author_name'),
            'reply' => admin_t('db.cf_reply'),
            'phone' => admin_t('db.cf_phone'),
            'qq_openid' => admin_t('db.cf_qq_openid'),
            'wechat_openid' => admin_t('db.cf_wechat_openid'),
            'last_login_at' => admin_t('db.cf_last_login_at'),
            'points_min' => admin_t('db.cf_points_min'),
            'trysee' => admin_t('db.cf_trysee'),
            'day_free' => admin_t('db.cf_day_free'),
            'need_login' => admin_t('db.cf_need_login'),
            'balance' => admin_t('db.cf_balance'),
            'from_word' => admin_t('db.cf_from_word'),
            'to_word' => admin_t('db.cf_to_word'),
            'words' => admin_t('db.cf_words'),
            'scope' => admin_t('db.cf_scope'),
            'action' => admin_t('db.cf_action'),
            'cron_expression' => admin_t('db.cf_cron_expression'),
            'pages' => admin_t('db.cf_pages'),
            'hours' => admin_t('db.cf_hours'),
            'last_run_at' => admin_t('db.cf_last_run_at'),
            'last_collect_at' => admin_t('db.cf_last_collect_at'),
            'last_page' => admin_t('db.cf_last_page'),
            'last_created' => admin_t('db.cf_last_created'),
            'last_updated' => admin_t('db.cf_last_updated'),
            'page' => admin_t('db.cf_page'),
            'created_n' => admin_t('db.cf_created_n'),
            'updated_n' => admin_t('db.cf_updated_n'),
            'skipped_n' => admin_t('db.cf_skipped_n'),
            'ok' => admin_t('db.cf_ok'),
            'api_url' => admin_t('ui.json_url'),
            'api_type' => admin_t('db.cf_api_type'),
            'mid' => admin_t('db.cf_mid'),
            'param' => admin_t('db.cf_param'),
            'bind_json' => admin_t('db.cf_bind_json'),
            'list_rule' => admin_t('db.cf_list_rule'),
            'title_rule' => admin_t('db.cf_title_rule'),
            'url_rule' => admin_t('db.cf_url_rule'),
            'content_rule' => admin_t('db.cf_content_rule'),
            'downer' => admin_t('db.cf_downer'),
            'player' => admin_t('db.cf_player'),
            'type' => admin_t('db.cf_type'),
            'k' => admin_t('db.cf_k'),
            'v' => admin_t('db.cf_v'),
            'dict_type' => admin_t('db.cf_dict_type'),
            'dict_key' => admin_t('db.cf_dict_key'),
            'value_type' => admin_t('db.cf_value_type'),
            'value_string' => admin_t('db.cf_value_string'),
            'value_int' => admin_t('db.cf_value_int'),
            'value_float' => admin_t('db.cf_value_float'),
            'value_json' => admin_t('db.cf_value_json'),
            'value_text' => admin_t('db.cf_value_text'),
            'enum_limit' => admin_t('db.cf_enum_limit'),
            'size' => admin_t('db.cf_size'),
            'md5' => admin_t('db.cf_md5'),
            'mime' => admin_t('db.cf_mime'),
            'file' => admin_t('db.cf_file'),
            'line' => admin_t('db.cf_line'),
            'trace' => admin_t('db.cf_trace'),
            'message' => admin_t('db.cf_message'),
            'context' => admin_t('db.cf_context'),
            'extra' => admin_t('db.cf_extra'),
            'exception_class' => admin_t('db.cf_exception_class'),
            'exception_message' => admin_t('db.cf_exception_message'),
            'request_id' => admin_t('db.cf_request_id'),
            'request_data' => admin_t('db.cf_request_data'),
            'response_code' => admin_t('db.cf_response_code'),
            'response_msg' => admin_t('db.cf_response_msg'),
            'duration_ms' => admin_t('db.cf_duration_ms'),
            'target_type' => admin_t('db.cf_target_type'),
            'target_id' => admin_t('db.cf_target_id'),
            'permission' => admin_t('db.cf_permission'),
            'route' => admin_t('db.cf_route'),
            'login_agent' => admin_t('db.cf_login_agent'),
            'role' => admin_t('db.cf_role'),
            'login_time' => admin_t('db.cf_login_time'),
            'ui_locale' => admin_t('db.cf_ui_locale'),
            'pid' => admin_t('db.cf_pid'),
            'api' => admin_t('db.cf_api'),
            'command' => admin_t('db.cf_command'),
            'params' => admin_t('db.cf_params'),
            'timezone' => admin_t('db.cf_timezone'),
            'without_overlapping' => admin_t('db.cf_without_overlapping'),
            'on_one_server' => admin_t('db.cf_on_one_server'),
            'run_in_maintenance' => admin_t('db.cf_run_in_maintenance'),
            'timeout' => admin_t('db.cf_timeout'),
            'max_attempts' => admin_t('db.cf_max_attempts'),
            'last_run_time' => admin_t('db.cf_last_run_at'),
            'last_status' => admin_t('db.cf_last_status'),
            'next_run_time' => admin_t('db.cf_next_run_time'),
            'key' => admin_t('db.cf_key'),
            'value' => admin_t('db.cf_value'),
            'expiration' => admin_t('db.cf_expiration'),
            'owner' => admin_t('db.cf_owner'),
            'queue' => admin_t('db.cf_queue'),
            'attempts' => admin_t('db.cf_attempts'),
            'reserved_at' => admin_t('db.cf_reserved_at'),
            'available_at' => admin_t('db.cf_available_at'),
            'uuid' => admin_t('db.cf_uuid'),
            'connection' => admin_t('db.cf_connection'),
            'exception' => admin_t('db.cf_exception'),
            'failed_at' => admin_t('db.cf_failed_at'),
            'total_jobs' => admin_t('db.cf_total_jobs'),
            'pending_jobs' => admin_t('db.cf_pending_jobs'),
            'failed_jobs' => admin_t('db.cf_failed_jobs'),
            'failed_job_ids' => admin_t('db.cf_failed_job_ids'),
            'options' => admin_t('db.cf_options'),
            'cancelled_at' => admin_t('db.cf_cancelled_at'),
            'finished_at' => admin_t('db.cf_finished_at'),
            'visitor_hash' => admin_t('db.cf_visitor_hash'),
            'status_code' => admin_t('db.cf_status_code'),
            'spider_name' => admin_t('db.cf_spider_name'),
            'min_points' => admin_t('db.cf_min_points'),
            'day_key' => admin_t('db.cf_day_key'),
            'days' => admin_t('db.cf_days'),
            'word' => admin_t('ui.searchwords'),
            'cover_thumb' => admin_t('db.cf_cover_thumb'),
            'cover_slide' => admin_t('db.cf_cover_slide'),
            'sub' => admin_t('ui.subtitle'),
            'color' => admin_t('db.cf_color'),
            'tag' => admin_t('db.cf_tag'),
            'extend' => admin_t('db.cf_extend'),
            'time_hits' => admin_t('db.cf_time_hits'),
            'tpl_list' => admin_t('db.cf_tpl_list'),
            'tpl_detail' => admin_t('db.cf_tpl_detail'),
            'tpl_play' => admin_t('db.cf_tpl_play'),
            'douban_id' => admin_t('db.cf_douban_id'),
            'douban_score' => admin_t('db.cf_douban_score'),
            'comment_up' => admin_t('db.cf_comment_up'),
            'comment_report' => admin_t('db.cf_comment_report'),
            'role_type' => admin_t('db.cf_role_type'),
            'sex' => admin_t('ui.gender'),
            'birthday' => admin_t('ui.birthday'),
            'author' => admin_t('ui.authors'),
            'pics' => admin_t('db.cf_pics'),
            'stock' => admin_t('db.cf_stock'),
            'hint' => admin_t('db.cf_hint'),
            'goods_id' => admin_t('db.cf_goods_id'),
            'goods_name' => admin_t('db.cf_goods_name'),
            'text' => admin_t('db.cf_text'),
            'scene' => admin_t('db.cf_scene'),
            'manga_id' => admin_t('db.cf_manga_id'),
            'chapter_id' => admin_t('db.cf_chapter_id'),
            'mode' => admin_t('db.cf_mode'),
            'last_activity' => admin_t('db.cf_last_activity'),
            'recommend' => admin_t('ui.recommend'),
            'tags' => admin_t('ui.tags'),
            'serialize' => admin_t('db.tf_plugin_mangas_serialize'),
            'yid' => admin_t('db.tf_plugin_mangas_yid'),
            'vip' => admin_t('db.tf_plugin_manga_chapters_vip'),
            'progress' => admin_t('db.tf_member_task_logs_progress'),
            'play_from' => admin_t('ui.play_from'),
            'ext' => admin_t('db.cf_extend'),
            'sales' => admin_t('ui.sales'),
            'driver' => admin_t('ui.driver'),
            'mch_id' => admin_t('ui.mch_id'),
            'app_key' => admin_t('db.cf_app_key'),
            'min_fen' => admin_t('db.cf_min_fen'),
            'max_fen' => admin_t('db.cf_max_fen'),
            'min_price' => admin_t('db.cf_min_price'),
            'goods_type' => admin_t('db.cf_goods_type'),
            'delivery' => admin_t('db.cf_delivery'),
            'contact' => admin_t('db.cf_contact'),
            'address' => admin_t('db.cf_address'),
            'used' => admin_t('ui.used'),
            'received' => admin_t('ui.received'),
            'per_user' => admin_t('db.cf_per_user'),
            'target' => admin_t('db.cf_target'),
            'image' => admin_t('ui.image'),
            'referer_day' => admin_t('db.cf_referer_day'),
            'referer_month' => admin_t('db.cf_referer_month'),
            'referer_year' => admin_t('db.cf_referer_year'),
            'month_key' => admin_t('db.cf_month_key'),
            'year_key' => admin_t('db.cf_year_key'),
            'from_url' => admin_t('db.cf_from_url'),
        ];
    }

    /**
     * @return array<string, array<string, string>>
     */
    public function tableFields(): array
    {
        return [
            'videos' => [
                'title' => admin_t('db.tf_videos_title'),
                'status' => admin_t('db.tf_videos_status'),
                'type' => admin_t('db.tf_videos_type'),
                'seo_title' => admin_t('ui.seo_title'),
                'seo_keywords' => admin_t('db.cf_seo_keywords'),
                'seo_description' => admin_t('ui.seo_des'),
            ],
            'video_types' => [
                'mid' => admin_t('db.tf_video_types_mid'),
                'kind' => admin_t('db.tf_video_types_kind'),
                'jump_url' => admin_t('db.tf_video_types_jump_url'),
                'page_size' => admin_t('db.tf_video_types_page_size'),
                'status' => admin_t('db.tf_video_types_status'),
            ],
            'video_sources' => [
                'name' => admin_t('db.tf_video_sources_name'),
                'type' => admin_t('db.tf_video_sources_type'),
                'status' => admin_t('db.tf_video_sources_status'),
            ],
            'video_episodes' => [
                'url' => admin_t('db.tf_video_episodes_url'),
                'duration' => admin_t('db.tf_video_episodes_duration'),
            ],
            'video_players' => [
                'code' => admin_t('db.tf_video_players_code'),
                'parse' => admin_t('db.tf_video_players_parse'),
            ],
            'video_roles' => [
                'name' => admin_t('ui.role_name'),
                'video_id' => admin_t('db.tf_video_roles_video_id'),
                'actor_id' => admin_t('db.tf_video_roles_actor_id'),
            ],
            'video_actor_rel' => [
                'role_type' => admin_t('db.tf_video_actor_rel_role_type'),
            ],
            'sys_user' => [
                'role' => admin_t('db.tf_sys_user_role'),
                'token' => admin_t('db.tf_sys_user_token'),
                'status' => admin_t('db.tf_sys_user_status'),
            ],
            'sys_role' => [
                'code' => admin_t('db.tf_sys_role_code'),
                'status' => admin_t('db.tf_sys_role_status'),
            ],
            'sys_perm' => [
                'type' => admin_t('db.tf_sys_perm_type'),
                'code' => admin_t('db.cf_permission'),
            ],
            'sys_schedule' => [
                'type' => 'artisan / http / shell',
                'status' => admin_t('db.tf_sys_schedule_status'),
                'code' => admin_t('db.tf_sys_schedule_code'),
                'last_duration_ms' => admin_t('db.tf_sys_schedule_last_duration_ms'),
            ],
            'sys_schedule_log' => [
                'schedule_id' => admin_t('db.tf_sys_schedule_log_schedule_id'),
                'status' => admin_t('db.tf_sys_schedule_log_status'),
                'duration_ms' => admin_t('db.tf_sys_schedule_log_duration_ms'),
                'output' => admin_t('db.tf_sys_schedule_log_output'),
                'error' => admin_t('db.tf_sys_schedule_log_error'),
                'create_time' => admin_t('db.tf_sys_schedule_log_create_time'),
            ],
            'video_monitor_min' => [
                'metric_key' => admin_t('db.tf_video_monitor_min_metric_key'),
                'stat_min' => admin_t('db.tf_video_monitor_min_stat_min'),
                'metric_type' => admin_t('db.tf_video_monitor_min_metric_type'),
                'metric_value' => admin_t('db.tf_video_monitor_min_metric_value'),
            ],
            'video_monitor_hour' => [
                'metric_key' => admin_t('db.tf_video_monitor_hour_metric_key'),
                'stat_hour' => admin_t('db.tf_video_monitor_hour_stat_hour'),
                'val_avg' => admin_t('db.tf_video_monitor_hour_val_avg'),
                'val_max' => admin_t('db.tf_video_monitor_hour_val_max'),
                'val_min' => admin_t('db.tf_video_monitor_hour_val_min'),
                'val_sum' => admin_t('db.tf_video_monitor_hour_val_sum'),
                'sample_cnt' => admin_t('db.tf_video_monitor_hour_sample_cnt'),
            ],
            'video_monitor_state' => [
                'state_key' => admin_t('db.tf_video_monitor_state_state_key'),
                'state_num' => admin_t('db.tf_video_monitor_state_state_num'),
                'state_val' => admin_t('db.tf_video_monitor_state_state_val'),
            ],
            'video_monitor_rules' => [
                'metric_key' => admin_t('db.tf_video_monitor_rules_metric_key'),
                'agg' => admin_t('db.tf_video_monitor_rules_agg'),
                'window_min' => admin_t('db.tf_video_monitor_rules_window_min'),
                'op' => admin_t('db.tf_video_monitor_rules_op'),
                'threshold' => admin_t('ui.threshold'),
                'for_min' => admin_t('db.tf_video_monitor_rules_for_min'),
                'silence_min' => admin_t('db.tf_video_monitor_rules_silence_min'),
                'status' => admin_t('db.tf_video_monitor_rules_status'),
                'hint' => admin_t('db.tf_video_monitor_rules_hint'),
            ],
            'video_monitor_events' => [
                'fingerprint' => admin_t('db.tf_video_monitor_events_fingerprint'),
                'status' => admin_t('db.tf_video_monitor_events_status'),
                'message' => admin_t('db.tf_video_monitor_events_message'),
                'value' => admin_t('db.tf_video_monitor_events_value'),
                'opened_at' => admin_t('db.tf_video_monitor_events_opened_at'),
                'closed_at' => admin_t('db.tf_video_monitor_events_closed_at'),
                'acked_at' => admin_t('db.tf_video_monitor_events_acked_at'),
            ],
            'sys_dict' => [
                'status' => admin_t('db.tf_sys_dict_status'),
            ],
            'sys_operate_log' => [
                'title' => admin_t('db.tf_sys_operate_log_title'),
                'action' => admin_t('db.tf_sys_operate_log_action'),
                'status' => admin_t('db.tf_sys_operate_log_status'),
            ],
            'sys_system_log' => [
                'level' => admin_t('db.tf_sys_system_log_level'),
                'channel' => admin_t('db.tf_sys_system_log_channel'),
            ],
            'members' => [
                'name' => admin_t('db.tf_members_name'),
                'status' => admin_t('db.tf_members_status'),
                'points' => admin_t('db.tf_members_points'),
            ],
            'member_orders' => [
                'status' => admin_t('db.tf_member_orders_status'),
                'amount' => admin_t('db.tf_member_orders_amount'),
                'channel' => admin_t('db.tf_member_orders_channel'),
                'original_amount' => admin_t('db.tf_member_orders_original_amount'),
                'coupon_discount' => admin_t('db.tf_member_orders_coupon_discount'),
            ],
            'member_withdraws' => [
                'status' => admin_t('db.tf_member_withdraws_status'),
                'amount' => admin_t('db.tf_member_withdraws_amount'),
            ],
            'member_point_logs' => [
                'points' => admin_t('db.tf_member_point_logs_points'),
                'type' => admin_t('db.tf_member_point_logs_type'),
            ],
            'member_tasks' => [
                'action' => admin_t('db.tf_member_tasks_action'),
                'type' => admin_t('db.tf_member_tasks_type'),
                'status' => admin_t('db.tf_member_tasks_status'),
            ],
            'member_task_logs' => [
                'status' => admin_t('db.tf_member_task_logs_status'),
                'day_key' => admin_t('db.tf_member_task_logs_day_key'),
                'progress' => admin_t('db.tf_member_task_logs_progress'),
            ],
            'member_sign_milestones' => [
                'days' => admin_t('db.tf_member_sign_milestones_days'),
                'status' => admin_t('db.tf_member_tasks_status'),
            ],
            'member_pms' => [
                'title' => admin_t('db.tf_member_pms_title'),
            ],
            'video_comments' => [
                'status' => admin_t('db.tf_video_comments_status'),
                'parent_id' => admin_t('db.tf_video_comments_parent_id'),
                'mid' => admin_t('db.tf_video_comments_mid'),
                'video_id' => admin_t('db.tf_video_comments_video_id'),
            ],
            'video_reports' => [
                'status' => admin_t('db.tf_video_reports_status'),
                'content' => admin_t('db.tf_video_reports_content'),
            ],
            'video_play_fails' => [
                'status' => admin_t('db.tf_video_play_fails_status'),
                'content' => admin_t('db.tf_video_play_fails_content'),
                'url' => admin_t('db.tf_video_play_fails_url'),
            ],
            'video_guestbooks' => [
                'status' => admin_t('db.tf_video_types_status'),
            ],
            'video_ads' => [
                'content' => admin_t('db.tf_video_ads_content'),
                'type_id' => admin_t('db.tf_video_ads_type_id'),
            ],
            'video_collect_temps' => [
                'status' => admin_t('db.tf_video_collect_temps_status'),
                'payload' => admin_t('db.tf_video_collect_temps_payload'),
                'title' => admin_t('db.tf_video_collect_temps_title'),
            ],
            'video_collect_tasks' => [
                'status' => admin_t('db.tf_video_collect_tasks_status'),
            ],
            'video_cj_rules' => [
                'type' => admin_t('db.tf_video_cj_rules_type'),
                'status' => admin_t('db.tf_video_cj_rules_status'),
                'url' => admin_t('db.tf_video_cj_rules_url'),
                'list_rule' => admin_t('db.tf_video_cj_rules_list_rule'),
                'title_rule' => admin_t('db.tf_video_cj_rules_title_rule'),
                'url_rule' => admin_t('db.tf_video_cj_rules_url_rule'),
                'content_rule' => admin_t('db.tf_video_cj_rules_content_rule'),
                'options' => admin_t('db.tf_video_cj_rules_options'),
                'interval_minutes' => admin_t('db.tf_video_cj_rules_interval_minutes'),
                'limit_items' => admin_t('db.tf_video_cj_rules_limit_items'),
                'publish_immediately' => admin_t('db.tf_video_cj_rules_publish_immediately'),
                'last_run_at' => admin_t('db.tf_video_cj_rules_last_run_at'),
                'last_status' => admin_t('db.tf_video_cj_rules_last_status'),
                'last_message' => admin_t('db.tf_video_cj_rules_last_message'),
            ],
            'video_cj_rule_logs' => [
                'rule_id' => admin_t('db.tf_video_cj_rule_logs_rule_id'),
                'status' => admin_t('db.tf_video_cj_rule_logs_status'),
                'fetched' => admin_t('db.tf_video_cj_rule_logs_fetched'),
                'created' => admin_t('db.cf_created_n'),
                'skipped' => admin_t('db.tf_video_cj_rule_logs_skipped'),
                'message' => admin_t('db.tf_video_cj_rule_logs_message'),
            ],
            'video_ulogs' => [
                'type' => admin_t('db.tf_video_ulogs_type'),
            ],
            'video_options' => [
                'k' => admin_t('db.tf_video_options_k'),
                'v' => admin_t('db.tf_video_options_v'),
            ],
            'video_domains' => [
                'host' => admin_t('db.tf_video_domains_host'),
                'theme' => admin_t('db.tf_video_domains_theme'),
                'site_name' => admin_t('db.tf_video_domains_site_name'),
                'site_keyword' => admin_t('db.tf_video_domains_site_keyword'),
                'site_description' => admin_t('db.tf_video_domains_site_description'),
                'status' => admin_t('db.tf_video_domains_status'),
            ],
            'video_access_logs' => [
                'url' => admin_t('db.tf_video_access_logs_url'),
            ],
            'stat_hits' => [
                'path' => admin_t('db.tf_stat_hits_path'),
                'created_at' => admin_t('db.tf_stat_hits_created_at'),
            ],
            'sessions' => [
                'id' => admin_t('db.tf_sessions_id'),
                'user_id' => admin_t('db.tf_sessions_user_id'),
            ],
            'users' => [
                'name' => admin_t('db.tf_users_name'),
            ],
            'migrations' => [
                'migration' => admin_t('db.tf_migrations_migration'),
                'batch' => admin_t('db.tf_migrations_batch'),
            ],
            'video_topics' => [
                'type' => admin_t('db.tf_video_topics_type'),
                'tag' => admin_t('db.tf_video_topics_tag'),
            ],
            'video_arts' => [
                'status' => admin_t('db.tf_video_arts_status'),
                'blurb' => admin_t('ui.blurb'),
                'source' => admin_t('db.tf_video_arts_source'),
                'author' => admin_t('db.tf_video_arts_author'),
                'tag' => admin_t('db.tf_video_arts_tag'),
                'deleted_at' => admin_t('db.tf_video_arts_deleted_at'),
                'flags' => admin_t('db.tf_video_arts_flags'),
                'sort' => admin_t('db.tf_video_arts_sort'),
                'published_at' => admin_t('db.tf_video_arts_published_at'),
                'seo_title' => admin_t('db.tf_video_arts_seo_title'),
                'seo_key' => admin_t('db.tf_video_arts_seo_key'),
                'seo_des' => admin_t('db.tf_video_arts_seo_des'),
            ],
            'video_art_tags' => [
                'name' => admin_t('db.tf_video_art_tags_name'),
                'slug' => admin_t('db.tf_video_art_tags_slug'),
                'status' => admin_t('db.tf_video_art_tags_status'),
            ],
            'video_art_tag_rel' => [
                'art_id' => admin_t('db.tf_video_art_tag_rel_art_id'),
                'tag_id' => admin_t('db.tf_video_art_tag_rel_tag_id'),
            ],
            'member_follows' => [
                'target_type' => admin_t('db.tf_member_follows_target_type'),
            ],
            'member_dynamics' => [
                'type' => admin_t('db.tf_member_dynamics_type'),
            ],
            'video_audit_rules' => [
                'status' => admin_t('db.tf_video_audit_rules_status'),
            ],
            'video_danmaku' => [
                'text' => admin_t('db.tf_video_danmaku_text'),
                'color' => admin_t('db.tf_video_danmaku_color'),
                'time' => admin_t('db.tf_video_danmaku_time'),
                'mode' => admin_t('db.tf_video_danmaku_mode'),
                'status' => admin_t('db.tf_video_types_status'),
                'report' => admin_t('db.tf_video_danmaku_report'),
                'episode_id' => admin_t('db.tf_video_danmaku_episode_id'),
                'member_id' => admin_t('db.tf_video_danmaku_member_id'),
                'ip' => admin_t('db.tf_video_danmaku_ip'),
            ],
            'plugin_manga_chapters' => [
                'name' => admin_t('db.tf_plugin_manga_chapters_name'),
                'pics' => admin_t('db.tf_plugin_manga_chapters_pics'),
                'manga_id' => admin_t('db.tf_plugin_manga_chapters_manga_id'),
                'vip' => admin_t('db.tf_plugin_manga_chapters_vip'),
            ],
            'plugin_mangas' => [
                'title' => admin_t('db.tf_plugin_mangas_title'),
                'status' => admin_t('db.tf_plugin_mangas_status'),
                'type_id' => admin_t('db.tf_plugin_mangas_type_id'),
                'serialize' => admin_t('db.tf_plugin_mangas_serialize'),
                'tags' => admin_t('db.tf_plugin_mangas_tags'),
                'recommend' => admin_t('db.tf_plugin_mangas_recommend'),
                'yid' => admin_t('db.tf_plugin_mangas_yid'),
            ],
            'plugin_manga_types' => [
                'slug' => admin_t('ui.url_slug'),
                'pic' => admin_t('ui.cover'),
                'page_size' => admin_t('db.tf_video_types_page_size'),
                'seo_title' => admin_t('ui.seo_title_ns'),
                'seo_keywords' => admin_t('ui.seo_key_ns'),
                'seo_description' => admin_t('ui.seo_des_ns'),
            ],
            'plugin_manga_pics' => [
                'manga_id' => admin_t('db.tf_plugin_manga_chapters_manga_id'),
                'chapter_id' => admin_t('db.tf_plugin_manga_pics_chapter_id'),
                'url' => admin_t('db.tf_plugin_manga_pics_url'),
                'sort' => admin_t('db.tf_plugin_manga_pics_sort'),
            ],
            'plugin_manga_comments' => [
                'manga_id' => admin_t('db.tf_plugin_manga_chapters_manga_id'),
                'member_id' => admin_t('db.tf_plugin_manga_comments_member_id'),
                'author_name' => admin_t('db.tf_plugin_manga_comments_author_name'),
                'content' => admin_t('db.tf_plugin_manga_comments_content'),
                'status' => admin_t('db.tf_plugin_manga_comments_status'),
                'ip' => admin_t('db.tf_video_danmaku_ip'),
            ],
            'plugin_manga_favors' => [
                'member_id' => admin_t('db.tf_plugin_manga_favors_member_id'),
                'manga_id' => admin_t('db.tf_plugin_manga_favors_manga_id'),
            ],
            'plugin_manga_tags' => [
                'name' => admin_t('db.tf_plugin_manga_tags_name'),
                'slug' => admin_t('ui.url_slug'),
                'status' => admin_t('db.tf_video_types_status'),
            ],
            'plugin_manga_authors' => [
                'name' => admin_t('db.tf_plugin_manga_authors_name'),
                'slug' => admin_t('ui.url_slug'),
                'status' => admin_t('db.tf_video_types_status'),
            ],
            'plugin_manga_histories' => [
                'member_id' => admin_t('db.tf_plugin_manga_histories_member_id'),
                'manga_id' => admin_t('db.cf_manga_id'),
                'chapter_id' => admin_t('db.tf_plugin_manga_histories_chapter_id'),
            ],
            'plugin_novels' => [
                'title' => admin_t('db.tf_plugin_novels_title'),
                'status' => admin_t('db.tf_plugin_mangas_status'),
                'type_id' => admin_t('db.tf_plugin_novels_type_id'),
                'serialize' => admin_t('db.tf_plugin_mangas_serialize'),
                'tags' => admin_t('db.tf_plugin_mangas_tags'),
                'recommend' => admin_t('db.tf_plugin_mangas_recommend'),
                'yid' => admin_t('db.tf_plugin_novels_yid'),
            ],
            'plugin_novel_chapters' => [
                'name' => admin_t('ui.chapter_name'),
                'novel_id' => admin_t('db.tf_plugin_novel_chapters_novel_id'),
                'content' => admin_t('ui.ph_chapter_body'),
                'vip' => admin_t('db.tf_plugin_novel_chapters_vip'),
            ],
            'plugin_novel_types' => [
                'name' => admin_t('db.tf_plugin_manga_types_name'),
                'status' => admin_t('db.tf_video_types_status'),
            ],
            'plugin_novel_tags' => [
                'name' => admin_t('db.tf_plugin_manga_tags_name'),
                'slug' => admin_t('ui.url_slug'),
            ],
            'plugin_novel_authors' => [
                'name' => admin_t('db.tf_plugin_manga_authors_name'),
                'slug' => admin_t('ui.url_slug'),
            ],
            'plugin_novel_comments' => [
                'novel_id' => admin_t('db.tf_plugin_novel_chapters_novel_id'),
                'member_id' => admin_t('db.tf_plugin_manga_comments_member_id'),
                'content' => admin_t('db.tf_plugin_manga_comments_content'),
                'status' => admin_t('db.tf_plugin_novel_comments_status'),
            ],
            'plugin_novel_favors' => [
                'member_id' => admin_t('db.tf_plugin_manga_favors_member_id'),
                'novel_id' => admin_t('db.tf_plugin_novel_favors_novel_id'),
            ],
            'plugin_novel_histories' => [
                'member_id' => admin_t('db.tf_plugin_manga_histories_member_id'),
                'novel_id' => admin_t('db.tf_plugin_novel_histories_novel_id'),
                'chapter_id' => admin_t('db.tf_plugin_manga_histories_chapter_id'),
            ],
            'plugin_galleries' => [
                'title' => admin_t('db.tf_plugin_galleries_title'),
                'status' => admin_t('db.tf_plugin_mangas_status'),
                'type_id' => admin_t('db.tf_plugin_galleries_type_id'),
                'tags' => admin_t('db.tf_plugin_mangas_tags'),
                'yid' => admin_t('db.tf_plugin_novels_yid'),
            ],
            'plugin_gallery_pics' => [
                'gallery_id' => admin_t('db.tf_plugin_gallery_pics_gallery_id'),
                'url' => admin_t('ui.ph_pic'),
                'sort' => admin_t('db.tf_plugin_gallery_pics_sort'),
            ],
            'plugin_gallery_types' => [
                'name' => admin_t('db.tf_plugin_manga_types_name'),
                'status' => admin_t('db.tf_video_types_status'),
            ],
            'plugin_gallery_tags' => [
                'name' => admin_t('db.tf_plugin_manga_tags_name'),
                'slug' => admin_t('ui.url_slug'),
            ],
            'plugin_gallery_authors' => [
                'name' => admin_t('db.tf_plugin_gallery_authors_name'),
                'slug' => admin_t('ui.url_slug'),
            ],
            'plugin_gallery_comments' => [
                'gallery_id' => admin_t('db.tf_plugin_gallery_pics_gallery_id'),
                'member_id' => admin_t('db.tf_plugin_manga_comments_member_id'),
                'content' => admin_t('db.tf_plugin_manga_comments_content'),
                'status' => admin_t('db.tf_plugin_novel_comments_status'),
            ],
            'plugin_gallery_favors' => [
                'member_id' => admin_t('db.tf_plugin_manga_favors_member_id'),
                'gallery_id' => admin_t('db.tf_plugin_gallery_favors_gallery_id'),
            ],
            'plugin_live_channels' => [
                'title' => admin_t('db.tf_plugin_live_channels_title'),
                'urls' => admin_t('db.tf_plugin_live_channels_urls'),
                'cate_id' => admin_t('db.tf_plugin_live_channels_cate_id'),
                'status' => admin_t('db.tf_plugin_live_channels_status'),
                'recommend' => admin_t('db.tf_plugin_live_channels_recommend'),
            ],
            'plugin_live_categories' => [
                'name' => admin_t('db.tf_plugin_manga_types_name'),
                'slug' => admin_t('ui.url_slug'),
                'status' => admin_t('db.tf_video_art_tags_status'),
            ],
            'plugin_mall_goods' => [
                'points' => admin_t('db.tf_plugin_mall_goods_points'),
                'status' => admin_t('db.tf_plugin_mall_goods_status'),
                'type' => admin_t('db.tf_plugin_mall_goods_type'),
                'ext' => admin_t('db.tf_plugin_mall_goods_ext'),
                'sales' => admin_t('ui.sales'),
            ],
            'plugin_mall_orders' => [
                'status' => admin_t('db.tf_plugin_mall_orders_status'),
                'points' => admin_t('db.tf_plugin_mall_orders_points'),
                'goods_type' => admin_t('db.tf_plugin_mall_orders_goods_type'),
                'delivery' => admin_t('db.tf_plugin_mall_orders_delivery'),
                'contact' => admin_t('db.tf_plugin_mall_orders_contact'),
                'address' => admin_t('db.tf_plugin_mall_orders_address'),
            ],
            'plugin_pay_channels' => [
                'driver' => admin_t('ui.driver'),
                'mch_id' => admin_t('ui.mch_id'),
                'app_key' => admin_t('db.cf_app_key'),
                'min_fen' => admin_t('db.cf_min_fen'),
                'max_fen' => admin_t('db.cf_max_fen'),
            ],
            'plugin_coupons' => [
                'min_price' => admin_t('db.cf_min_price'),
                'per_user' => admin_t('db.cf_per_user'),
                'target' => admin_t('db.cf_target'),
                'received' => admin_t('ui.received'),
                'used' => admin_t('ui.used'),
            ],
            'plugin_friend_links' => [
                'status' => admin_t('db.tf_plugin_friend_links_status'),
                'type' => admin_t('db.tf_plugin_friend_links_type'),
                'referer_total' => admin_t('db.tf_plugin_friend_links_referer_total'),
                'clicks' => admin_t('db.tf_plugin_friend_links_clicks'),
                'edit_token' => admin_t('db.tf_plugin_friend_links_edit_token'),
            ],
            'plugin_friend_link_cates' => [
                'status' => admin_t('db.tf_video_types_status'),
            ],
            'plugin_friend_link_clicks' => [
                'link_id' => admin_t('db.tf_plugin_friend_link_clicks_link_id'),
                'ip' => admin_t('db.tf_plugin_friend_link_clicks_ip'),
            ],
            'plugin_friend_link_hits' => [
                'from_host' => admin_t('db.tf_plugin_friend_link_hits_from_host'),
                'day_key' => admin_t('db.tf_plugin_friend_link_hits_day_key'),
            ],
            'plugin_friend_link_options' => [
                'k' => admin_t('db.tf_plugin_friend_link_options_k'),
                'v' => admin_t('db.tf_plugin_friend_link_options_v'),
            ],
            'plugin_ads' => [
                'type' => admin_t('db.tf_plugin_ads_type'),
                'slot' => admin_t('db.tf_plugin_ads_slot'),
                'start_at' => admin_t('db.tf_plugin_ads_start_at'),
                'expire_at' => admin_t('db.tf_plugin_ads_expire_at'),
                'impressions' => admin_t('db.tf_plugin_ads_impressions'),
                'clicks' => admin_t('db.tf_plugin_ads_clicks'),
            ],
            'plugin_ad_clicks' => [
                'ad_id' => admin_t('db.tf_plugin_ad_clicks_ad_id'),
                'page' => admin_t('db.tf_plugin_ad_clicks_page'),
            ],
            'plugin_ad_days' => [
                'day_key' => admin_t('db.tf_plugin_ad_days_day_key'),
                'impressions' => admin_t('db.tf_plugin_ad_days_impressions'),
                'clicks' => admin_t('db.tf_plugin_ad_days_clicks'),
            ],
            'plugin_publish_options' => [
                'k' => admin_t('db.tf_plugin_publish_options_k'),
                'v' => admin_t('db.tf_plugin_publish_options_v'),
            ],
            'plugin_chat_messages' => [
                'text' => admin_t('db.tf_plugin_chat_messages_text'),
                'name' => admin_t('db.tf_plugin_chat_messages_name'),
                'status' => admin_t('db.tf_video_types_status'),
                'report' => admin_t('db.tf_video_danmaku_report'),
                'member_id' => admin_t('db.tf_plugin_chat_messages_member_id'),
                'video_id' => admin_t('db.tf_plugin_chat_messages_video_id'),
                'ip' => admin_t('db.tf_plugin_chat_messages_ip'),
            ],
            'plugin_sms_codes' => [
                'code' => admin_t('db.tf_plugin_sms_codes_code'),
                'scene' => admin_t('db.tf_plugin_sms_codes_scene'),
            ],
        ];
    }

    public function guessField(string $field): string
    {
        if (str_ends_with($field, '_id')) {
            return admin_t('db.guess_rel_id');
        }
        if (str_ends_with($field, '_at') || str_ends_with($field, '_time')) {
            return admin_t('ui.time');
        }
        if (str_starts_with($field, 'is_')) {
            return admin_t('db.guess_yesno');
        }
        if (str_starts_with($field, 'seo_')) {
            return admin_t('db.guess_seo');
        }
        if (str_starts_with($field, 'tpl_')) {
            return admin_t('db.guess_tpl');
        }
        if (str_starts_with($field, 'hits_')) {
            return admin_t('db.guess_hits');
        }

        return admin_t('db.guess_fallback');
    }
}
